import React from 'react';
import StoryBook from '../components/StoryBook';
import MeadowScene from '../components/scenes/MeadowScene';

const storyData = {
  title: 'How the Alphabet Was Made',
  audioDir: '/arthurs-world/audio/alphabet-made',
  pages: [
    // ── Page 1: Taffy wants to do better ──
    {
      bg: 'from-purple-300 to-indigo-500',
      image: '/arthurs-world/images/alphabet-made/page-1.png',
      scene: <MeadowScene />,
      text: 'After the funny mix-up with the first letter, Taffy wanted to do BETTER!',
      elements: [
        {
          id: 'taffy',
          x: 40,
          y: 36,
          content: '\uD83D\uDC67',
          size: 76,
          z: 3,
        },
        {
          id: 'daddy',
          x: 68,
          y: 38,
          content: '\uD83E\uDDD4',
          size: 72,
          z: 3,
        },
        {
          id: 'mixed-up-letter',
          x: 20,
          y: 22,
          content: '\u2709\uFE0F',
          size: 44,
          z: 2,
        },
        {
          id: 'lightbulb-idea',
          x: 50,
          y: 14,
          content: '\uD83D\uDCA1',
          size: 48,
          z: 2,
        },
        {
          id: 'hidden-butterfly',
          x: 88,
          y: 18,
          content: '\uD83E\uDD8B',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-wiggle',
          type: 'tap-wiggle',
          targetId: 'taffy',
          data: {},
        },
        {
          id: 'daddy-grow',
          type: 'tap-grow',
          targetId: 'daddy',
          data: {},
        },
        {
          id: 'letter-shake',
          type: 'tap-shake',
          targetId: 'mixed-up-letter',
          data: {},
        },
        {
          id: 'idea-sparkle',
          type: 'tap-sparkle',
          targetId: 'lightbulb-idea',
          data: {},
        },
        {
          id: 'butterfly-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-butterfly',
          data: { content: 'Flutter! \uD83E\uDD8B' },
        },
      ],
    },

    // ── Page 2: Let's make shapes for sounds ──
    {
      bg: 'from-violet-300 to-purple-500',
      image: '/arthurs-world/images/alphabet-made/page-2.png',
      scene: <MeadowScene />,
      text: 'She said to Daddy "Let\'s make shapes for SOUNDS! Then everyone will understand!"',
      elements: [
        {
          id: 'excited-taffy',
          x: 35,
          y: 38,
          content: '\uD83D\uDC67',
          size: 72,
          z: 3,
        },
        {
          id: 'listening-daddy',
          x: 70,
          y: 40,
          content: '\uD83E\uDDD4',
          size: 68,
          z: 3,
        },
        {
          id: 'speech-bubble',
          x: 35,
          y: 16,
          content: '\uD83D\uDCAC',
          size: 48,
          z: 2,
        },
        {
          id: 'music-note',
          x: 15,
          y: 24,
          content: '\uD83C\uDFB5',
          size: 40,
          z: 2,
        },
        {
          id: 'star-sparkle',
          x: 85,
          y: 14,
          content: '\u2728',
          size: 38,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-sound',
          type: 'tap-sound',
          targetId: 'excited-taffy',
          data: { say: 'Let\'s make shapes for sounds!' },
        },
        {
          id: 'daddy-wiggle',
          type: 'tap-wiggle',
          targetId: 'listening-daddy',
          data: {},
        },
        {
          id: 'bubble-spin',
          type: 'tap-spin',
          targetId: 'speech-bubble',
          data: {},
        },
        {
          id: 'note-color',
          type: 'tap-color',
          targetId: 'music-note',
          data: { colors: ['#A78BFA', '#EC4899', '#38BDF8', '#34D399', '#FBBF24'] },
        },
        {
          id: 'star-sparkle-tap',
          type: 'tap-sparkle',
          targetId: 'star-sparkle',
          data: {},
        },
      ],
    },

    // ── Page 3: AAAH becomes A (key alphabet page) ──
    {
      bg: 'from-indigo-300 to-violet-500',
      image: '/arthurs-world/images/alphabet-made/page-3.png',
      scene: <MeadowScene />,
      text: 'Taffy opened her mouth wide and said "AAAH!" Daddy drew a mouth shape \u2014 that became the letter A!',
      elements: [
        {
          id: 'taffy-mouth-open',
          x: 30,
          y: 36,
          content: '\uD83D\uDE2E',
          size: 76,
          z: 3,
        },
        {
          id: 'daddy-drawing',
          x: 68,
          y: 38,
          content: '\u270D\uFE0F',
          size: 56,
          z: 3,
        },
        {
          id: 'sound-to-letter-a',
          x: 50,
          y: 16,
          content: '\uD83D\uDD0A',
          size: 56,
          z: 4,
        },
        {
          id: 'magic-wand',
          x: 85,
          y: 20,
          content: '\uD83E\uDE84',
          size: 40,
          z: 2,
        },
        {
          id: 'hidden-sparkle-a',
          x: 15,
          y: 18,
          content: '\u2728',
          size: 30,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'mouth-sound-a',
          type: 'tap-sound',
          targetId: 'taffy-mouth-open',
          data: { say: 'Aaah!' },
        },
        {
          id: 'sound-swap-to-a',
          type: 'tap-swap',
          targetId: 'sound-to-letter-a',
          data: { altContent: '\uD83C\uDD70\uFE0F' },
        },
        {
          id: 'daddy-animate-draw',
          type: 'tap-animate',
          targetId: 'daddy-drawing',
          data: { animation: 'animate-wiggle', duration: 800 },
        },
        {
          id: 'wand-sparkle',
          type: 'tap-sparkle',
          targetId: 'magic-wand',
          data: {},
        },
        {
          id: 'sparkle-a-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-sparkle-a',
          data: { content: 'A is for AAAH! \u2728' },
        },
      ],
    },

    // ── Page 4: Buh buh becomes B (key alphabet page) ──
    {
      bg: 'from-purple-400 to-indigo-600',
      image: '/arthurs-world/images/alphabet-made/page-4.png',
      scene: <MeadowScene />,
      text: 'Then she made a "Buh buh" sound with her lips. Daddy drew lips together \u2014 that became B!',
      elements: [
        {
          id: 'taffy-lips',
          x: 30,
          y: 36,
          content: '\uD83D\uDC8B',
          size: 72,
          z: 3,
        },
        {
          id: 'daddy-pencil',
          x: 70,
          y: 40,
          content: '\u270F\uFE0F',
          size: 52,
          z: 3,
        },
        {
          id: 'sound-to-letter-b',
          x: 50,
          y: 16,
          content: '\uD83D\uDDE3\uFE0F',
          size: 56,
          z: 4,
        },
        {
          id: 'bee-friend',
          x: 85,
          y: 28,
          content: '\uD83D\uDC1D',
          size: 40,
          z: 2,
        },
        {
          id: 'hidden-flower',
          x: 12,
          y: 60,
          content: '\uD83C\uDF38',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'lips-sound-b',
          type: 'tap-sound',
          targetId: 'taffy-lips',
          data: { say: 'Buh buh buh!' },
        },
        {
          id: 'sound-swap-to-b',
          type: 'tap-swap',
          targetId: 'sound-to-letter-b',
          data: { altContent: '\uD83C\uDD71\uFE0F' },
        },
        {
          id: 'pencil-wiggle',
          type: 'tap-wiggle',
          targetId: 'daddy-pencil',
          data: {},
        },
        {
          id: 'bee-shake',
          type: 'tap-shake',
          targetId: 'bee-friend',
          data: {},
        },
        {
          id: 'flower-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-flower',
          data: { content: 'B is for Buzz! \uD83C\uDF38' },
        },
      ],
    },

    // ── Page 5: Sssss becomes S (key alphabet page) ──
    {
      bg: 'from-indigo-400 to-blue-600',
      image: '/arthurs-world/images/alphabet-made/page-5.png',
      scene: <MeadowScene />,
      text: 'She made a "Sssss" sound like a snake! Daddy drew a wiggly snake \u2014 that became S!',
      elements: [
        {
          id: 'taffy-hissing',
          x: 28,
          y: 36,
          content: '\uD83D\uDC67',
          size: 68,
          z: 3,
        },
        {
          id: 'snake-sound',
          x: 55,
          y: 32,
          content: '\uD83D\uDC0D',
          size: 64,
          z: 3,
        },
        {
          id: 'sound-to-letter-s',
          x: 50,
          y: 14,
          content: '\uD83D\uDD0A',
          size: 52,
          z: 4,
        },
        {
          id: 'wiggly-line',
          x: 82,
          y: 24,
          content: '\u3030\uFE0F',
          size: 44,
          z: 2,
        },
        {
          id: 'grass-tuft',
          x: 15,
          y: 58,
          content: '\uD83C\uDF3F',
          size: 36,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-hiss-sound',
          type: 'tap-sound',
          targetId: 'taffy-hissing',
          data: { say: 'Sssssss!' },
        },
        {
          id: 'sound-swap-to-s',
          type: 'tap-swap',
          targetId: 'sound-to-letter-s',
          data: { altContent: '\uD83C\uDD82' },
        },
        {
          id: 'snake-wiggle',
          type: 'tap-wiggle',
          targetId: 'snake-sound',
          data: {},
        },
        {
          id: 'wiggly-spin',
          type: 'tap-spin',
          targetId: 'wiggly-line',
          data: {},
        },
        {
          id: 'grass-color',
          type: 'tap-color',
          targetId: 'grass-tuft',
          data: { colors: ['#22C55E', '#16A34A', '#4ADE80', '#86EFAC', '#15803D'] },
        },
      ],
    },

    // ── Page 6: O is a round mouth (key alphabet page) ──
    {
      bg: 'from-blue-300 to-indigo-500',
      image: '/arthurs-world/images/alphabet-made/page-6.png',
      scene: <MeadowScene />,
      text: 'They kept going! Every sound got its own special shape! O was a round mouth saying "Ooooh!"',
      elements: [
        {
          id: 'taffy-ooh',
          x: 30,
          y: 36,
          content: '\uD83D\uDE2F',
          size: 72,
          z: 3,
        },
        {
          id: 'daddy-excited',
          x: 72,
          y: 38,
          content: '\uD83E\uDDD4',
          size: 68,
          z: 3,
        },
        {
          id: 'sound-to-letter-o',
          x: 50,
          y: 14,
          content: '\u2B55',
          size: 56,
          z: 4,
        },
        {
          id: 'rainbow-arc',
          x: 50,
          y: 60,
          content: '\uD83C\uDF08',
          size: 48,
          z: 1,
        },
        {
          id: 'hidden-owl',
          x: 88,
          y: 58,
          content: '\uD83E\uDD89',
          size: 30,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-ooh-sound',
          type: 'tap-sound',
          targetId: 'taffy-ooh',
          data: { say: 'Ooooh!' },
        },
        {
          id: 'sound-swap-to-o',
          type: 'tap-swap',
          targetId: 'sound-to-letter-o',
          data: { altContent: '\uD83C\uDD7E\uFE0F' },
        },
        {
          id: 'daddy-sparkle',
          type: 'tap-sparkle',
          targetId: 'daddy-excited',
          data: {},
        },
        {
          id: 'rainbow-color',
          type: 'tap-color',
          targetId: 'rainbow-arc',
          data: { colors: ['#EF4444', '#F97316', '#EAB308', '#22C55E', '#3B82F6', '#8B5CF6'] },
        },
        {
          id: 'owl-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-owl',
          data: { content: 'O is for Owl! \uD83E\uDD89' },
        },
      ],
    },

    // ── Page 7: Lots of letters! ──
    {
      bg: 'from-violet-400 to-purple-600',
      image: '/arthurs-world/images/alphabet-made/page-7.png',
      scene: <MeadowScene />,
      text: 'Soon they had LOTS of letters! A, B, C, D, E, F, G... so many shapes!',
      elements: [
        {
          id: 'letter-a',
          x: 12,
          y: 18,
          content: '\uD83C\uDD70\uFE0F',
          size: 48,
          z: 2,
        },
        {
          id: 'letter-b',
          x: 30,
          y: 14,
          content: '\uD83C\uDD71\uFE0F',
          size: 48,
          z: 2,
        },
        {
          id: 'letter-c',
          x: 50,
          y: 12,
          content: '\u00A9\uFE0F',
          size: 48,
          z: 2,
        },
        {
          id: 'letter-o',
          x: 70,
          y: 14,
          content: '\uD83C\uDD7E\uFE0F',
          size: 48,
          z: 2,
        },
        {
          id: 'letter-s',
          x: 88,
          y: 18,
          content: '\uD83C\uDD82',
          size: 48,
          z: 2,
        },
        {
          id: 'celebration-taffy',
          x: 40,
          y: 40,
          content: '\uD83D\uDC67',
          size: 72,
          z: 3,
        },
      ],
      interactions: [
        {
          id: 'letter-a-count',
          type: 'tap-count',
          targetId: 'letter-a',
          data: { max: 5 },
        },
        {
          id: 'letter-b-spin',
          type: 'tap-spin',
          targetId: 'letter-b',
          data: {},
        },
        {
          id: 'letter-c-wiggle',
          type: 'tap-wiggle',
          targetId: 'letter-c',
          data: {},
        },
        {
          id: 'letter-o-grow',
          type: 'tap-grow',
          targetId: 'letter-o',
          data: {},
        },
        {
          id: 'letter-s-color',
          type: 'tap-color',
          targetId: 'letter-s',
          data: { colors: ['#A78BFA', '#EC4899', '#38BDF8', '#34D399', '#FBBF24', '#EF4444'] },
        },
        {
          id: 'taffy-celebrate-animate',
          type: 'tap-animate',
          targetId: 'celebration-taffy',
          data: { animation: 'animate-dance', duration: 1000 },
        },
      ],
    },

    // ── Page 8: Taffy writes her name (drag-to-target page) ──
    {
      bg: 'from-purple-300 to-violet-500',
      image: '/arthurs-world/images/alphabet-made/page-8.png',
      scene: <MeadowScene />,
      text: 'Now Taffy could write WORDS! She wrote her name: T-A-F-F-Y!',
      elements: [
        {
          id: 'proud-taffy',
          x: 20,
          y: 38,
          content: '\uD83D\uDC67',
          size: 72,
          z: 3,
        },
        {
          id: 'draggable-letter-t',
          x: 80,
          y: 18,
          content: '\uD83C\uDDF9',
          size: 52,
          z: 4,
        },
        {
          id: 'name-slot',
          x: 55,
          y: 40,
          content: '\u2753',
          size: 52,
          z: 3,
        },
        {
          id: 'pencil-writing',
          x: 42,
          y: 18,
          content: '\u270F\uFE0F',
          size: 44,
          z: 2,
        },
        {
          id: 'scroll-paper',
          x: 55,
          y: 58,
          content: '\uD83D\uDCDC',
          size: 48,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'letter-t-drag-to-name',
          type: 'drag-to-target',
          targetId: 'draggable-letter-t',
          data: { dropZone: { x: 55, y: 40, radius: 45 }, onDrop: 'snap' },
        },
        {
          id: 'taffy-name-sound',
          type: 'tap-sound',
          targetId: 'proud-taffy',
          data: { say: 'T, A, F, F, Y! That spells Taffy!' },
        },
        {
          id: 'name-slot-sparkle',
          type: 'tap-sparkle',
          targetId: 'name-slot',
          data: {},
        },
        {
          id: 'pencil-shake',
          type: 'tap-shake',
          targetId: 'pencil-writing',
          data: {},
        },
        {
          id: 'scroll-wiggle',
          type: 'tap-wiggle',
          targetId: 'scroll-paper',
          data: {},
        },
      ],
    },

    // ── Page 9: Teaching friends ──
    {
      bg: 'from-indigo-300 to-purple-500',
      image: '/arthurs-world/images/alphabet-made/page-9.png',
      scene: <MeadowScene />,
      text: 'She taught all her friends the alphabet. Now everyone could read and write!',
      elements: [
        {
          id: 'teacher-taffy',
          x: 45,
          y: 32,
          content: '\uD83D\uDC67',
          size: 72,
          z: 3,
        },
        {
          id: 'friend-bear',
          x: 18,
          y: 44,
          content: '\uD83D\uDC3B',
          size: 56,
          z: 2,
        },
        {
          id: 'friend-rabbit',
          x: 75,
          y: 44,
          content: '\uD83D\uDC30',
          size: 52,
          z: 2,
        },
        {
          id: 'book-open',
          x: 50,
          y: 58,
          content: '\uD83D\uDCD6',
          size: 52,
          z: 2,
        },
        {
          id: 'hidden-fox',
          x: 90,
          y: 62,
          content: '\uD83E\uDD8A',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-teach-sound',
          type: 'tap-sound',
          targetId: 'teacher-taffy',
          data: { say: 'A, B, C! Now you try!' },
        },
        {
          id: 'bear-animate',
          type: 'tap-animate',
          targetId: 'friend-bear',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'rabbit-swap',
          type: 'tap-swap',
          targetId: 'friend-rabbit',
          data: { altContent: '\uD83D\uDC07\uD83D\uDCDA' },
        },
        {
          id: 'book-grow',
          type: 'tap-grow',
          targetId: 'book-open',
          data: {},
        },
        {
          id: 'fox-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-fox',
          data: { content: 'I can read! \uD83E\uDD8A' },
        },
      ],
    },

    // ── Page 10: The End ──
    {
      bg: 'from-violet-300 to-indigo-500',
      image: '/arthurs-world/images/alphabet-made/page-10.png',
      scene: <MeadowScene />,
      text: 'And that is how the alphabet was made! Now YOU can learn your letters too! The end!',
      elements: [
        {
          id: 'waving-taffy',
          x: 35,
          y: 34,
          content: '\uD83D\uDC67',
          size: 80,
          z: 3,
        },
        {
          id: 'waving-daddy',
          x: 65,
          y: 36,
          content: '\uD83E\uDDD4',
          size: 76,
          z: 3,
        },
        {
          id: 'alphabet-star',
          x: 50,
          y: 12,
          content: '\u2B50',
          size: 52,
          z: 2,
        },
        {
          id: 'party-confetti',
          x: 20,
          y: 16,
          content: '\uD83C\uDF89',
          size: 44,
          z: 2,
        },
        {
          id: 'abc-block',
          x: 80,
          y: 18,
          content: '\uD83D\uDD24',
          size: 44,
          z: 2,
        },
        {
          id: 'magic-rainbow',
          x: 50,
          y: 60,
          content: '\uD83C\uDF08',
          size: 48,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-end-sparkle',
          type: 'tap-sparkle',
          targetId: 'waving-taffy',
          data: {},
        },
        {
          id: 'daddy-end-sound',
          type: 'tap-sound',
          targetId: 'waving-daddy',
          data: { say: 'The end! Now you know your letters!' },
        },
        {
          id: 'star-spin',
          type: 'tap-spin',
          targetId: 'alphabet-star',
          data: {},
        },
        {
          id: 'confetti-hide',
          type: 'tap-hide',
          targetId: 'party-confetti',
          data: {},
        },
        {
          id: 'abc-color',
          type: 'tap-color',
          targetId: 'abc-block',
          data: { colors: ['#A78BFA', '#EC4899', '#38BDF8', '#34D399', '#FBBF24', '#EF4444'] },
        },
        {
          id: 'rainbow-wiggle',
          type: 'tap-wiggle',
          targetId: 'magic-rainbow',
          data: {},
        },
      ],
    },
  ],
};

export default function AlphabetMade() {
  return <StoryBook story={storyData} />;
}
