import React from 'react';
import StoryBook from '../components/StoryBook';

const storyData = {
  title: 'The Beginning of the Armadillos',
  audioDir: '/arthurs-world/audio/armadillos',
  pages: [
    // ── Page 1: Meet the best friends ──
    {
      bg: 'from-green-400 to-lime-600',
      image: '/arthurs-world/images/armadillos/page-1.png',
      text: 'Once upon a time, there was a prickly hedgehog and a slow tortoise. They were best friends!',
      elements: [
        {
          id: 'hedgehog',
          x: 30,
          y: 38,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'tortoise',
          x: 68,
          y: 42,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'heart-friends',
          x: 50,
          y: 22,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'jungle-tree',
          x: 10,
          y: 20,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'sun-jungle',
          x: 88,
          y: 12,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'hedgehog-wiggle',
          type: 'tap-wiggle',
          targetId: 'hedgehog',
          data: {},
        },
        {
          id: 'tortoise-wiggle',
          type: 'tap-wiggle',
          targetId: 'tortoise',
          data: {},
        },
        {
          id: 'heart-grow',
          type: 'tap-grow',
          targetId: 'heart-friends',
          data: {},
        },
        {
          id: 'tree-shake',
          type: 'tap-shake',
          targetId: 'jungle-tree',
          data: {},
        },
        {
          id: 'sun-spin',
          type: 'tap-spin',
          targetId: 'sun-jungle',
          data: {},
        },
      ],
    },

    // ── Page 2: The hungry jaguar arrives ──
    {
      bg: 'from-lime-500 to-green-700',
      image: '/arthurs-world/images/armadillos/page-2.png',
      text: 'A hungry jaguar came along! He wanted to eat them for dinner!',
      elements: [
        {
          id: 'jaguar',
          x: 50,
          y: 32,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'scared-hedgehog',
          x: 20,
          y: 50,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'scared-tortoise',
          x: 80,
          y: 52,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'danger-sign',
          x: 50,
          y: 14,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'hidden-parrot',
          x: 12,
          y: 18,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'jungle-bush',
          x: 90,
          y: 30,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'jaguar-sound',
          type: 'tap-sound',
          targetId: 'jaguar',
          data: { say: 'I am SO hungry!' },
        },
        {
          id: 'jaguar-shake',
          type: 'tap-shake',
          targetId: 'jaguar',
          data: {},
        },
        {
          id: 'hedgehog-scared-wiggle',
          type: 'tap-wiggle',
          targetId: 'scared-hedgehog',
          data: {},
        },
        {
          id: 'danger-color',
          type: 'tap-color',
          targetId: 'danger-sign',
          data: { colors: ['#EF4444', '#F59E0B', '#EF4444', '#F59E0B'] },
        },
        {
          id: 'parrot-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-parrot',
          data: { content: 'Squawk!' },
        },
        {
          id: 'bush-wiggle',
          type: 'tap-wiggle',
          targetId: 'jungle-bush',
          data: {},
        },
      ],
    },

    // ── Page 3: Hedgehog curls into a ball ──
    {
      bg: 'from-green-500 to-emerald-700',
      image: '/arthurs-world/images/armadillos/page-3.png',
      text: 'The hedgehog curled into a prickly ball! "Ouch!" said the jaguar. "Too prickly!"',
      elements: [
        {
          id: 'curled-hedgehog',
          x: 35,
          y: 42,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'ouch-jaguar',
          x: 68,
          y: 38,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'ouch-effect',
          x: 52,
          y: 22,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'prickle-stars',
          x: 25,
          y: 26,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'watching-tortoise',
          x: 88,
          y: 55,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'hedgehog-grow-ball',
          type: 'tap-grow',
          targetId: 'curled-hedgehog',
          data: {},
        },
        {
          id: 'jaguar-ouch-sound',
          type: 'tap-sound',
          targetId: 'ouch-jaguar',
          data: { say: 'Ouch! Too prickly!' },
        },
        {
          id: 'ouch-sparkle',
          type: 'tap-sparkle',
          targetId: 'ouch-effect',
          data: {},
        },
        {
          id: 'prickle-spin',
          type: 'tap-spin',
          targetId: 'prickle-stars',
          data: {},
        },
        {
          id: 'tortoise-wiggle-watch',
          type: 'tap-wiggle',
          targetId: 'watching-tortoise',
          data: {},
        },
      ],
    },

    // ── Page 4: Tortoise hides in her shell ──
    {
      bg: 'from-emerald-400 to-green-700',
      image: '/arthurs-world/images/armadillos/page-4.png',
      text: 'The tortoise hid inside her hard shell! "I can\'t bite through that!" said the jaguar.',
      elements: [
        {
          id: 'shelled-tortoise',
          x: 35,
          y: 44,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'biting-jaguar',
          x: 65,
          y: 38,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'shield-effect',
          x: 30,
          y: 28,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'tooth-break',
          x: 72,
          y: 22,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'watching-hedgehog',
          x: 12,
          y: 55,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'tortoise-shell-shake',
          type: 'tap-shake',
          targetId: 'shelled-tortoise',
          data: {},
        },
        {
          id: 'jaguar-bite-sound',
          type: 'tap-sound',
          targetId: 'biting-jaguar',
          data: { say: 'I cannot bite through that!' },
        },
        {
          id: 'shield-sparkle',
          type: 'tap-sparkle',
          targetId: 'shield-effect',
          data: {},
        },
        {
          id: 'tooth-wiggle',
          type: 'tap-wiggle',
          targetId: 'tooth-break',
          data: {},
        },
        {
          id: 'hedgehog-count-cheers',
          type: 'tap-count',
          targetId: 'watching-hedgehog',
          data: { max: 5 },
        },
      ],
    },

    // ── Page 5: Mama jaguar gives advice ──
    {
      bg: 'from-yellow-600 to-amber-800',
      image: '/arthurs-world/images/armadillos/page-5.png',
      text: 'The jaguar\'s mother said "If it curls up, it\'s a hedgehog. If it has a shell, it\'s a tortoise."',
      elements: [
        {
          id: 'mama-jaguar',
          x: 50,
          y: 32,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'baby-jaguar',
          x: 25,
          y: 48,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'speech-bubble',
          x: 65,
          y: 15,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'thinking-face',
          x: 18,
          y: 25,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'hidden-monkey',
          x: 88,
          y: 45,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'moon-night',
          x: 85,
          y: 10,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'mama-advice-sound',
          type: 'tap-sound',
          targetId: 'mama-jaguar',
          data: { say: 'If it curls up, it is a hedgehog. If it has a shell, it is a tortoise.' },
        },
        {
          id: 'mama-grow',
          type: 'tap-grow',
          targetId: 'mama-jaguar',
          data: {},
        },
        {
          id: 'baby-animate-nod',
          type: 'tap-animate',
          targetId: 'baby-jaguar',
          data: { animation: 'animate-bounce', duration: 800 },
        },
        {
          id: 'bubble-spin',
          type: 'tap-spin',
          targetId: 'speech-bubble',
          data: {},
        },
        {
          id: 'monkey-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-monkey',
          data: { content: 'Hee hee!' },
        },
        {
          id: 'moon-color',
          type: 'tap-color',
          targetId: 'moon-night',
          data: { colors: ['#FBBF24', '#F8FAFC', '#FBBF24'] },
        },
      ],
    },

    // ── Page 6: Learning each other's tricks ──
    {
      bg: 'from-lime-400 to-green-600',
      image: '/arthurs-world/images/armadillos/page-6.png',
      text: 'But clever hedgehog learned to swim like tortoise! And tortoise learned to curl up like hedgehog!',
      elements: [
        {
          id: 'swimming-hedgehog',
          x: 30,
          y: 40,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'curling-tortoise',
          x: 70,
          y: 38,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'water-splash',
          x: 25,
          y: 58,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'swap-arrows',
          x: 50,
          y: 24,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'clever-lightbulb',
          x: 50,
          y: 10,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'hedgehog-swap-tortoise',
          type: 'tap-swap',
          targetId: 'swimming-hedgehog',
          data: { altContent: 'Tortoise' },
        },
        {
          id: 'tortoise-swap-hedgehog',
          type: 'tap-swap',
          targetId: 'curling-tortoise',
          data: { altContent: 'Hedgehog' },
        },
        {
          id: 'splash-sparkle',
          type: 'tap-sparkle',
          targetId: 'water-splash',
          data: {},
        },
        {
          id: 'arrows-spin',
          type: 'tap-spin',
          targetId: 'swap-arrows',
          data: {},
        },
        {
          id: 'lightbulb-color',
          type: 'tap-color',
          targetId: 'clever-lightbulb',
          data: { colors: ['#FBBF24', '#FDE68A', '#F59E0B', '#FBBF24'] },
        },
      ],
    },

    // ── Page 7: The confused jaguar ──
    {
      bg: 'from-green-500 to-lime-700',
      image: '/arthurs-world/images/armadillos/page-7.png',
      text: 'The jaguar was SO confused! "Which one is which? I can\'t tell!"',
      elements: [
        {
          id: 'confused-jaguar',
          x: 50,
          y: 35,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'tricky-animal-left',
          x: 20,
          y: 50,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'tricky-animal-right',
          x: 80,
          y: 50,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'dizzy-stars',
          x: 50,
          y: 16,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'question-marks',
          x: 38,
          y: 20,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'hidden-snake',
          x: 90,
          y: 25,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'jaguar-confused-sound',
          type: 'tap-sound',
          targetId: 'confused-jaguar',
          data: { say: 'Which one is which? I cannot tell!' },
        },
        {
          id: 'jaguar-confused-shake',
          type: 'tap-shake',
          targetId: 'confused-jaguar',
          data: {},
        },
        {
          id: 'left-animal-swap',
          type: 'tap-swap',
          targetId: 'tricky-animal-left',
          data: { altContent: 'Tortoise' },
        },
        {
          id: 'right-animal-swap',
          type: 'tap-swap',
          targetId: 'tricky-animal-right',
          data: { altContent: 'Hedgehog' },
        },
        {
          id: 'dizzy-spin',
          type: 'tap-spin',
          targetId: 'dizzy-stars',
          data: {},
        },
        {
          id: 'snake-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-snake',
          data: { content: 'Hissss!' },
        },
      ],
    },

    // ── Page 8: THE TRANSFORMATION (key page) ──
    {
      bg: 'from-amber-400 to-yellow-600',
      image: '/arthurs-world/images/armadillos/page-8.png',
      text: 'They mixed up so much that they turned into something NEW \u2014 an armadillo!',
      elements: [
        {
          id: 'draggable-hedgehog',
          x: 22,
          y: 38,
          z: 4,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'target-tortoise',
          x: 72,
          y: 40,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'magic-sparkles',
          x: 50,
          y: 20,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'transform-swirl',
          x: 50,
          y: 55,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'new-armadillo',
          x: 50,
          y: 40,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'hedgehog-drag-to-tortoise',
          type: 'drag-to-target',
          targetId: 'draggable-hedgehog',
          data: { dropZone: { x: 72, y: 40, radius: 50 }, onDrop: 'snap' },
        },
        {
          id: 'tortoise-swap-armadillo',
          type: 'tap-swap',
          targetId: 'target-tortoise',
          data: { altContent: 'Armadillo!' },
        },
        {
          id: 'magic-sparkle-burst',
          type: 'tap-sparkle',
          targetId: 'magic-sparkles',
          data: {},
        },
        {
          id: 'swirl-spin',
          type: 'tap-spin',
          targetId: 'transform-swirl',
          data: {},
        },
        {
          id: 'armadillo-reveal-new',
          type: 'tap-reveal',
          targetId: 'new-armadillo',
          data: { content: 'NEW ANIMAL!' },
        },
      ],
    },

    // ── Page 9: The armadillo's powers ──
    {
      bg: 'from-lime-500 to-emerald-700',
      image: '/arthurs-world/images/armadillos/page-9.png',
      text: 'The armadillo had a hard shell AND could curl into a ball! The jaguar couldn\'t catch him at all!',
      elements: [
        {
          id: 'armadillo-hero',
          x: 45,
          y: 38,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'running-jaguar',
          x: 82,
          y: 45,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'shell-icon',
          x: 25,
          y: 20,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'ball-icon',
          x: 65,
          y: 18,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'victory-star',
          x: 45,
          y: 12,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'hidden-toucan',
          x: 10,
          y: 50,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'armadillo-grow-strong',
          type: 'tap-grow',
          targetId: 'armadillo-hero',
          data: {},
        },
        {
          id: 'armadillo-sound',
          type: 'tap-sound',
          targetId: 'armadillo-hero',
          data: { say: 'You cannot catch me!' },
        },
        {
          id: 'jaguar-hide-run',
          type: 'tap-hide',
          targetId: 'running-jaguar',
          data: {},
        },
        {
          id: 'shell-shake',
          type: 'tap-shake',
          targetId: 'shell-icon',
          data: {},
        },
        {
          id: 'ball-spin',
          type: 'tap-spin',
          targetId: 'ball-icon',
          data: {},
        },
        {
          id: 'toucan-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-toucan',
          data: { content: 'Hooray!' },
        },
      ],
    },

    // ── Page 10: The End ──
    {
      bg: 'from-green-300 to-lime-500',
      image: '/arthurs-world/images/armadillos/page-10.png',
      text: 'And that is how armadillos began! They\'re part hedgehog and part tortoise! The end!',
      elements: [
        {
          id: 'final-armadillo',
          x: 45,
          y: 35,
          z: 3,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'mini-hedgehog',
          x: 18,
          y: 48,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'mini-tortoise',
          x: 78,
          y: 48,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'party-popper',
          x: 30,
          y: 16,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'celebration-star',
          x: 65,
          y: 14,
          z: 2,
          hotspot: true,
          w: 120,
          h: 100,
        },
        {
          id: 'rainbow',
          x: 50,
          y: 8,
          z: 1,
          hotspot: true,
          w: 120,
          h: 100,
        },
      ],
      interactions: [
        {
          id: 'armadillo-end-sparkle',
          type: 'tap-sparkle',
          targetId: 'final-armadillo',
          data: {},
        },
        {
          id: 'armadillo-end-sound',
          type: 'tap-sound',
          targetId: 'final-armadillo',
          data: { say: 'The end!' },
        },
        {
          id: 'hedgehog-dance',
          type: 'tap-animate',
          targetId: 'mini-hedgehog',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'tortoise-dance',
          type: 'tap-animate',
          targetId: 'mini-tortoise',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'popper-spin',
          type: 'tap-spin',
          targetId: 'party-popper',
          data: {},
        },
        {
          id: 'star-color',
          type: 'tap-color',
          targetId: 'celebration-star',
          data: { colors: ['#FBBF24', '#EF4444', '#8B5CF6', '#3B82F6', '#10B981', '#EC4899'] },
        },
      ],
    },
  ],
};

export default function Armadillos() {
  return <StoryBook story={storyData} />;
}
