import React from 'react';
import StoryBook from '../components/StoryBook';
import MeadowScene from '../components/scenes/MeadowScene';

const storyData = {
  title: 'The Butterfly That Stamped',
  audioDir: '/arthurs-world/audio/butterfly-stamped',
  pages: [
    // ── Page 1: King Solomon the wise ──
    {
      bg: 'from-amber-300 to-purple-500',
      image: '/arthurs-world/images/butterfly-stamped/page-1.png',
      scene: <MeadowScene />,
      text: 'King Solomon was the wisest king in the whole world. He could talk to ALL the animals!',
      elements: [
        {
          id: 'king-solomon',
          x: 50,
          y: 35,
          content: '\uD83E\uDD34',
          size: 80,
          z: 3,
        },
        {
          id: 'palace',
          x: 50,
          y: 14,
          content: '\uD83C\uDFF0',
          size: 64,
          z: 1,
        },
        {
          id: 'bird-friend',
          x: 18,
          y: 28,
          content: '\uD83D\uDC26',
          size: 40,
          z: 2,
        },
        {
          id: 'cat-friend',
          x: 80,
          y: 48,
          content: '\uD83D\uDC31',
          size: 38,
          z: 2,
        },
        {
          id: 'crown-sparkle',
          x: 50,
          y: 18,
          content: '\uD83D\uDC51',
          size: 36,
          z: 4,
        },
      ],
      interactions: [
        {
          id: 'solomon-sound',
          type: 'tap-sound',
          targetId: 'king-solomon',
          data: { say: 'Hello animals! I can talk to all of you!' },
        },
        {
          id: 'palace-sparkle',
          type: 'tap-sparkle',
          targetId: 'palace',
          data: {},
        },
        {
          id: 'bird-wiggle',
          type: 'tap-wiggle',
          targetId: 'bird-friend',
          data: {},
        },
        {
          id: 'cat-grow',
          type: 'tap-grow',
          targetId: 'cat-friend',
          data: {},
        },
        {
          id: 'crown-spin',
          type: 'tap-spin',
          targetId: 'crown-sparkle',
          data: {},
        },
      ],
    },

    // ── Page 2: The butterfly friend ──
    {
      bg: 'from-pink-300 to-purple-500',
      image: '/arthurs-world/images/butterfly-stamped/page-2.png',
      scene: <MeadowScene />,
      text: 'He had a beautiful butterfly friend. But the butterfly liked to show off to his wife!',
      elements: [
        {
          id: 'butterfly-husband',
          x: 35,
          y: 32,
          content: '\uD83E\uDD8B',
          size: 72,
          z: 3,
        },
        {
          id: 'butterfly-wife',
          x: 65,
          y: 34,
          content: '\uD83E\uDD8B',
          size: 64,
          z: 3,
        },
        {
          id: 'flower-pink',
          x: 20,
          y: 58,
          content: '\uD83C\uDF38',
          size: 40,
          z: 1,
        },
        {
          id: 'flower-yellow',
          x: 80,
          y: 60,
          content: '\uD83C\uDF3B',
          size: 38,
          z: 1,
        },
        {
          id: 'hidden-ladybug',
          x: 90,
          y: 52,
          content: '\uD83D\uDC1E',
          size: 26,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'husband-color',
          type: 'tap-color',
          targetId: 'butterfly-husband',
          data: { colors: ['#EC4899', '#8B5CF6', '#3B82F6', '#F59E0B', '#10B981'] },
        },
        {
          id: 'wife-wiggle',
          type: 'tap-wiggle',
          targetId: 'butterfly-wife',
          data: {},
        },
        {
          id: 'pink-flower-sparkle',
          type: 'tap-sparkle',
          targetId: 'flower-pink',
          data: {},
        },
        {
          id: 'yellow-flower-spin',
          type: 'tap-spin',
          targetId: 'flower-yellow',
          data: {},
        },
        {
          id: 'ladybug-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-ladybug',
          data: { content: 'Hi there! \uD83D\uDC1E' },
        },
      ],
    },

    // ── Page 3: The butterfly shows off ──
    {
      bg: 'from-purple-400 to-pink-600',
      image: '/arthurs-world/images/butterfly-stamped/page-3.png',
      scene: <MeadowScene />,
      text: 'The butterfly said to his wife "I am SO powerful! Watch \u2014 if I stamp my foot, the palace will disappear!"',
      elements: [
        {
          id: 'boasting-butterfly',
          x: 40,
          y: 35,
          content: '\uD83E\uDD8B',
          size: 76,
          z: 3,
        },
        {
          id: 'speech-bubble',
          x: 55,
          y: 16,
          content: '\uD83D\uDCAC',
          size: 44,
          z: 2,
        },
        {
          id: 'palace-bg',
          x: 50,
          y: 10,
          content: '\uD83C\uDFF0',
          size: 56,
          z: 1,
        },
        {
          id: 'wife-listening',
          x: 75,
          y: 38,
          content: '\uD83E\uDD8B',
          size: 56,
          z: 2,
        },
        {
          id: 'flexing-arm',
          x: 25,
          y: 25,
          content: '\uD83D\uDCAA',
          size: 44,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'boast-sound',
          type: 'tap-sound',
          targetId: 'boasting-butterfly',
          data: { say: 'I am SO powerful! Watch this!' },
        },
        {
          id: 'boast-grow',
          type: 'tap-grow',
          targetId: 'boasting-butterfly',
          data: {},
        },
        {
          id: 'bubble-shake',
          type: 'tap-shake',
          targetId: 'speech-bubble',
          data: {},
        },
        {
          id: 'palace-shimmer',
          type: 'tap-sparkle',
          targetId: 'palace-bg',
          data: {},
        },
        {
          id: 'flex-animate',
          type: 'tap-animate',
          targetId: 'flexing-arm',
          data: { animation: 'animate-bounce', duration: 800 },
        },
      ],
    },

    // ── Page 4: Wife laughs ──
    {
      bg: 'from-pink-400 to-rose-600',
      image: '/arthurs-world/images/butterfly-stamped/page-4.png',
      scene: <MeadowScene />,
      text: 'His wife laughed! "You\'re just a tiny butterfly! You can\'t make a palace disappear!"',
      elements: [
        {
          id: 'laughing-wife',
          x: 55,
          y: 34,
          content: '\uD83E\uDD8B',
          size: 72,
          z: 3,
        },
        {
          id: 'laugh-face',
          x: 70,
          y: 18,
          content: '\uD83D\uDE02',
          size: 48,
          z: 2,
        },
        {
          id: 'embarrassed-butterfly',
          x: 30,
          y: 38,
          content: '\uD83E\uDD8B',
          size: 60,
          z: 3,
        },
        {
          id: 'tiny-palace',
          x: 50,
          y: 12,
          content: '\uD83C\uDFF0',
          size: 48,
          z: 1,
        },
        {
          id: 'giggle-stars',
          x: 82,
          y: 28,
          content: '\u2728',
          size: 32,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'wife-laugh-sound',
          type: 'tap-sound',
          targetId: 'laughing-wife',
          data: { say: 'Ha ha ha! You are just a tiny butterfly!' },
        },
        {
          id: 'laugh-face-spin',
          type: 'tap-spin',
          targetId: 'laugh-face',
          data: {},
        },
        {
          id: 'embarrassed-shake',
          type: 'tap-shake',
          targetId: 'embarrassed-butterfly',
          data: {},
        },
        {
          id: 'palace-swap',
          type: 'tap-swap',
          targetId: 'tiny-palace',
          data: { altContent: '\uD83C\uDFDA\uFE0F' },
        },
        {
          id: 'stars-count',
          type: 'tap-count',
          targetId: 'giggle-stars',
          data: { max: 5 },
        },
      ],
    },

    // ── Page 5: Butterfly asks Solomon for help (drag-to-target) ──
    {
      bg: 'from-amber-400 to-purple-600',
      image: '/arthurs-world/images/butterfly-stamped/page-5.png',
      scene: <MeadowScene />,
      text: 'The butterfly was worried. He\'d been showing off and now he was stuck! He went to ask King Solomon for help.',
      elements: [
        {
          id: 'worried-butterfly',
          x: 20,
          y: 35,
          content: '\uD83E\uDD8B',
          size: 64,
          z: 4,
        },
        {
          id: 'solomon-throne',
          x: 75,
          y: 32,
          content: '\uD83E\uDD34',
          size: 76,
          z: 3,
        },
        {
          id: 'worried-face',
          x: 15,
          y: 18,
          content: '\uD83D\uDE1F',
          size: 40,
          z: 2,
        },
        {
          id: 'throne-chair',
          x: 75,
          y: 50,
          content: '\uD83E\uDE91',
          size: 44,
          z: 1,
        },
        {
          id: 'hidden-mouse',
          x: 88,
          y: 60,
          content: '\uD83D\uDC2D',
          size: 26,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'butterfly-drag-to-solomon',
          type: 'drag-to-target',
          targetId: 'worried-butterfly',
          data: { dropZone: { x: 75, y: 32, radius: 45 }, onDrop: 'snap' },
        },
        {
          id: 'solomon-sound',
          type: 'tap-sound',
          targetId: 'solomon-throne',
          data: { say: 'Come here little butterfly, tell me what happened!' },
        },
        {
          id: 'worry-wiggle',
          type: 'tap-wiggle',
          targetId: 'worried-face',
          data: {},
        },
        {
          id: 'throne-sparkle',
          type: 'tap-sparkle',
          targetId: 'throne-chair',
          data: {},
        },
        {
          id: 'mouse-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-mouse',
          data: { content: 'Squeak! \uD83D\uDC2D' },
        },
      ],
    },

    // ── Page 6: Solomon helps ──
    {
      bg: 'from-amber-300 to-yellow-500',
      image: '/arthurs-world/images/butterfly-stamped/page-6.png',
      scene: <MeadowScene />,
      text: 'Kind King Solomon said "Don\'t worry little friend! When you stamp, I\'ll use MY magic!"',
      elements: [
        {
          id: 'kind-solomon',
          x: 45,
          y: 32,
          content: '\uD83E\uDD34',
          size: 80,
          z: 3,
        },
        {
          id: 'grateful-butterfly',
          x: 65,
          y: 25,
          content: '\uD83E\uDD8B',
          size: 56,
          z: 3,
        },
        {
          id: 'magic-wand',
          x: 30,
          y: 22,
          content: '\uD83E\uDE84',
          size: 48,
          z: 2,
        },
        {
          id: 'heart',
          x: 55,
          y: 15,
          content: '\u2764\uFE0F',
          size: 36,
          z: 2,
        },
        {
          id: 'magic-sparkles',
          x: 80,
          y: 45,
          content: '\u2728',
          size: 40,
          z: 2,
        },
        {
          id: 'hidden-bee',
          x: 12,
          y: 55,
          content: '\uD83D\uDC1D',
          size: 24,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'solomon-help-sound',
          type: 'tap-sound',
          targetId: 'kind-solomon',
          data: { say: 'Don\'t worry little friend! I will use my magic!' },
        },
        {
          id: 'butterfly-animate-happy',
          type: 'tap-animate',
          targetId: 'grateful-butterfly',
          data: { animation: 'animate-fly', duration: 1000 },
        },
        {
          id: 'wand-sparkle',
          type: 'tap-sparkle',
          targetId: 'magic-wand',
          data: {},
        },
        {
          id: 'heart-grow',
          type: 'tap-grow',
          targetId: 'heart',
          data: {},
        },
        {
          id: 'sparkles-color',
          type: 'tap-color',
          targetId: 'magic-sparkles',
          data: { colors: ['#FBBF24', '#EC4899', '#8B5CF6', '#3B82F6', '#10B981'] },
        },
        {
          id: 'bee-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-bee',
          data: { content: 'Buzz buzz! \uD83D\uDC1D' },
        },
      ],
    },

    // ── Page 7: THE BIG STAMP! (key page) ──
    {
      bg: 'from-purple-500 to-pink-600',
      image: '/arthurs-world/images/butterfly-stamped/page-7.png',
      scene: <MeadowScene />,
      text: 'The butterfly stamped his tiny foot \u2014 STAMP! And King Solomon made the palace shimmer and shake!',
      elements: [
        {
          id: 'stamping-butterfly',
          x: 40,
          y: 38,
          content: '\uD83E\uDD8B',
          size: 80,
          z: 4,
        },
        {
          id: 'shaking-palace',
          x: 50,
          y: 12,
          content: '\uD83C\uDFF0',
          size: 72,
          z: 2,
        },
        {
          id: 'magic-solomon',
          x: 75,
          y: 35,
          content: '\uD83E\uDD34',
          size: 68,
          z: 3,
        },
        {
          id: 'stamp-explosion',
          x: 35,
          y: 55,
          content: '\uD83D\uDCA5',
          size: 52,
          z: 3,
        },
        {
          id: 'magic-stars',
          x: 20,
          y: 15,
          content: '\uD83C\uDF1F',
          size: 44,
          z: 2,
        },
        {
          id: 'wow-text',
          x: 65,
          y: 18,
          content: '\u2757',
          size: 48,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'butterfly-stamp-sparkle',
          type: 'tap-sparkle',
          targetId: 'stamping-butterfly',
          data: {},
        },
        {
          id: 'palace-shake',
          type: 'tap-shake',
          targetId: 'shaking-palace',
          data: {},
        },
        {
          id: 'solomon-magic-sound',
          type: 'tap-sound',
          targetId: 'magic-solomon',
          data: { say: 'Abracadabra! Shimmer and shake!' },
        },
        {
          id: 'explosion-grow',
          type: 'tap-grow',
          targetId: 'stamp-explosion',
          data: {},
        },
        {
          id: 'stars-spin',
          type: 'tap-spin',
          targetId: 'magic-stars',
          data: {},
        },
        {
          id: 'wow-wiggle',
          type: 'tap-wiggle',
          targetId: 'wow-text',
          data: {},
        },
      ],
    },

    // ── Page 8: Wife is amazed ──
    {
      bg: 'from-pink-400 to-purple-600',
      image: '/arthurs-world/images/butterfly-stamped/page-8.png',
      scene: <MeadowScene />,
      text: 'The butterfly\'s wife was AMAZED! "Wow! You really ARE powerful!" she said.',
      elements: [
        {
          id: 'amazed-wife',
          x: 55,
          y: 34,
          content: '\uD83E\uDD8B',
          size: 72,
          z: 3,
        },
        {
          id: 'proud-butterfly',
          x: 30,
          y: 36,
          content: '\uD83E\uDD8B',
          size: 68,
          z: 3,
        },
        {
          id: 'wow-face',
          x: 70,
          y: 16,
          content: '\uD83D\uDE32',
          size: 48,
          z: 2,
        },
        {
          id: 'celebration-confetti',
          x: 15,
          y: 20,
          content: '\uD83C\uDF89',
          size: 40,
          z: 2,
        },
        {
          id: 'sparkle-trail',
          x: 85,
          y: 42,
          content: '\u2728',
          size: 36,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'wife-amazed-sound',
          type: 'tap-sound',
          targetId: 'amazed-wife',
          data: { say: 'Wow! You really are powerful!' },
        },
        {
          id: 'proud-animate',
          type: 'tap-animate',
          targetId: 'proud-butterfly',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'wow-shake',
          type: 'tap-shake',
          targetId: 'wow-face',
          data: {},
        },
        {
          id: 'confetti-spin',
          type: 'tap-spin',
          targetId: 'celebration-confetti',
          data: {},
        },
        {
          id: 'sparkle-hide',
          type: 'tap-hide',
          targetId: 'sparkle-trail',
          data: {},
        },
      ],
    },

    // ── Page 9: The lesson ──
    {
      bg: 'from-amber-300 to-pink-500',
      image: '/arthurs-world/images/butterfly-stamped/page-9.png',
      scene: <MeadowScene />,
      text: 'But the butterfly learned his lesson \u2014 it\'s not nice to show off. Being kind is better than being powerful!',
      elements: [
        {
          id: 'wise-butterfly',
          x: 45,
          y: 35,
          content: '\uD83E\uDD8B',
          size: 76,
          z: 3,
        },
        {
          id: 'kind-heart',
          x: 50,
          y: 15,
          content: '\uD83D\uDC96',
          size: 52,
          z: 2,
        },
        {
          id: 'wife-happy',
          x: 72,
          y: 38,
          content: '\uD83E\uDD8B',
          size: 56,
          z: 2,
        },
        {
          id: 'gentle-flower',
          x: 18,
          y: 55,
          content: '\uD83C\uDF3A',
          size: 38,
          z: 1,
        },
        {
          id: 'peace-dove',
          x: 82,
          y: 18,
          content: '\uD83D\uDD4A\uFE0F',
          size: 36,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'wise-butterfly-sparkle',
          type: 'tap-sparkle',
          targetId: 'wise-butterfly',
          data: {},
        },
        {
          id: 'heart-color',
          type: 'tap-color',
          targetId: 'kind-heart',
          data: { colors: ['#EC4899', '#EF4444', '#F59E0B', '#A855F7', '#F472B6'] },
        },
        {
          id: 'wife-happy-wiggle',
          type: 'tap-wiggle',
          targetId: 'wife-happy',
          data: {},
        },
        {
          id: 'flower-grow',
          type: 'tap-grow',
          targetId: 'gentle-flower',
          data: {},
        },
        {
          id: 'dove-animate',
          type: 'tap-animate',
          targetId: 'peace-dove',
          data: { animation: 'animate-fly', duration: 1200 },
        },
      ],
    },

    // ── Page 10: The end ──
    {
      bg: 'from-pink-300 to-amber-400',
      image: '/arthurs-world/images/butterfly-stamped/page-10.png',
      scene: <MeadowScene />,
      text: 'And that is the story of the butterfly that stamped! Even tiny creatures can do big things! The end!',
      elements: [
        {
          id: 'hero-butterfly',
          x: 45,
          y: 32,
          content: '\uD83E\uDD8B',
          size: 84,
          z: 3,
        },
        {
          id: 'solomon-waving',
          x: 75,
          y: 38,
          content: '\uD83E\uDD34',
          size: 64,
          z: 2,
        },
        {
          id: 'wife-waving',
          x: 18,
          y: 40,
          content: '\uD83E\uDD8B',
          size: 56,
          z: 2,
        },
        {
          id: 'end-star',
          x: 50,
          y: 12,
          content: '\u2B50',
          size: 48,
          z: 2,
        },
        {
          id: 'end-rainbow',
          x: 30,
          y: 15,
          content: '\uD83C\uDF08',
          size: 44,
          z: 1,
        },
        {
          id: 'end-party',
          x: 70,
          y: 18,
          content: '\uD83C\uDF89',
          size: 40,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'hero-end-sparkle',
          type: 'tap-sparkle',
          targetId: 'hero-butterfly',
          data: {},
        },
        {
          id: 'hero-end-sound',
          type: 'tap-sound',
          targetId: 'hero-butterfly',
          data: { say: 'The end! Even tiny creatures can do big things!' },
        },
        {
          id: 'solomon-wave-wiggle',
          type: 'tap-wiggle',
          targetId: 'solomon-waving',
          data: {},
        },
        {
          id: 'wife-wave-animate',
          type: 'tap-animate',
          targetId: 'wife-waving',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'star-swap',
          type: 'tap-swap',
          targetId: 'end-star',
          data: { altContent: '\uD83C\uDF1F' },
        },
        {
          id: 'party-spin',
          type: 'tap-spin',
          targetId: 'end-party',
          data: {},
        },
      ],
    },
  ],
};

export default function ButterflyStamped() {
  return <StoryBook story={storyData} />;
}
