import React from 'react';
import StoryBook from '../components/StoryBook';
import MeadowScene from '../components/scenes/MeadowScene';

const storyData = {
  title: 'How the Camel Got His Hump',
  audioDir: '/arthurs-world/audio/camel-hump',
  pages: [
    // ── Page 1: The Lazy Camel ──
    {
      bg: 'from-amber-300 to-orange-500',
      image: '/arthurs-world/images/camel-hump/page-1.png',
      scene: <MeadowScene />,
      text: 'Once upon a time, there was a very lazy camel who lived in the desert.',
      elements: [
        {
          id: 'camel',
          x: 50,
          y: 40,
          content: '\uD83D\uDC2B',
          size: 80,
          z: 3,
        },
        {
          id: 'sun',
          x: 82,
          y: 15,
          content: '\u2600\uFE0F',
          size: 56,
          z: 1,
        },
        {
          id: 'cactus-left',
          x: 12,
          y: 55,
          content: '\uD83C\uDF35',
          size: 48,
          z: 2,
        },
        {
          id: 'cactus-right',
          x: 88,
          y: 52,
          content: '\uD83C\uDF35',
          size: 42,
          z: 2,
        },
        {
          id: 'hidden-lizard',
          x: 22,
          y: 68,
          content: '\uD83E\uDD8E',
          size: 24,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'camel-lazy-sound',
          type: 'tap-sound',
          targetId: 'camel',
          data: { say: 'Zzzzzz...' },
        },
        {
          id: 'camel-wiggle',
          type: 'tap-wiggle',
          targetId: 'camel',
          data: {},
        },
        {
          id: 'sun-spin',
          type: 'tap-spin',
          targetId: 'sun',
          data: {},
        },
        {
          id: 'cactus-left-shake',
          type: 'tap-shake',
          targetId: 'cactus-left',
          data: {},
        },
        {
          id: 'lizard-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-lizard',
          data: { content: 'A lizard! \uD83E\uDD8E' },
        },
      ],
    },

    // ── Page 2: The Horse Asks ──
    {
      bg: 'from-amber-200 to-yellow-500',
      image: '/arthurs-world/images/camel-hump/page-2.png',
      scene: <MeadowScene />,
      text: 'The horse asked the camel to help. The camel just said HUMPH!',
      elements: [
        {
          id: 'horse',
          x: 25,
          y: 40,
          content: '\uD83D\uDC34',
          size: 64,
          z: 3,
        },
        {
          id: 'grumpy-camel',
          x: 70,
          y: 42,
          content: '\uD83D\uDC2B',
          size: 72,
          z: 3,
        },
        {
          id: 'speech-humph',
          x: 70,
          y: 18,
          content: '\uD83D\uDCAC',
          size: 44,
          z: 2,
        },
        {
          id: 'hay-bale',
          x: 15,
          y: 62,
          content: '\uD83C\uDF3E',
          size: 36,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'camel-humph-sound',
          type: 'tap-sound',
          targetId: 'grumpy-camel',
          data: { say: 'HUMPH!' },
        },
        {
          id: 'camel-shake',
          type: 'tap-shake',
          targetId: 'grumpy-camel',
          data: {},
        },
        {
          id: 'horse-wiggle',
          type: 'tap-wiggle',
          targetId: 'horse',
          data: {},
        },
        {
          id: 'speech-sparkle',
          type: 'tap-sparkle',
          targetId: 'speech-humph',
          data: {},
        },
        {
          id: 'hay-count',
          type: 'tap-count',
          targetId: 'hay-bale',
          data: { max: 3 },
        },
      ],
    },

    // ── Page 3: The Dog Asks ──
    {
      bg: 'from-amber-300 to-orange-400',
      image: '/arthurs-world/images/camel-hump/page-3.png',
      scene: <MeadowScene />,
      text: 'The dog asked the camel to help. The camel just said HUMPH!',
      elements: [
        {
          id: 'dog',
          x: 25,
          y: 42,
          content: '\uD83D\uDC15',
          size: 60,
          z: 3,
        },
        {
          id: 'grumpy-camel-2',
          x: 70,
          y: 40,
          content: '\uD83D\uDC2B',
          size: 72,
          z: 3,
        },
        {
          id: 'speech-humph-2',
          x: 70,
          y: 16,
          content: '\uD83D\uDCAC',
          size: 44,
          z: 2,
        },
        {
          id: 'stick',
          x: 42,
          y: 60,
          content: '\uD83E\uDEB5',
          size: 32,
          z: 1,
        },
        {
          id: 'hidden-beetle',
          x: 88,
          y: 65,
          content: '\uD83E\uDEB2',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'camel-humph-sound-2',
          type: 'tap-sound',
          targetId: 'grumpy-camel-2',
          data: { say: 'HUMPH!' },
        },
        {
          id: 'dog-wiggle',
          type: 'tap-wiggle',
          targetId: 'dog',
          data: {},
        },
        {
          id: 'speech-2-grow',
          type: 'tap-grow',
          targetId: 'speech-humph-2',
          data: {},
        },
        {
          id: 'stick-spin',
          type: 'tap-spin',
          targetId: 'stick',
          data: {},
        },
        {
          id: 'beetle-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-beetle',
          data: { content: 'A beetle! \uD83E\uDEB2' },
        },
      ],
    },

    // ── Page 4: The Ox Asks ──
    {
      bg: 'from-yellow-300 to-amber-500',
      image: '/arthurs-world/images/camel-hump/page-4.png',
      scene: <MeadowScene />,
      text: 'The ox asked the camel to help. The camel just said HUMPH!',
      elements: [
        {
          id: 'ox',
          x: 25,
          y: 40,
          content: '\uD83D\uDC02',
          size: 64,
          z: 3,
        },
        {
          id: 'grumpy-camel-3',
          x: 72,
          y: 40,
          content: '\uD83D\uDC2B',
          size: 72,
          z: 3,
        },
        {
          id: 'speech-humph-3',
          x: 72,
          y: 16,
          content: '\uD83D\uDCAC',
          size: 48,
          z: 2,
        },
        {
          id: 'plow',
          x: 42,
          y: 62,
          content: '\u2692\uFE0F',
          size: 36,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'camel-humph-sound-3',
          type: 'tap-sound',
          targetId: 'grumpy-camel-3',
          data: { say: 'HUMPH!' },
        },
        {
          id: 'camel-3-shake',
          type: 'tap-shake',
          targetId: 'grumpy-camel-3',
          data: {},
        },
        {
          id: 'ox-grow',
          type: 'tap-grow',
          targetId: 'ox',
          data: {},
        },
        {
          id: 'speech-3-sparkle',
          type: 'tap-sparkle',
          targetId: 'speech-humph-3',
          data: {},
        },
        {
          id: 'plow-wiggle',
          type: 'tap-wiggle',
          targetId: 'plow',
          data: {},
        },
      ],
    },

    // ── Page 5: Extra Work ──
    {
      bg: 'from-orange-300 to-red-400',
      image: '/arthurs-world/images/camel-hump/page-5.png',
      scene: <MeadowScene />,
      text: "All the animals had to do extra work because the lazy camel wouldn't help!",
      elements: [
        {
          id: 'tired-horse',
          x: 18,
          y: 38,
          content: '\uD83D\uDC34',
          size: 56,
          z: 3,
        },
        {
          id: 'tired-dog',
          x: 45,
          y: 42,
          content: '\uD83D\uDC15',
          size: 52,
          z: 3,
        },
        {
          id: 'tired-ox',
          x: 72,
          y: 38,
          content: '\uD83D\uDC02',
          size: 56,
          z: 3,
        },
        {
          id: 'sweat-drops',
          x: 45,
          y: 22,
          content: '\uD83D\uDCA6',
          size: 36,
          z: 2,
        },
        {
          id: 'tired-face',
          x: 45,
          y: 62,
          content: '\uD83E\uDD71',
          size: 40,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'horse-tired-animate',
          type: 'tap-animate',
          targetId: 'tired-horse',
          data: { animation: 'animate-bounce', duration: 800 },
        },
        {
          id: 'dog-tired-shake',
          type: 'tap-shake',
          targetId: 'tired-dog',
          data: {},
        },
        {
          id: 'ox-tired-wiggle',
          type: 'tap-wiggle',
          targetId: 'tired-ox',
          data: {},
        },
        {
          id: 'sweat-sparkle',
          type: 'tap-sparkle',
          targetId: 'sweat-drops',
          data: {},
        },
        {
          id: 'tired-face-color',
          type: 'tap-color',
          targetId: 'tired-face',
          data: { colors: ['#EF4444', '#F59E0B', '#6366F1', '#EC4899'] },
        },
      ],
    },

    // ── Page 6: The Genie Appears ──
    {
      bg: 'from-purple-400 to-indigo-600',
      image: '/arthurs-world/images/camel-hump/page-6.png',
      scene: <MeadowScene />,
      text: 'A magic genie appeared from the desert! Whoooosh!',
      elements: [
        {
          id: 'genie',
          x: 45,
          y: 35,
          content: '\uD83E\uDDDE',
          size: 76,
          z: 3,
        },
        {
          id: 'sparkles-left',
          x: 18,
          y: 30,
          content: '\u2728',
          size: 40,
          z: 2,
        },
        {
          id: 'sparkles-right',
          x: 78,
          y: 28,
          content: '\u2728',
          size: 36,
          z: 2,
        },
        {
          id: 'magic-swirl',
          x: 45,
          y: 60,
          content: '\uD83C\uDF00',
          size: 44,
          z: 1,
        },
        {
          id: 'scared-camel',
          x: 82,
          y: 48,
          content: '\uD83D\uDC2B',
          size: 56,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'genie-sparkle',
          type: 'tap-sparkle',
          targetId: 'genie',
          data: {},
        },
        {
          id: 'genie-whoosh-sound',
          type: 'tap-sound',
          targetId: 'genie',
          data: { say: 'Whoooosh!' },
        },
        {
          id: 'sparkles-left-spin',
          type: 'tap-spin',
          targetId: 'sparkles-left',
          data: {},
        },
        {
          id: 'magic-swirl-animate',
          type: 'tap-animate',
          targetId: 'magic-swirl',
          data: { animation: 'animate-spin360', duration: 1000 },
        },
        {
          id: 'camel-scared-shake',
          type: 'tap-shake',
          targetId: 'scared-camel',
          data: {},
        },
      ],
    },

    // ── Page 7: Genie Confronts Camel ──
    {
      bg: 'from-violet-400 to-purple-600',
      image: '/arthurs-world/images/camel-hump/page-7.png',
      scene: <MeadowScene />,
      text: "The genie said: Camel, why won't you work? The camel said HUMPH again!",
      elements: [
        {
          id: 'angry-genie',
          x: 30,
          y: 35,
          content: '\uD83E\uDDDE',
          size: 68,
          z: 3,
        },
        {
          id: 'stubborn-camel',
          x: 72,
          y: 42,
          content: '\uD83D\uDC2B',
          size: 72,
          z: 3,
        },
        {
          id: 'humph-bubble',
          x: 72,
          y: 18,
          content: '\uD83D\uDCAC',
          size: 44,
          z: 2,
        },
        {
          id: 'angry-symbol',
          x: 30,
          y: 14,
          content: '\uD83D\uDCA2',
          size: 32,
          z: 2,
        },
        {
          id: 'hidden-scorpion',
          x: 52,
          y: 68,
          content: '\uD83E\uDD82',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'camel-humph-again-sound',
          type: 'tap-sound',
          targetId: 'stubborn-camel',
          data: { say: 'HUMPH!' },
        },
        {
          id: 'genie-grow',
          type: 'tap-grow',
          targetId: 'angry-genie',
          data: {},
        },
        {
          id: 'humph-bubble-shake',
          type: 'tap-shake',
          targetId: 'humph-bubble',
          data: {},
        },
        {
          id: 'angry-sparkle',
          type: 'tap-sparkle',
          targetId: 'angry-symbol',
          data: {},
        },
        {
          id: 'scorpion-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-scorpion',
          data: { content: 'A scorpion! \uD83E\uDD82' },
        },
      ],
    },

    // ── Page 8: POOF! The Hump Grows ──
    {
      bg: 'from-fuchsia-400 to-purple-700',
      image: '/arthurs-world/images/camel-hump/page-8.png',
      scene: <MeadowScene />,
      text: 'The genie waved his hands and POOF! A big hump grew on the camel\'s back!',
      elements: [
        {
          id: 'magic-genie',
          x: 22,
          y: 32,
          content: '\uD83E\uDDDE',
          size: 64,
          z: 3,
        },
        {
          id: 'camel-transforming',
          x: 68,
          y: 40,
          content: '\uD83D\uDC2B',
          size: 76,
          z: 3,
        },
        {
          id: 'poof-effect',
          x: 68,
          y: 22,
          content: '\uD83D\uDCA5',
          size: 52,
          z: 2,
        },
        {
          id: 'sparkle-burst-1',
          x: 42,
          y: 38,
          content: '\u2728',
          size: 36,
          z: 2,
        },
        {
          id: 'sparkle-burst-2',
          x: 85,
          y: 30,
          content: '\u2728',
          size: 32,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'camel-swap-hump',
          type: 'tap-swap',
          targetId: 'camel-transforming',
          data: { altContent: '\uD83D\uDC2A' },
        },
        {
          id: 'poof-sound',
          type: 'tap-sound',
          targetId: 'poof-effect',
          data: { say: 'POOF!' },
        },
        {
          id: 'camel-grow-hump',
          type: 'tap-grow',
          targetId: 'camel-transforming',
          data: {},
        },
        {
          id: 'sparkle-1-sparkle',
          type: 'tap-sparkle',
          targetId: 'sparkle-burst-1',
          data: {},
        },
        {
          id: 'genie-magic-animate',
          type: 'tap-animate',
          targetId: 'magic-genie',
          data: { animation: 'animate-dance', duration: 1000 },
        },
      ],
    },

    // ── Page 9: The Hump Works ──
    {
      bg: 'from-sky-300 to-amber-400',
      image: '/arthurs-world/images/camel-hump/page-9.png',
      scene: <MeadowScene />,
      text: 'Now the camel could carry water in his hump and work for days and days!',
      elements: [
        {
          id: 'working-camel',
          x: 50,
          y: 38,
          content: '\uD83D\uDC2A',
          size: 80,
          z: 3,
        },
        {
          id: 'water-drop-1',
          x: 30,
          y: 22,
          content: '\uD83D\uDCA7',
          size: 32,
          z: 2,
        },
        {
          id: 'water-drop-2',
          x: 68,
          y: 20,
          content: '\uD83D\uDCA7',
          size: 28,
          z: 2,
        },
        {
          id: 'sun-bright',
          x: 85,
          y: 12,
          content: '\u2600\uFE0F',
          size: 48,
          z: 1,
        },
        {
          id: 'water-drop-target',
          x: 50,
          y: 28,
          content: '',
          size: 10,
          z: 0,
        },
      ],
      interactions: [
        {
          id: 'camel-working-animate',
          type: 'tap-animate',
          targetId: 'working-camel',
          data: { animation: 'animate-bounce', duration: 800 },
        },
        {
          id: 'camel-happy-sound',
          type: 'tap-sound',
          targetId: 'working-camel',
          data: { say: 'I can work now!' },
        },
        {
          id: 'water-1-drag',
          type: 'drag-to-target',
          targetId: 'water-drop-1',
          data: { dropZone: { x: 50, y: 28, radius: 40 }, onDrop: 'snap' },
        },
        {
          id: 'water-2-sparkle',
          type: 'tap-sparkle',
          targetId: 'water-drop-2',
          data: {},
        },
        {
          id: 'sun-spin',
          type: 'tap-spin',
          targetId: 'sun-bright',
          data: {},
        },
      ],
    },

    // ── Page 10: The End ──
    {
      bg: 'from-green-300 to-amber-400',
      image: '/arthurs-world/images/camel-hump/page-10.png',
      scene: <MeadowScene />,
      text: 'And that is how the camel got his hump! The end!',
      elements: [
        {
          id: 'happy-camel',
          x: 50,
          y: 36,
          content: '\uD83D\uDC2A',
          size: 76,
          z: 3,
        },
        {
          id: 'happy-horse',
          x: 18,
          y: 44,
          content: '\uD83D\uDC34',
          size: 52,
          z: 2,
        },
        {
          id: 'happy-dog',
          x: 82,
          y: 46,
          content: '\uD83D\uDC15',
          size: 48,
          z: 2,
        },
        {
          id: 'happy-ox',
          x: 35,
          y: 58,
          content: '\uD83D\uDC02',
          size: 50,
          z: 2,
        },
        {
          id: 'hearts',
          x: 50,
          y: 16,
          content: '\u2764\uFE0F',
          size: 40,
          z: 2,
        },
        {
          id: 'hidden-snake',
          x: 68,
          y: 66,
          content: '\uD83D\uDC0D',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'camel-happy-sparkle',
          type: 'tap-sparkle',
          targetId: 'happy-camel',
          data: {},
        },
        {
          id: 'camel-end-sound',
          type: 'tap-sound',
          targetId: 'happy-camel',
          data: { say: 'The end!' },
        },
        {
          id: 'horse-end-animate',
          type: 'tap-animate',
          targetId: 'happy-horse',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'hearts-color',
          type: 'tap-color',
          targetId: 'hearts',
          data: { colors: ['#EF4444', '#EC4899', '#F59E0B', '#8B5CF6', '#10B981'] },
        },
        {
          id: 'snake-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-snake',
          data: { content: 'A sneaky snake! \uD83D\uDC0D' },
        },
      ],
    },
  ],
};

export default function CamelHump() {
  return <StoryBook story={storyData} />;
}
