import React from 'react';
import StoryBook from '../components/StoryBook';
import UnderwaterScene from '../components/scenes/UnderwaterScene';

const storyData = {
  title: 'The Crab That Played with the Sea',
  audioDir: '/arthurs-world/audio/crab-sea',
  pages: [
    // ── Page 1: The Eldest Magician makes the world ──
    {
      bg: 'from-cyan-300 to-blue-500',
      image: '/arthurs-world/images/crab-sea/page-1.png',
      scene: <UnderwaterScene />,
      text: 'In the very beginning, the Eldest Magician was making the world. He told all the animals to play!',
      elements: [
        {
          id: 'magician',
          x: 50,
          y: 32,
          content: '\uD83E\uDDD9',
          size: 72,
          z: 3,
        },
        {
          id: 'sparkle-wand',
          x: 65,
          y: 25,
          content: '\u2728',
          size: 40,
          z: 2,
        },
        {
          id: 'globe',
          x: 30,
          y: 50,
          content: '\uD83C\uDF0D',
          size: 52,
          z: 2,
        },
        {
          id: 'star-top',
          x: 80,
          y: 18,
          content: '\u2B50',
          size: 32,
          z: 1,
        },
        {
          id: 'rainbow',
          x: 18,
          y: 22,
          content: '\uD83C\uDF08',
          size: 44,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'magician-sparkle',
          type: 'tap-sparkle',
          targetId: 'magician',
          data: {},
        },
        {
          id: 'wand-wiggle',
          type: 'tap-wiggle',
          targetId: 'sparkle-wand',
          data: {},
        },
        {
          id: 'globe-spin',
          type: 'tap-spin',
          targetId: 'globe',
          data: {},
        },
        {
          id: 'star-color',
          type: 'tap-color',
          targetId: 'star-top',
          data: { colors: ['#FACC15', '#EC4899', '#38BDF8', '#22C55E', '#A78BFA'] },
        },
        {
          id: 'rainbow-grow',
          type: 'tap-grow',
          targetId: 'rainbow',
          data: {},
        },
      ],
    },

    // ── Page 2: Animals playing ──
    {
      bg: 'from-teal-300 to-cyan-500',
      image: '/arthurs-world/images/crab-sea/page-2.png',
      scene: <UnderwaterScene />,
      text: 'The elephant played at being an elephant. The cow played at being a cow. Everyone was happy!',
      elements: [
        {
          id: 'elephant',
          x: 25,
          y: 35,
          content: '\uD83D\uDC18',
          size: 64,
          z: 3,
        },
        {
          id: 'cow',
          x: 70,
          y: 38,
          content: '\uD83D\uDC04',
          size: 56,
          z: 3,
        },
        {
          id: 'bird',
          x: 50,
          y: 20,
          content: '\uD83D\uDC26',
          size: 40,
          z: 2,
        },
        {
          id: 'flower',
          x: 85,
          y: 60,
          content: '\uD83C\uDF3B',
          size: 36,
          z: 1,
        },
        {
          id: 'happy-sun',
          x: 15,
          y: 18,
          content: '\u2600\uFE0F',
          size: 48,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'elephant-sound',
          type: 'tap-sound',
          targetId: 'elephant',
          data: { say: 'Trumpet! I am an elephant!' },
        },
        {
          id: 'cow-sound',
          type: 'tap-sound',
          targetId: 'cow',
          data: { say: 'Moo! I am a cow!' },
        },
        {
          id: 'bird-animate',
          type: 'tap-animate',
          targetId: 'bird',
          data: { animation: 'animate-fly', duration: 1000 },
        },
        {
          id: 'flower-wiggle',
          type: 'tap-wiggle',
          targetId: 'flower',
          data: {},
        },
        {
          id: 'sun-sparkle',
          type: 'tap-sparkle',
          targetId: 'happy-sun',
          data: {},
        },
      ],
    },

    // ── Page 3: Crab goes to the sea ──
    {
      bg: 'from-cyan-400 to-blue-600',
      image: '/arthurs-world/images/crab-sea/page-3.png',
      scene: <UnderwaterScene />,
      text: 'But one little crab went down to the sea and started playing with the water \u2014 splash, splash!',
      elements: [
        {
          id: 'big-crab',
          x: 45,
          y: 42,
          content: '\uD83E\uDD80',
          size: 68,
          z: 3,
        },
        {
          id: 'splash-left',
          x: 25,
          y: 35,
          content: '\uD83D\uDCA6',
          size: 44,
          z: 2,
        },
        {
          id: 'splash-right',
          x: 72,
          y: 30,
          content: '\uD83D\uDCA6',
          size: 40,
          z: 2,
        },
        {
          id: 'wave-bg',
          x: 50,
          y: 60,
          content: '\uD83C\uDF0A',
          size: 48,
          z: 1,
        },
        {
          id: 'hidden-shell',
          x: 88,
          y: 65,
          content: '\uD83D\uDC1A',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'crab-shake',
          type: 'tap-shake',
          targetId: 'big-crab',
          data: {},
        },
        {
          id: 'splash-left-sparkle',
          type: 'tap-sparkle',
          targetId: 'splash-left',
          data: {},
        },
        {
          id: 'splash-right-wiggle',
          type: 'tap-wiggle',
          targetId: 'splash-right',
          data: {},
        },
        {
          id: 'wave-bg-color',
          type: 'tap-color',
          targetId: 'wave-bg',
          data: { colors: ['#0EA5E9', '#06B6D4', '#2DD4BF', '#0284C7', '#0891B2'] },
        },
        {
          id: 'shell-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-shell',
          data: { content: 'A pretty shell! \uD83D\uDC1A' },
        },
      ],
    },

    // ── Page 4: Water rises (key splash page) ──
    {
      bg: 'from-blue-500 to-blue-800',
      image: '/arthurs-world/images/crab-sea/page-4.png',
      scene: <UnderwaterScene />,
      text: 'The crab was SO big and strong! When he went IN the water, it rose up high!',
      elements: [
        {
          id: 'strong-crab',
          x: 40,
          y: 45,
          content: '\uD83E\uDD80',
          size: 80,
          z: 3,
        },
        {
          id: 'wave-up-1',
          x: 20,
          y: 25,
          content: '\uD83C\uDF0A',
          size: 56,
          z: 2,
        },
        {
          id: 'wave-up-2',
          x: 75,
          y: 22,
          content: '\uD83C\uDF0A',
          size: 52,
          z: 2,
        },
        {
          id: 'up-arrow',
          x: 60,
          y: 18,
          content: '\u2B06\uFE0F',
          size: 44,
          z: 2,
        },
        {
          id: 'big-splash',
          x: 50,
          y: 62,
          content: '\uD83D\uDCA6',
          size: 48,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'crab-grow-big',
          type: 'tap-grow',
          targetId: 'strong-crab',
          data: {},
        },
        {
          id: 'wave-up-1-shake',
          type: 'tap-shake',
          targetId: 'wave-up-1',
          data: {},
        },
        {
          id: 'wave-up-2-shake',
          type: 'tap-shake',
          targetId: 'wave-up-2',
          data: {},
        },
        {
          id: 'arrow-animate',
          type: 'tap-animate',
          targetId: 'up-arrow',
          data: { animation: 'animate-bounce', duration: 1000 },
        },
        {
          id: 'splash-sound',
          type: 'tap-sound',
          targetId: 'big-splash',
          data: { say: 'SPLASH! The water goes UP!' },
        },
      ],
    },

    // ── Page 5: Water goes down (key splash page) ──
    {
      bg: 'from-cyan-500 to-blue-700',
      image: '/arthurs-world/images/crab-sea/page-5.png',
      scene: <UnderwaterScene />,
      text: 'When the crab came OUT of the water, it went down low! In and out, up and down!',
      elements: [
        {
          id: 'out-crab',
          x: 45,
          y: 30,
          content: '\uD83E\uDD80',
          size: 76,
          z: 3,
        },
        {
          id: 'down-arrow',
          x: 25,
          y: 55,
          content: '\u2B07\uFE0F',
          size: 44,
          z: 2,
        },
        {
          id: 'low-wave',
          x: 50,
          y: 65,
          content: '\uD83C\uDF0A',
          size: 52,
          z: 2,
        },
        {
          id: 'drip',
          x: 70,
          y: 48,
          content: '\uD83D\uDCA7',
          size: 36,
          z: 1,
        },
        {
          id: 'count-splashes',
          x: 82,
          y: 28,
          content: '\uD83D\uDCA6',
          size: 40,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'crab-out-wiggle',
          type: 'tap-wiggle',
          targetId: 'out-crab',
          data: {},
        },
        {
          id: 'crab-out-sound',
          type: 'tap-sound',
          targetId: 'out-crab',
          data: { say: 'In and out! Up and down!' },
        },
        {
          id: 'down-arrow-spin',
          type: 'tap-spin',
          targetId: 'down-arrow',
          data: {},
        },
        {
          id: 'low-wave-shake',
          type: 'tap-shake',
          targetId: 'low-wave',
          data: {},
        },
        {
          id: 'splash-count',
          type: 'tap-count',
          targetId: 'count-splashes',
          data: { max: 5 },
        },
      ],
    },

    // ── Page 6: Magician notices ──
    {
      bg: 'from-teal-400 to-blue-600',
      image: '/arthurs-world/images/crab-sea/page-6.png',
      scene: <UnderwaterScene />,
      text: 'The Eldest Magician said "Who is playing with my sea? The water keeps going up and down!"',
      elements: [
        {
          id: 'angry-magician',
          x: 35,
          y: 30,
          content: '\uD83E\uDDD9',
          size: 72,
          z: 3,
        },
        {
          id: 'question-mark',
          x: 55,
          y: 20,
          content: '\u2753',
          size: 44,
          z: 2,
        },
        {
          id: 'wobbly-wave',
          x: 50,
          y: 60,
          content: '\uD83C\uDF0A',
          size: 52,
          z: 2,
        },
        {
          id: 'magic-staff',
          x: 18,
          y: 42,
          content: '\uD83E\uDE84',
          size: 48,
          z: 2,
        },
        {
          id: 'hidden-crab-peek',
          x: 80,
          y: 62,
          content: '\uD83E\uDD80',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'magician-shake',
          type: 'tap-shake',
          targetId: 'angry-magician',
          data: {},
        },
        {
          id: 'question-spin',
          type: 'tap-spin',
          targetId: 'question-mark',
          data: {},
        },
        {
          id: 'wave-wiggle',
          type: 'tap-wiggle',
          targetId: 'wobbly-wave',
          data: {},
        },
        {
          id: 'staff-sparkle',
          type: 'tap-sparkle',
          targetId: 'magic-staff',
          data: {},
        },
        {
          id: 'crab-peek-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-crab-peek',
          data: { content: 'Peek-a-boo! \uD83E\uDD80' },
        },
      ],
    },

    // ── Page 7: Little girl Doris tells ──
    {
      bg: 'from-cyan-300 to-teal-500',
      image: '/arthurs-world/images/crab-sea/page-7.png',
      scene: <UnderwaterScene />,
      text: "Little girl Doris said \"It's the big crab, Mr Magician! He's making the water go whoosh!\"",
      elements: [
        {
          id: 'doris',
          x: 60,
          y: 35,
          content: '\uD83D\uDC67',
          size: 64,
          z: 3,
        },
        {
          id: 'doris-magician',
          x: 25,
          y: 32,
          content: '\uD83E\uDDD9',
          size: 60,
          z: 3,
        },
        {
          id: 'pointing-hand',
          x: 72,
          y: 50,
          content: '\uD83D\uDC49',
          size: 40,
          z: 2,
        },
        {
          id: 'naughty-crab',
          x: 85,
          y: 58,
          content: '\uD83E\uDD80',
          size: 48,
          z: 2,
        },
        {
          id: 'speech-whoosh',
          x: 48,
          y: 18,
          content: '\uD83D\uDCAC',
          size: 40,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'doris-sound',
          type: 'tap-sound',
          targetId: 'doris',
          data: { say: "It's the crab! He's making the water go whoosh!" },
        },
        {
          id: 'doris-animate',
          type: 'tap-animate',
          targetId: 'doris',
          data: { animation: 'animate-bounce', duration: 800 },
        },
        {
          id: 'magician-grow',
          type: 'tap-grow',
          targetId: 'doris-magician',
          data: {},
        },
        {
          id: 'naughty-crab-wiggle',
          type: 'tap-wiggle',
          targetId: 'naughty-crab',
          data: {},
        },
        {
          id: 'speech-sparkle',
          type: 'tap-sparkle',
          targetId: 'speech-whoosh',
          data: {},
        },
      ],
    },

    // ── Page 8: Magician makes crab small ──
    {
      bg: 'from-blue-400 to-indigo-600',
      image: '/arthurs-world/images/crab-sea/page-8.png',
      scene: <UnderwaterScene />,
      text: 'The Magician made the crab small with his magic! Now the crab was tiny!',
      elements: [
        {
          id: 'magic-magician',
          x: 30,
          y: 32,
          content: '\uD83E\uDDD9',
          size: 72,
          z: 3,
        },
        {
          id: 'shrinking-crab',
          x: 65,
          y: 55,
          content: '\uD83E\uDD80',
          size: 28,
          z: 3,
        },
        {
          id: 'magic-zap',
          x: 48,
          y: 40,
          content: '\u26A1',
          size: 44,
          z: 2,
        },
        {
          id: 'magic-stars',
          x: 75,
          y: 35,
          content: '\u2728',
          size: 36,
          z: 2,
        },
        {
          id: 'tiny-label',
          x: 65,
          y: 70,
          content: '\uD83D\uDD2C',
          size: 32,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'magic-zap-sparkle',
          type: 'tap-sparkle',
          targetId: 'magic-zap',
          data: {},
        },
        {
          id: 'crab-swap-tiny',
          type: 'tap-swap',
          targetId: 'shrinking-crab',
          data: { altContent: '\uD83E\uDD80' },
        },
        {
          id: 'magician-sound',
          type: 'tap-sound',
          targetId: 'magic-magician',
          data: { say: 'Be SMALL, little crab!' },
        },
        {
          id: 'stars-spin',
          type: 'tap-spin',
          targetId: 'magic-stars',
          data: {},
        },
        {
          id: 'tiny-label-color',
          type: 'tap-color',
          targetId: 'tiny-label',
          data: { colors: ['#8B5CF6', '#EC4899', '#06B6D4', '#F59E0B', '#10B981'] },
        },
      ],
    },

    // ── Page 9: Crab still plays — that's the tides! (drag-to-target) ──
    {
      bg: 'from-cyan-400 to-blue-600',
      image: '/arthurs-world/images/crab-sea/page-9.png',
      scene: <UnderwaterScene />,
      text: "But the little crab STILL plays with the sea! In and out, in and out \u2014 that's the TIDES!",
      elements: [
        {
          id: 'tide-crab',
          x: 25,
          y: 35,
          content: '\uD83E\uDD80',
          size: 56,
          z: 3,
        },
        {
          id: 'tide-water',
          x: 70,
          y: 50,
          content: '\uD83C\uDF0A',
          size: 60,
          z: 2,
        },
        {
          id: 'tide-up',
          x: 82,
          y: 25,
          content: '\u2B06\uFE0F',
          size: 36,
          z: 1,
        },
        {
          id: 'tide-down',
          x: 82,
          y: 65,
          content: '\u2B07\uFE0F',
          size: 36,
          z: 1,
        },
        {
          id: 'hidden-starfish',
          x: 15,
          y: 68,
          content: '\u2B50',
          size: 24,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'crab-drag-to-sea',
          type: 'drag-to-target',
          targetId: 'tide-crab',
          data: { dropZone: { x: 70, y: 50, radius: 45 }, onDrop: 'snap' },
        },
        {
          id: 'tide-water-shake',
          type: 'tap-shake',
          targetId: 'tide-water',
          data: {},
        },
        {
          id: 'tide-up-wiggle',
          type: 'tap-wiggle',
          targetId: 'tide-up',
          data: {},
        },
        {
          id: 'tide-down-wiggle',
          type: 'tap-wiggle',
          targetId: 'tide-down',
          data: {},
        },
        {
          id: 'starfish-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-starfish',
          data: { content: 'A starfish! \u2B50' },
        },
      ],
    },

    // ── Page 10: The end — sea goes up and down! ──
    {
      bg: 'from-teal-300 to-cyan-500',
      image: '/arthurs-world/images/crab-sea/page-10.png',
      scene: <UnderwaterScene />,
      text: 'And that is why the sea goes up and down every day! The crab is still playing! The end!',
      elements: [
        {
          id: 'happy-crab',
          x: 45,
          y: 40,
          content: '\uD83E\uDD80',
          size: 64,
          z: 3,
        },
        {
          id: 'end-wave-1',
          x: 20,
          y: 55,
          content: '\uD83C\uDF0A',
          size: 48,
          z: 2,
        },
        {
          id: 'end-wave-2',
          x: 75,
          y: 52,
          content: '\uD83C\uDF0A',
          size: 44,
          z: 2,
        },
        {
          id: 'end-fish',
          x: 60,
          y: 62,
          content: '\uD83D\uDC20',
          size: 36,
          z: 2,
        },
        {
          id: 'end-sun',
          x: 50,
          y: 15,
          content: '\uD83C\uDF05',
          size: 56,
          z: 1,
        },
        {
          id: 'end-heart',
          x: 15,
          y: 25,
          content: '\u2764\uFE0F',
          size: 36,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'happy-crab-animate',
          type: 'tap-animate',
          targetId: 'happy-crab',
          data: { animation: 'animate-dance', duration: 1200 },
        },
        {
          id: 'happy-crab-sound',
          type: 'tap-sound',
          targetId: 'happy-crab',
          data: { say: 'I love playing with the sea!' },
        },
        {
          id: 'wave-1-wiggle',
          type: 'tap-wiggle',
          targetId: 'end-wave-1',
          data: {},
        },
        {
          id: 'wave-2-wiggle',
          type: 'tap-wiggle',
          targetId: 'end-wave-2',
          data: {},
        },
        {
          id: 'fish-hide',
          type: 'tap-hide',
          targetId: 'end-fish',
          data: {},
        },
        {
          id: 'sun-sparkle',
          type: 'tap-sparkle',
          targetId: 'end-sun',
          data: {},
        },
        {
          id: 'heart-grow',
          type: 'tap-grow',
          targetId: 'end-heart',
          data: {},
        },
      ],
    },
  ],
};

export default function CrabSea() {
  return <StoryBook story={storyData} />;
}
