import React from 'react';
import StoryBook from '../components/StoryBook';
import MeadowScene from '../components/scenes/MeadowScene';

const storyData = {
  title: "The Elephant's Child",
  audioDir: '/arthurs-world/audio/elephant-child',
  pages: [
    // ── Page 1: Short-nosed elephants ──
    {
      bg: 'from-green-400 to-emerald-600',
      image: '/arthurs-world/images/elephant-child/page-1.png',
      scene: <MeadowScene />,
      text: 'Once upon a time, elephants had short, stubby noses. This little elephant was VERY curious!',
      elements: [
        {
          id: 'baby-elephant',
          x: 50,
          y: 38,
          content: '\uD83D\uDC18',
          size: 80,
          z: 3,
        },
        {
          id: 'mama-elephant',
          x: 20,
          y: 35,
          content: '\uD83D\uDC18',
          size: 64,
          z: 2,
        },
        {
          id: 'tree-left',
          x: 10,
          y: 22,
          content: '\uD83C\uDF33',
          size: 52,
          z: 1,
        },
        {
          id: 'sun',
          x: 85,
          y: 12,
          content: '\u2600\uFE0F',
          size: 56,
          z: 1,
        },
        {
          id: 'butterfly',
          x: 72,
          y: 28,
          content: '\uD83E\uDD8B',
          size: 36,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'elephant-wiggle',
          type: 'tap-wiggle',
          targetId: 'baby-elephant',
          data: {},
        },
        {
          id: 'elephant-curious-sound',
          type: 'tap-sound',
          targetId: 'baby-elephant',
          data: { say: 'Why? Why? Why?' },
        },
        {
          id: 'mama-grow',
          type: 'tap-grow',
          targetId: 'mama-elephant',
          data: {},
        },
        {
          id: 'sun-spin',
          type: 'tap-spin',
          targetId: 'sun',
          data: {},
        },
        {
          id: 'butterfly-sparkle',
          type: 'tap-sparkle',
          targetId: 'butterfly',
          data: {},
        },
      ],
    },

    // ── Page 2: Asking questions ──
    {
      bg: 'from-green-500 to-emerald-700',
      image: '/arthurs-world/images/elephant-child/page-2.png',
      scene: <MeadowScene />,
      text: 'He asked everyone questions! "What does the crocodile eat for dinner?" Nobody would tell him!',
      elements: [
        {
          id: 'curious-elephant',
          x: 50,
          y: 40,
          content: '\uD83D\uDC18',
          size: 72,
          z: 3,
        },
        {
          id: 'giraffe',
          x: 18,
          y: 28,
          content: '\uD83E\uDD92',
          size: 56,
          z: 2,
        },
        {
          id: 'zebra',
          x: 82,
          y: 38,
          content: '\uD83E\uDD93',
          size: 52,
          z: 2,
        },
        {
          id: 'question-mark',
          x: 60,
          y: 18,
          content: '\u2753',
          size: 44,
          z: 2,
        },
        {
          id: 'hidden-bird',
          x: 88,
          y: 15,
          content: '\uD83D\uDC26',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'elephant-ask-sound',
          type: 'tap-sound',
          targetId: 'curious-elephant',
          data: { say: 'What does the crocodile eat?' },
        },
        {
          id: 'giraffe-shake',
          type: 'tap-shake',
          targetId: 'giraffe',
          data: {},
        },
        {
          id: 'zebra-swap',
          type: 'tap-swap',
          targetId: 'zebra',
          data: { altContent: '\uD83D\uDE44' },
        },
        {
          id: 'question-count',
          type: 'tap-count',
          targetId: 'question-mark',
          data: { max: 5 },
        },
        {
          id: 'bird-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-bird',
          data: { content: 'Tweet tweet! \uD83D\uDC26' },
        },
      ],
    },

    // ── Page 3: Aunty Hippo ──
    {
      bg: 'from-emerald-400 to-green-600',
      image: '/arthurs-world/images/elephant-child/page-3.png',
      scene: <MeadowScene />,
      text: 'His aunty hippo said "Go to the river and find out yourself!" So off he went on a big adventure.',
      elements: [
        {
          id: 'hippo',
          x: 30,
          y: 42,
          content: '\uD83E\uDD9B',
          size: 72,
          z: 3,
        },
        {
          id: 'adventuring-elephant',
          x: 72,
          y: 40,
          content: '\uD83D\uDC18',
          size: 64,
          z: 3,
        },
        {
          id: 'pointing-sign',
          x: 55,
          y: 22,
          content: '\uD83D\uDC49',
          size: 44,
          z: 2,
        },
        {
          id: 'flower-1',
          x: 15,
          y: 62,
          content: '\uD83C\uDF3B',
          size: 36,
          z: 1,
        },
        {
          id: 'flower-2',
          x: 88,
          y: 58,
          content: '\uD83C\uDF3A',
          size: 32,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'hippo-sound',
          type: 'tap-sound',
          targetId: 'hippo',
          data: { say: 'Go find out yourself!' },
        },
        {
          id: 'hippo-wiggle',
          type: 'tap-wiggle',
          targetId: 'hippo',
          data: {},
        },
        {
          id: 'elephant-animate-walk',
          type: 'tap-animate',
          targetId: 'adventuring-elephant',
          data: { animation: 'animate-fly', duration: 1200 },
        },
        {
          id: 'sign-sparkle',
          type: 'tap-sparkle',
          targetId: 'pointing-sign',
          data: {},
        },
        {
          id: 'flower-1-color',
          type: 'tap-color',
          targetId: 'flower-1',
          data: { colors: ['#EF4444', '#F59E0B', '#8B5CF6', '#EC4899', '#10B981'] },
        },
      ],
    },

    // ── Page 4: Meeting the crocodile ──
    {
      bg: 'from-teal-400 to-emerald-700',
      image: '/arthurs-world/images/elephant-child/page-4.png',
      scene: <MeadowScene />,
      text: 'At the great grey-green river, the little elephant met a crocodile! "Hello!" said the elephant.',
      elements: [
        {
          id: 'river-elephant',
          x: 30,
          y: 38,
          content: '\uD83D\uDC18',
          size: 68,
          z: 3,
        },
        {
          id: 'crocodile',
          x: 70,
          y: 45,
          content: '\uD83D\uDC0A',
          size: 72,
          z: 3,
        },
        {
          id: 'river-wave',
          x: 50,
          y: 60,
          content: '\uD83C\uDF0A',
          size: 48,
          z: 1,
        },
        {
          id: 'reed-left',
          x: 12,
          y: 50,
          content: '\uD83C\uDF3F',
          size: 40,
          z: 1,
        },
        {
          id: 'hidden-frog',
          x: 90,
          y: 62,
          content: '\uD83D\uDC38',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'elephant-hello-sound',
          type: 'tap-sound',
          targetId: 'river-elephant',
          data: { say: 'Hello Mister Crocodile!' },
        },
        {
          id: 'croc-wiggle',
          type: 'tap-wiggle',
          targetId: 'crocodile',
          data: {},
        },
        {
          id: 'wave-sparkle',
          type: 'tap-sparkle',
          targetId: 'river-wave',
          data: {},
        },
        {
          id: 'reed-shake',
          type: 'tap-shake',
          targetId: 'reed-left',
          data: {},
        },
        {
          id: 'frog-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-frog',
          data: { content: 'Ribbit! \uD83D\uDC38' },
        },
      ],
    },

    // ── Page 5: Come closer ──
    {
      bg: 'from-teal-500 to-green-800',
      image: '/arthurs-world/images/elephant-child/page-5.png',
      scene: <MeadowScene />,
      text: 'The crocodile whispered "Come closer, and I\'ll tell you what I eat for dinner!"',
      elements: [
        {
          id: 'close-elephant',
          x: 38,
          y: 40,
          content: '\uD83D\uDC18',
          size: 64,
          z: 3,
        },
        {
          id: 'sneaky-croc',
          x: 65,
          y: 45,
          content: '\uD83D\uDC0A',
          size: 76,
          z: 3,
        },
        {
          id: 'whisper-bubble',
          x: 55,
          y: 22,
          content: '\uD83D\uDCAC',
          size: 44,
          z: 2,
        },
        {
          id: 'water-ripple',
          x: 50,
          y: 65,
          content: '\uD83D\uDCA7',
          size: 36,
          z: 1,
        },
        {
          id: 'warning-bird',
          x: 15,
          y: 18,
          content: '\uD83D\uDC26',
          size: 32,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'croc-whisper-sound',
          type: 'tap-sound',
          targetId: 'sneaky-croc',
          data: { say: 'Come closer little one!' },
        },
        {
          id: 'croc-grow',
          type: 'tap-grow',
          targetId: 'sneaky-croc',
          data: {},
        },
        {
          id: 'elephant-wiggle',
          type: 'tap-wiggle',
          targetId: 'close-elephant',
          data: {},
        },
        {
          id: 'bubble-spin',
          type: 'tap-spin',
          targetId: 'whisper-bubble',
          data: {},
        },
        {
          id: 'bird-shake',
          type: 'tap-shake',
          targetId: 'warning-bird',
          data: {},
        },
      ],
    },

    // ── Page 6: SNAP! ──
    {
      bg: 'from-emerald-600 to-green-900',
      image: '/arthurs-world/images/elephant-child/page-6.png',
      scene: <MeadowScene />,
      text: 'SNAP! The crocodile grabbed his nose and pulled and pulled! "Let go!" cried the elephant.',
      elements: [
        {
          id: 'grabbed-elephant',
          x: 32,
          y: 38,
          content: '\uD83D\uDC18',
          size: 68,
          z: 3,
        },
        {
          id: 'biting-croc',
          x: 68,
          y: 42,
          content: '\uD83D\uDC0A',
          size: 80,
          z: 3,
        },
        {
          id: 'snap-effect',
          x: 50,
          y: 30,
          content: '\uD83D\uDCA5',
          size: 52,
          z: 2,
        },
        {
          id: 'tears',
          x: 22,
          y: 25,
          content: '\uD83D\uDE2D',
          size: 40,
          z: 2,
        },
        {
          id: 'splash-water',
          x: 50,
          y: 62,
          content: '\uD83D\uDCA6',
          size: 40,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'croc-shake-bite',
          type: 'tap-shake',
          targetId: 'biting-croc',
          data: {},
        },
        {
          id: 'elephant-letgo-sound',
          type: 'tap-sound',
          targetId: 'grabbed-elephant',
          data: { say: 'Let go of my nose!' },
        },
        {
          id: 'snap-sparkle',
          type: 'tap-sparkle',
          targetId: 'snap-effect',
          data: {},
        },
        {
          id: 'tears-wiggle',
          type: 'tap-wiggle',
          targetId: 'tears',
          data: {},
        },
        {
          id: 'splash-hide',
          type: 'tap-hide',
          targetId: 'splash-water',
          data: {},
        },
      ],
    },

    // ── Page 7: STRETCHING! (key page) ──
    {
      bg: 'from-green-500 to-teal-700',
      image: '/arthurs-world/images/elephant-child/page-7.png',
      scene: <MeadowScene />,
      text: 'The elephant pulled back SO hard! His nose stretched and stretched and STRETCHED!',
      elements: [
        {
          id: 'stretching-elephant',
          x: 25,
          y: 38,
          content: '\uD83D\uDC18',
          size: 72,
          z: 3,
        },
        {
          id: 'pulling-croc',
          x: 78,
          y: 42,
          content: '\uD83D\uDC0A',
          size: 72,
          z: 3,
        },
        {
          id: 'trunk-stretch',
          x: 50,
          y: 40,
          content: '\u27A1\uFE0F',
          size: 56,
          z: 2,
        },
        {
          id: 'effort-stars',
          x: 18,
          y: 22,
          content: '\uD83D\uDCAB',
          size: 40,
          z: 2,
        },
        {
          id: 'stretch-sound-effect',
          x: 50,
          y: 18,
          content: '\uD83D\uDDE3\uFE0F',
          size: 40,
          z: 2,
        },
        {
          id: 'splashing',
          x: 50,
          y: 62,
          content: '\uD83D\uDCA6',
          size: 44,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'trunk-grow',
          type: 'tap-grow',
          targetId: 'trunk-stretch',
          data: {},
        },
        {
          id: 'elephant-pull-shake',
          type: 'tap-shake',
          targetId: 'stretching-elephant',
          data: {},
        },
        {
          id: 'croc-pull-shake',
          type: 'tap-shake',
          targetId: 'pulling-croc',
          data: {},
        },
        {
          id: 'stars-spin',
          type: 'tap-spin',
          targetId: 'effort-stars',
          data: {},
        },
        {
          id: 'stretch-sound',
          type: 'tap-sound',
          targetId: 'stretch-sound-effect',
          data: { say: 'Stretch stretch stretch!' },
        },
        {
          id: 'splash-sparkle',
          type: 'tap-sparkle',
          targetId: 'splashing',
          data: {},
        },
      ],
    },

    // ── Page 8: POP! Long nose! ──
    {
      bg: 'from-teal-400 to-green-600',
      image: '/arthurs-world/images/elephant-child/page-8.png',
      scene: <MeadowScene />,
      text: 'POP! He got free! But his nose was now very, very long! "Oh no, my nose!" he said.',
      elements: [
        {
          id: 'long-nose-elephant',
          x: 45,
          y: 38,
          content: '\uD83D\uDC18',
          size: 80,
          z: 3,
        },
        {
          id: 'fleeing-croc',
          x: 85,
          y: 52,
          content: '\uD83D\uDC0A',
          size: 52,
          z: 2,
        },
        {
          id: 'pop-effect',
          x: 55,
          y: 18,
          content: '\uD83D\uDCA5',
          size: 48,
          z: 2,
        },
        {
          id: 'surprised-face',
          x: 30,
          y: 20,
          content: '\uD83D\uDE32',
          size: 42,
          z: 2,
        },
        {
          id: 'hidden-lizard',
          x: 12,
          y: 60,
          content: '\uD83E\uDD8E',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'elephant-ohno-sound',
          type: 'tap-sound',
          targetId: 'long-nose-elephant',
          data: { say: 'Oh no, my nose is so long!' },
        },
        {
          id: 'elephant-grow-trunk',
          type: 'tap-grow',
          targetId: 'long-nose-elephant',
          data: {},
        },
        {
          id: 'croc-animate-flee',
          type: 'tap-animate',
          targetId: 'fleeing-croc',
          data: { animation: 'animate-fly', duration: 1000 },
        },
        {
          id: 'pop-sparkle',
          type: 'tap-sparkle',
          targetId: 'pop-effect',
          data: {},
        },
        {
          id: 'lizard-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-lizard',
          data: { content: 'Whoa! \uD83E\uDD8E' },
        },
      ],
    },

    // ── Page 9: Amazing trunk! (drag-to-target page) ──
    {
      bg: 'from-green-400 to-emerald-500',
      image: '/arthurs-world/images/elephant-child/page-9.png',
      scene: <MeadowScene />,
      text: 'But wait \u2014 his long trunk was AMAZING! He could pick fruit, spray water, and give big hugs!',
      elements: [
        {
          id: 'happy-elephant',
          x: 45,
          y: 38,
          content: '\uD83D\uDC18',
          size: 80,
          z: 3,
        },
        {
          id: 'draggable-fruit',
          x: 80,
          y: 20,
          content: '\uD83C\uDF4C',
          size: 48,
          z: 4,
        },
        {
          id: 'water-spray',
          x: 18,
          y: 30,
          content: '\uD83D\uDCA6',
          size: 44,
          z: 2,
        },
        {
          id: 'heart-hug',
          x: 72,
          y: 55,
          content: '\u2764\uFE0F',
          size: 40,
          z: 2,
        },
        {
          id: 'tree-with-fruit',
          x: 88,
          y: 12,
          content: '\uD83C\uDF34',
          size: 52,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'fruit-drag-to-elephant',
          type: 'drag-to-target',
          targetId: 'draggable-fruit',
          data: { dropZone: { x: 45, y: 38, radius: 45 }, onDrop: 'snap' },
        },
        {
          id: 'elephant-yay-sound',
          type: 'tap-sound',
          targetId: 'happy-elephant',
          data: { say: 'My trunk is amazing!' },
        },
        {
          id: 'water-sparkle',
          type: 'tap-sparkle',
          targetId: 'water-spray',
          data: {},
        },
        {
          id: 'heart-grow',
          type: 'tap-grow',
          targetId: 'heart-hug',
          data: {},
        },
        {
          id: 'tree-wiggle',
          type: 'tap-wiggle',
          targetId: 'tree-with-fruit',
          data: {},
        },
      ],
    },

    // ── Page 10: The End ──
    {
      bg: 'from-emerald-300 to-green-500',
      image: '/arthurs-world/images/elephant-child/page-10.png',
      scene: <MeadowScene />,
      text: 'And that is how elephants got their long trunks! The end!',
      elements: [
        {
          id: 'proud-elephant',
          x: 45,
          y: 35,
          content: '\uD83D\uDC18',
          size: 84,
          z: 3,
        },
        {
          id: 'elephant-friend-1',
          x: 18,
          y: 42,
          content: '\uD83D\uDC18',
          size: 56,
          z: 2,
        },
        {
          id: 'elephant-friend-2',
          x: 78,
          y: 40,
          content: '\uD83D\uDC18',
          size: 60,
          z: 2,
        },
        {
          id: 'celebration-star',
          x: 50,
          y: 15,
          content: '\u2B50',
          size: 48,
          z: 2,
        },
        {
          id: 'party-popper',
          x: 30,
          y: 18,
          content: '\uD83C\uDF89',
          size: 40,
          z: 2,
        },
        {
          id: 'rainbow',
          x: 70,
          y: 12,
          content: '\uD83C\uDF08',
          size: 44,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'elephant-end-sparkle',
          type: 'tap-sparkle',
          targetId: 'proud-elephant',
          data: {},
        },
        {
          id: 'elephant-end-sound',
          type: 'tap-sound',
          targetId: 'proud-elephant',
          data: { say: 'The end!' },
        },
        {
          id: 'friend-1-animate',
          type: 'tap-animate',
          targetId: 'elephant-friend-1',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'friend-2-animate',
          type: 'tap-animate',
          targetId: 'elephant-friend-2',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'star-color',
          type: 'tap-color',
          targetId: 'celebration-star',
          data: { colors: ['#FBBF24', '#EF4444', '#8B5CF6', '#3B82F6', '#10B981', '#EC4899'] },
        },
        {
          id: 'popper-spin',
          type: 'tap-spin',
          targetId: 'party-popper',
          data: {},
        },
      ],
    },
  ],
};

export default function ElephantChild() {
  return <StoryBook story={storyData} />;
}
