import React from 'react';
import StoryBook from '../components/StoryBook';
import ForestScene from '../components/scenes/ForestScene';

const storyData = {
  title: 'How the First Letter Was Written',
  audioDir: '/arthurs-world/audio/first-letter',
  pages: [
    // ── Page 1: Fishing by the river ──
    {
      bg: 'from-amber-200 to-green-400',
      image: '/arthurs-world/images/first-letter/page-1.png',
      scene: <ForestScene />,
      text: 'Once upon a time, a little girl called Taffy went fishing with her daddy by the river.',
      elements: [
        {
          id: 'taffy',
          x: 35,
          y: 38,
          content: '\uD83D\uDC67',
          size: 64,
          z: 3,
        },
        {
          id: 'daddy',
          x: 60,
          y: 36,
          content: '\uD83E\uDDD4',
          size: 68,
          z: 3,
        },
        {
          id: 'fishing-rod',
          x: 75,
          y: 50,
          content: '\uD83C\uDFA3',
          size: 48,
          z: 2,
        },
        {
          id: 'river-wave',
          x: 50,
          y: 68,
          content: '\uD83C\uDF0A',
          size: 44,
          z: 1,
        },
        {
          id: 'hidden-fish',
          x: 20,
          y: 65,
          content: '\uD83D\uDC1F',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-wiggle',
          type: 'tap-wiggle',
          targetId: 'taffy',
          data: {},
        },
        {
          id: 'daddy-grow',
          type: 'tap-grow',
          targetId: 'daddy',
          data: {},
        },
        {
          id: 'rod-spin',
          type: 'tap-spin',
          targetId: 'fishing-rod',
          data: {},
        },
        {
          id: 'river-sparkle',
          type: 'tap-sparkle',
          targetId: 'river-wave',
          data: {},
        },
        {
          id: 'fish-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-fish',
          data: { content: 'Splash! \uD83D\uDC1F' },
        },
      ],
    },

    // ── Page 2: Daddy's spear broke ──
    {
      bg: 'from-amber-300 to-orange-400',
      image: '/arthurs-world/images/first-letter/page-2.png',
      scene: <ForestScene />,
      text: "Oh no! Daddy's fishing spear broke! He needed a new one from home.",
      elements: [
        {
          id: 'sad-daddy',
          x: 40,
          y: 35,
          content: '\uD83E\uDDD4',
          size: 68,
          z: 3,
        },
        {
          id: 'broken-spear',
          x: 65,
          y: 45,
          content: '\uD83E\uDE78',
          size: 56,
          z: 2,
        },
        {
          id: 'worried-taffy',
          x: 20,
          y: 40,
          content: '\uD83D\uDC67',
          size: 58,
          z: 3,
        },
        {
          id: 'home-far',
          x: 85,
          y: 22,
          content: '\uD83C\uDFE0',
          size: 42,
          z: 1,
        },
        {
          id: 'crack-effect',
          x: 55,
          y: 55,
          content: '\uD83D\uDCA5',
          size: 40,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'daddy-shake',
          type: 'tap-shake',
          targetId: 'sad-daddy',
          data: {},
        },
        {
          id: 'spear-swap',
          type: 'tap-swap',
          targetId: 'broken-spear',
          data: { altContent: '\uD83D\uDDE1\uFE0F' },
        },
        {
          id: 'taffy-sound',
          type: 'tap-sound',
          targetId: 'worried-taffy',
          data: { say: 'Oh no!' },
        },
        {
          id: 'home-sparkle',
          type: 'tap-sparkle',
          targetId: 'home-far',
          data: {},
        },
        {
          id: 'crack-wiggle',
          type: 'tap-wiggle',
          targetId: 'crack-effect',
          data: {},
        },
      ],
    },

    // ── Page 3: Taffy has an idea ──
    {
      bg: 'from-yellow-200 to-amber-400',
      image: '/arthurs-world/images/first-letter/page-3.png',
      scene: <ForestScene />,
      text: 'Taffy had a great idea! She found a piece of bark and drew a picture on it!',
      elements: [
        {
          id: 'idea-taffy',
          x: 30,
          y: 35,
          content: '\uD83D\uDC67',
          size: 64,
          z: 3,
        },
        {
          id: 'lightbulb',
          x: 30,
          y: 18,
          content: '\uD83D\uDCA1',
          size: 42,
          z: 4,
        },
        {
          id: 'bark-piece',
          x: 60,
          y: 45,
          content: '\uD83E\uDEB5',
          size: 56,
          z: 2,
        },
        {
          id: 'drawing-marks',
          x: 60,
          y: 32,
          content: '\u270D\uFE0F',
          size: 40,
          z: 3,
        },
        {
          id: 'hidden-butterfly',
          x: 85,
          y: 25,
          content: '\uD83E\uDD8B',
          size: 28,
          z: 1,
        },
        {
          id: 'tree-stump',
          x: 80,
          y: 60,
          content: '\uD83E\uDEB5',
          size: 36,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-sparkle',
          type: 'tap-sparkle',
          targetId: 'idea-taffy',
          data: {},
        },
        {
          id: 'lightbulb-color',
          type: 'tap-color',
          targetId: 'lightbulb',
          data: { colors: ['#FACC15', '#FB923C', '#F472B6', '#A78BFA', '#34D399'] },
        },
        {
          id: 'bark-grow',
          type: 'tap-grow',
          targetId: 'bark-piece',
          data: {},
        },
        {
          id: 'drawing-count',
          type: 'tap-count',
          targetId: 'drawing-marks',
          data: { max: 5 },
        },
        {
          id: 'butterfly-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-butterfly',
          data: { content: 'Flutter! \uD83E\uDD8B' },
        },
        {
          id: 'stump-wiggle',
          type: 'tap-wiggle',
          targetId: 'tree-stump',
          data: {},
        },
      ],
    },

    // ── Page 4: The very first letter ──
    {
      bg: 'from-orange-200 to-amber-500',
      image: '/arthurs-world/images/first-letter/page-4.png',
      scene: <ForestScene />,
      text: 'She drew Daddy, the broken spear, and their home. It was the very first letter ever!',
      elements: [
        {
          id: 'proud-taffy',
          x: 25,
          y: 38,
          content: '\uD83D\uDC67',
          size: 60,
          z: 3,
        },
        {
          id: 'letter-bark',
          x: 55,
          y: 40,
          content: '\uD83D\uDCDC',
          size: 64,
          z: 3,
        },
        {
          id: 'drawing-daddy',
          x: 50,
          y: 25,
          content: '\uD83E\uDDD4',
          size: 28,
          z: 4,
        },
        {
          id: 'drawing-spear',
          x: 62,
          y: 25,
          content: '\uD83E\uDE78',
          size: 24,
          z: 4,
        },
        {
          id: 'drawing-home',
          x: 56,
          y: 18,
          content: '\uD83C\uDFE0',
          size: 24,
          z: 4,
        },
        {
          id: 'sparkle-star',
          x: 78,
          y: 35,
          content: '\u2728',
          size: 36,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'taffy-animate',
          type: 'tap-animate',
          targetId: 'proud-taffy',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'letter-sparkle',
          type: 'tap-sparkle',
          targetId: 'letter-bark',
          data: {},
        },
        {
          id: 'letter-grow',
          type: 'tap-grow',
          targetId: 'letter-bark',
          data: {},
        },
        {
          id: 'drawing-daddy-wiggle',
          type: 'tap-wiggle',
          targetId: 'drawing-daddy',
          data: {},
        },
        {
          id: 'drawing-spear-shake',
          type: 'tap-shake',
          targetId: 'drawing-spear',
          data: {},
        },
        {
          id: 'star-spin',
          type: 'tap-spin',
          targetId: 'sparkle-star',
          data: {},
        },
      ],
    },

    // ── Page 5: The stranger arrives ──
    {
      bg: 'from-green-300 to-amber-400',
      image: '/arthurs-world/images/first-letter/page-5.png',
      scene: <ForestScene />,
      text: 'A stranger came by and Taffy gave him the picture to take to Mummy.',
      elements: [
        {
          id: 'taffy-giving',
          x: 30,
          y: 38,
          content: '\uD83D\uDC67',
          size: 58,
          z: 3,
        },
        {
          id: 'stranger',
          x: 70,
          y: 36,
          content: '\uD83E\uDDD4\u200D\u2642\uFE0F',
          size: 64,
          z: 3,
        },
        {
          id: 'draggable-letter',
          x: 42,
          y: 48,
          content: '\uD83D\uDCDC',
          size: 48,
          z: 4,
        },
        {
          id: 'pointing-hand',
          x: 50,
          y: 28,
          content: '\uD83D\uDC49',
          size: 36,
          z: 2,
        },
        {
          id: 'hidden-bird',
          x: 15,
          y: 20,
          content: '\uD83D\uDC26',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'letter-drag',
          type: 'drag-to-target',
          targetId: 'draggable-letter',
          data: { dropZone: { x: 70, y: 36, radius: 40 }, onDrop: 'snap' },
        },
        {
          id: 'taffy-sound',
          type: 'tap-sound',
          targetId: 'taffy-giving',
          data: { say: 'Please take this to Mummy!' },
        },
        {
          id: 'stranger-wiggle',
          type: 'tap-wiggle',
          targetId: 'stranger',
          data: {},
        },
        {
          id: 'pointing-sparkle',
          type: 'tap-sparkle',
          targetId: 'pointing-hand',
          data: {},
        },
        {
          id: 'bird-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-bird',
          data: { content: 'Tweet! \uD83D\uDC26' },
        },
      ],
    },

    // ── Page 6: The stranger is confused ──
    {
      bg: 'from-amber-300 to-rose-400',
      image: '/arthurs-world/images/first-letter/page-6.png',
      scene: <ForestScene />,
      text: "But the stranger didn't understand the picture! He thought it meant something different!",
      elements: [
        {
          id: 'confused-stranger',
          x: 45,
          y: 35,
          content: '\uD83E\uDDD4\u200D\u2642\uFE0F',
          size: 68,
          z: 3,
        },
        {
          id: 'question-mark-1',
          x: 25,
          y: 25,
          content: '\u2753',
          size: 44,
          z: 2,
        },
        {
          id: 'question-mark-2',
          x: 70,
          y: 22,
          content: '\u2753',
          size: 40,
          z: 2,
        },
        {
          id: 'upside-letter',
          x: 45,
          y: 55,
          content: '\uD83D\uDCDC',
          size: 50,
          z: 2,
        },
        {
          id: 'dizzy-stars',
          x: 60,
          y: 40,
          content: '\uD83D\uDCAB',
          size: 34,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'stranger-shake',
          type: 'tap-shake',
          targetId: 'confused-stranger',
          data: {},
        },
        {
          id: 'stranger-sound',
          type: 'tap-sound',
          targetId: 'confused-stranger',
          data: { say: 'I do not understand!' },
        },
        {
          id: 'question-1-spin',
          type: 'tap-spin',
          targetId: 'question-mark-1',
          data: {},
        },
        {
          id: 'question-2-color',
          type: 'tap-color',
          targetId: 'question-mark-2',
          data: { colors: ['#EF4444', '#F59E0B', '#8B5CF6', '#3B82F6', '#EC4899'] },
        },
        {
          id: 'letter-swap',
          type: 'tap-swap',
          targetId: 'upside-letter',
          data: { altContent: '\uD83E\uDD37' },
        },
      ],
    },

    // ── Page 7: Everyone comes from the village ──
    {
      bg: 'from-green-300 to-emerald-500',
      image: '/arthurs-world/images/first-letter/page-7.png',
      scene: <ForestScene />,
      text: 'He brought ALL the people from the village! Everyone was very confused!',
      elements: [
        {
          id: 'person-1',
          x: 15,
          y: 35,
          content: '\uD83D\uDC69',
          size: 48,
          z: 2,
        },
        {
          id: 'person-2',
          x: 30,
          y: 32,
          content: '\uD83E\uDDD3',
          size: 48,
          z: 2,
        },
        {
          id: 'person-3',
          x: 50,
          y: 34,
          content: '\uD83D\uDC68',
          size: 48,
          z: 2,
        },
        {
          id: 'person-4',
          x: 70,
          y: 33,
          content: '\uD83E\uDDD1',
          size: 48,
          z: 2,
        },
        {
          id: 'person-5',
          x: 85,
          y: 36,
          content: '\uD83D\uDC75',
          size: 48,
          z: 2,
        },
        {
          id: 'crowd-noise',
          x: 50,
          y: 55,
          content: '\uD83D\uDDE3\uFE0F',
          size: 44,
          z: 3,
        },
      ],
      interactions: [
        {
          id: 'person-1-wiggle',
          type: 'tap-wiggle',
          targetId: 'person-1',
          data: {},
        },
        {
          id: 'person-2-shake',
          type: 'tap-shake',
          targetId: 'person-2',
          data: {},
        },
        {
          id: 'person-3-spin',
          type: 'tap-spin',
          targetId: 'person-3',
          data: {},
        },
        {
          id: 'person-4-grow',
          type: 'tap-grow',
          targetId: 'person-4',
          data: {},
        },
        {
          id: 'person-5-animate',
          type: 'tap-animate',
          targetId: 'person-5',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'crowd-count',
          type: 'tap-count',
          targetId: 'crowd-noise',
          data: { max: 5 },
        },
      ],
    },

    // ── Page 8: Mummy sees the mix-up ──
    {
      bg: 'from-rose-200 to-amber-300',
      image: '/arthurs-world/images/first-letter/page-8.png',
      scene: <ForestScene />,
      text: 'Mummy came too and saw the silly mix-up. Everyone laughed and laughed!',
      elements: [
        {
          id: 'mummy',
          x: 40,
          y: 32,
          content: '\uD83D\uDC69',
          size: 68,
          z: 3,
        },
        {
          id: 'laughing-1',
          x: 15,
          y: 45,
          content: '\uD83D\uDE02',
          size: 44,
          z: 2,
        },
        {
          id: 'laughing-2',
          x: 75,
          y: 42,
          content: '\uD83E\uDD23',
          size: 44,
          z: 2,
        },
        {
          id: 'silly-taffy',
          x: 55,
          y: 50,
          content: '\uD83D\uDC67',
          size: 56,
          z: 3,
        },
        {
          id: 'hidden-flower',
          x: 88,
          y: 65,
          content: '\uD83C\uDF3B',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'mummy-sparkle',
          type: 'tap-sparkle',
          targetId: 'mummy',
          data: {},
        },
        {
          id: 'mummy-sound',
          type: 'tap-sound',
          targetId: 'mummy',
          data: { say: 'Oh Taffy, what a silly mix-up!' },
        },
        {
          id: 'laughing-1-shake',
          type: 'tap-shake',
          targetId: 'laughing-1',
          data: {},
        },
        {
          id: 'laughing-2-animate',
          type: 'tap-animate',
          targetId: 'laughing-2',
          data: { animation: 'animate-bounce', duration: 800 },
        },
        {
          id: 'taffy-hide',
          type: 'tap-hide',
          targetId: 'silly-taffy',
          data: {},
        },
        {
          id: 'flower-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-flower',
          data: { content: 'Pretty! \uD83C\uDF3B' },
        },
      ],
    },

    // ── Page 9: Taffy will try again ──
    {
      bg: 'from-yellow-200 to-orange-300',
      image: '/arthurs-world/images/first-letter/page-9.png',
      scene: <ForestScene />,
      text: "Taffy said 'Next time, I'll draw BETTER pictures so everyone understands!'",
      elements: [
        {
          id: 'determined-taffy',
          x: 35,
          y: 35,
          content: '\uD83D\uDC67',
          size: 68,
          z: 3,
        },
        {
          id: 'new-letter',
          x: 60,
          y: 40,
          content: '\uD83D\uDCDD',
          size: 52,
          z: 3,
        },
        {
          id: 'star-left',
          x: 15,
          y: 25,
          content: '\u2B50',
          size: 36,
          z: 2,
        },
        {
          id: 'star-right',
          x: 85,
          y: 22,
          content: '\u2B50',
          size: 32,
          z: 2,
        },
        {
          id: 'rainbow',
          x: 50,
          y: 15,
          content: '\uD83C\uDF08',
          size: 48,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-sound',
          type: 'tap-sound',
          targetId: 'determined-taffy',
          data: { say: 'I will try again!' },
        },
        {
          id: 'taffy-grow',
          type: 'tap-grow',
          targetId: 'determined-taffy',
          data: {},
        },
        {
          id: 'new-letter-sparkle',
          type: 'tap-sparkle',
          targetId: 'new-letter',
          data: {},
        },
        {
          id: 'star-left-spin',
          type: 'tap-spin',
          targetId: 'star-left',
          data: {},
        },
        {
          id: 'star-right-color',
          type: 'tap-color',
          targetId: 'star-right',
          data: { colors: ['#FACC15', '#F472B6', '#38BDF8', '#A78BFA', '#34D399'] },
        },
        {
          id: 'rainbow-wiggle',
          type: 'tap-wiggle',
          targetId: 'rainbow',
          data: {},
        },
      ],
    },

    // ── Page 10: The End ──
    {
      bg: 'from-amber-200 to-orange-400',
      image: '/arthurs-world/images/first-letter/page-10.png',
      scene: <ForestScene />,
      text: 'And that is how the very first letter was written! Now we can all write to each other! The end!',
      elements: [
        {
          id: 'happy-taffy',
          x: 30,
          y: 35,
          content: '\uD83D\uDC67',
          size: 64,
          z: 3,
        },
        {
          id: 'happy-daddy',
          x: 55,
          y: 33,
          content: '\uD83E\uDDD4',
          size: 68,
          z: 3,
        },
        {
          id: 'happy-mummy',
          x: 42,
          y: 25,
          content: '\uD83D\uDC69',
          size: 56,
          z: 2,
        },
        {
          id: 'final-letter',
          x: 80,
          y: 40,
          content: '\uD83D\uDCDC',
          size: 52,
          z: 3,
        },
        {
          id: 'celebration',
          x: 15,
          y: 22,
          content: '\uD83C\uDF89',
          size: 44,
          z: 2,
        },
        {
          id: 'hidden-heart',
          x: 88,
          y: 62,
          content: '\u2764\uFE0F',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'taffy-animate',
          type: 'tap-animate',
          targetId: 'happy-taffy',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'daddy-sparkle',
          type: 'tap-sparkle',
          targetId: 'happy-daddy',
          data: {},
        },
        {
          id: 'mummy-wiggle',
          type: 'tap-wiggle',
          targetId: 'happy-mummy',
          data: {},
        },
        {
          id: 'letter-sound',
          type: 'tap-sound',
          targetId: 'final-letter',
          data: { say: 'The very first letter!' },
        },
        {
          id: 'celebration-shake',
          type: 'tap-shake',
          targetId: 'celebration',
          data: {},
        },
        {
          id: 'heart-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-heart',
          data: { content: 'Love! \u2764\uFE0F' },
        },
      ],
    },
  ],
};

export default function FirstLetter() {
  return <StoryBook story={storyData} />;
}
