import React from 'react';
import StoryBook from '../components/StoryBook';
import ForestScene from '../components/scenes/ForestScene';
import CottageScene from '../components/scenes/CottageScene';

const storyData = {
  title: 'Goldilocks',
  audioDir: '/arthurs-world/audio/goldilocks',
  pages: [
    // ── Page 1: Walk in the forest ──
    {
      bg: 'from-green-400 to-green-700',
      scene: <ForestScene />,
      image: '/arthurs-world/images/goldilocks/page-1.png',
      text: 'Once upon a time, a little girl called Goldilocks went for a walk in the forest.',
      elements: [
        {
          id: 'girl-1',
          x: 45,
          y: 55,
          content: <span>👧</span>,
          size: 56,
          z: 12,
        },
        {
          id: 'flower-1',
          x: 25,
          y: 68,
          content: <span>🌸</span>,
          size: 40,
          z: 10,
        },
        {
          id: 'butterfly-1',
          x: 65,
          y: 35,
          content: <span>🦋</span>,
          size: 38,
          z: 11,
        },
        {
          id: 'tree-1',
          x: 80,
          y: 50,
          content: <span>🌲</span>,
          size: 52,
          z: 8,
        },
        {
          id: 'mushroom-1',
          x: 14,
          y: 72,
          content: <span>🍄</span>,
          size: 28,
          z: 9,
        },
      ],
      interactions: [
        {
          id: 'int-1a',
          type: 'tap-sound',
          targetId: 'girl-1',
          data: { say: 'What a lovely day!' },
        },
        {
          id: 'int-1b',
          type: 'tap-animate',
          targetId: 'butterfly-1',
          data: { animation: 'animate-fly', duration: 1200 },
        },
        {
          id: 'int-1c',
          type: 'tap-color',
          targetId: 'flower-1',
          data: { colors: ['#f9a8d4', '#c084fc', '#fde047', '#fb7185', '#a78bfa'] },
        },
        {
          id: 'int-1d',
          type: 'tap-grow',
          targetId: 'tree-1',
          data: {},
        },
        {
          id: 'int-1e',
          type: 'tap-reveal',
          targetId: 'mushroom-1',
          data: { content: <span>🐛</span> },
        },
      ],
    },

    // ── Page 2: Finding the cottage ──
    {
      bg: 'from-green-300 to-amber-200',
      scene: <CottageScene />,
      image: '/arthurs-world/images/goldilocks/page-2.png',
      text: 'She found a little cottage in the woods. Who lives here?',
      elements: [
        {
          id: 'cottage-2',
          x: 50,
          y: 40,
          content: <span>🏠</span>,
          size: 64,
          z: 10,
        },
        {
          id: 'girl-2',
          x: 28,
          y: 60,
          content: <span>👧</span>,
          size: 52,
          z: 12,
        },
        {
          id: 'door-2',
          x: 50,
          y: 58,
          content: <span>🚪</span>,
          size: 44,
          z: 11,
        },
        {
          id: 'window-2',
          x: 68,
          y: 34,
          content: <span>🪟</span>,
          size: 32,
          z: 9,
        },
        {
          id: 'bird-2',
          x: 82,
          y: 22,
          content: <span>🐦</span>,
          size: 28,
          z: 11,
        },
      ],
      interactions: [
        {
          id: 'int-2a',
          type: 'tap-grow',
          targetId: 'cottage-2',
          data: {},
        },
        {
          id: 'int-2b',
          type: 'tap-sound',
          targetId: 'girl-2',
          data: { say: 'I wonder who lives here?' },
        },
        {
          id: 'int-2c',
          type: 'tap-reveal',
          targetId: 'door-2',
          data: { content: <span>🔓</span> },
        },
        {
          id: 'int-2d',
          type: 'tap-sparkle',
          targetId: 'window-2',
          data: {},
        },
        {
          id: 'int-2e',
          type: 'tap-animate',
          targetId: 'bird-2',
          data: { animation: 'animate-fly', duration: 1000 },
        },
      ],
    },

    // ── Page 3: Three bowls of porridge ──
    {
      bg: 'from-amber-100 to-amber-300',
      scene: <CottageScene />,
      image: '/arthurs-world/images/goldilocks/page-3.png',
      text: 'Inside she found three bowls of porridge. Big, medium and small!',
      elements: [
        {
          id: 'bowl-big',
          x: 25,
          y: 50,
          content: <span>🥣</span>,
          size: 60,
          z: 10,
        },
        {
          id: 'bowl-medium',
          x: 50,
          y: 52,
          content: <span>🥣</span>,
          size: 48,
          z: 10,
        },
        {
          id: 'bowl-small',
          x: 72,
          y: 54,
          content: <span>🥣</span>,
          size: 38,
          z: 10,
        },
        {
          id: 'steam-3',
          x: 25,
          y: 36,
          content: <span>♨️</span>,
          size: 36,
          z: 9,
        },
        {
          id: 'ice-3',
          x: 50,
          y: 38,
          content: <span>❄️</span>,
          size: 26,
          z: 9,
        },
      ],
      interactions: [
        {
          id: 'int-3a',
          type: 'tap-swap',
          targetId: 'bowl-big',
          data: { altContent: <span>🔥🥣🔥</span> },
        },
        {
          id: 'int-3a2',
          type: 'tap-sound',
          targetId: 'bowl-big',
          data: { say: 'Too hot!' },
        },
        {
          id: 'int-3b',
          type: 'tap-swap',
          targetId: 'bowl-medium',
          data: { altContent: <span>🧊🥣🧊</span> },
        },
        {
          id: 'int-3b2',
          type: 'tap-sound',
          targetId: 'bowl-medium',
          data: { say: 'Too cold!' },
        },
        {
          id: 'int-3c',
          type: 'tap-swap',
          targetId: 'bowl-small',
          data: { altContent: <span>✨🥣✨</span> },
        },
        {
          id: 'int-3c2',
          type: 'tap-sound',
          targetId: 'bowl-small',
          data: { say: 'Just right!' },
        },
        {
          id: 'int-3d',
          type: 'tap-wiggle',
          targetId: 'steam-3',
          data: {},
        },
        {
          id: 'int-3e',
          type: 'tap-spin',
          targetId: 'ice-3',
          data: {},
        },
      ],
    },

    // ── Page 4: Eating the porridge ──
    {
      bg: 'from-amber-100 to-amber-300',
      scene: <CottageScene />,
      image: '/arthurs-world/images/goldilocks/page-4.png',
      text: 'Goldilocks ate up all the little bowl of porridge. Yum yum!',
      elements: [
        {
          id: 'girl-4',
          x: 40,
          y: 48,
          content: <span>👧</span>,
          size: 56,
          z: 12,
        },
        {
          id: 'bowl-4',
          x: 60,
          y: 56,
          content: <span>🥣</span>,
          size: 42,
          z: 10,
        },
        {
          id: 'spoon-4',
          x: 78,
          y: 42,
          content: <span>🥄</span>,
          size: 36,
          z: 11,
        },
        {
          id: 'yum-4',
          x: 28,
          y: 32,
          content: <span>😋</span>,
          size: 30,
          z: 9,
        },
      ],
      interactions: [
        {
          id: 'int-4a',
          type: 'tap-count',
          targetId: 'bowl-4',
          data: { max: 5 },
        },
        {
          id: 'int-4b',
          type: 'tap-sound',
          targetId: 'girl-4',
          data: { say: 'Yummy!' },
        },
        {
          id: 'int-4c',
          type: 'drag-to-target',
          targetId: 'spoon-4',
          data: { dropZone: { x: 60, y: 56, radius: 40 }, onDrop: 'snap' },
        },
        {
          id: 'int-4d',
          type: 'tap-spin',
          targetId: 'yum-4',
          data: {},
        },
        {
          id: 'int-4e',
          type: 'tap-reveal',
          targetId: 'yum-4',
          data: { content: <span>🤤</span> },
        },
      ],
    },

    // ── Page 5: Three chairs ──
    {
      bg: 'from-amber-100 to-orange-200',
      scene: <CottageScene />,
      image: '/arthurs-world/images/goldilocks/page-5.png',
      text: 'Then she found three chairs. Big, medium and small!',
      elements: [
        {
          id: 'chair-big',
          x: 22,
          y: 48,
          content: <span>🪑</span>,
          size: 60,
          z: 10,
        },
        {
          id: 'chair-medium',
          x: 48,
          y: 50,
          content: <span>🪑</span>,
          size: 48,
          z: 10,
        },
        {
          id: 'chair-small',
          x: 72,
          y: 52,
          content: <span>🪑</span>,
          size: 38,
          z: 10,
        },
        {
          id: 'cushion-5',
          x: 88,
          y: 65,
          content: <span>🟫</span>,
          size: 24,
          z: 9,
        },
      ],
      interactions: [
        {
          id: 'int-5a',
          type: 'tap-swap',
          targetId: 'chair-big',
          data: { altContent: <span>🪨🪑</span> },
        },
        {
          id: 'int-5a2',
          type: 'tap-sound',
          targetId: 'chair-big',
          data: { say: 'Too hard!' },
        },
        {
          id: 'int-5b',
          type: 'tap-swap',
          targetId: 'chair-medium',
          data: { altContent: <span>☁️🪑</span> },
        },
        {
          id: 'int-5b2',
          type: 'tap-sound',
          targetId: 'chair-medium',
          data: { say: 'Too soft!' },
        },
        {
          id: 'int-5c',
          type: 'tap-sound',
          targetId: 'chair-small',
          data: { say: 'Just right!' },
        },
        {
          id: 'int-5d',
          type: 'tap-wiggle',
          targetId: 'chair-small',
          data: {},
        },
        {
          id: 'int-5e',
          type: 'tap-reveal',
          targetId: 'cushion-5',
          data: { content: <span>🐁</span> },
        },
      ],
    },

    // ── Page 6: Chair breaks ──
    {
      bg: 'from-amber-200 to-orange-300',
      scene: <CottageScene />,
      image: '/arthurs-world/images/goldilocks/page-6.png',
      text: 'Oh no! The little chair broke! CRASH!',
      elements: [
        {
          id: 'broken-6',
          x: 50,
          y: 55,
          content: <span>💥🪑</span>,
          size: 48,
          z: 10,
        },
        {
          id: 'girl-6',
          x: 35,
          y: 45,
          content: <span>👧</span>,
          size: 52,
          z: 12,
        },
        {
          id: 'star-6a',
          x: 65,
          y: 38,
          content: <span>⭐</span>,
          size: 32,
          z: 11,
        },
        {
          id: 'splinter-6',
          x: 60,
          y: 68,
          content: <span>🪵</span>,
          size: 28,
          z: 9,
        },
        {
          id: 'star-6b',
          x: 72,
          y: 50,
          content: <span>⭐</span>,
          size: 28,
          z: 11,
        },
      ],
      interactions: [
        {
          id: 'int-6a',
          type: 'tap-hide',
          targetId: 'broken-6',
          data: {},
        },
        {
          id: 'int-6b',
          type: 'tap-sound',
          targetId: 'girl-6',
          data: { say: 'Oopsie!' },
        },
        {
          id: 'int-6c',
          type: 'tap-shake',
          targetId: 'star-6a',
          data: {},
        },
        {
          id: 'int-6d',
          type: 'tap-spin',
          targetId: 'splinter-6',
          data: {},
        },
        {
          id: 'int-6e',
          type: 'tap-color',
          targetId: 'star-6b',
          data: { colors: ['#fde047', '#fb923c', '#c084fc', '#4ade80', '#f9a8d4', '#38bdf8'] },
        },
      ],
    },

    // ── Page 7: Three beds ──
    {
      bg: 'from-indigo-200 to-purple-300',
      scene: <CottageScene />,
      image: '/arthurs-world/images/goldilocks/page-7.png',
      text: 'Goldilocks felt sleepy. She found three beds upstairs.',
      elements: [
        {
          id: 'bed-big',
          x: 20,
          y: 50,
          content: <span>🛏️</span>,
          size: 58,
          z: 10,
        },
        {
          id: 'bed-medium',
          x: 48,
          y: 52,
          content: <span>🛏️</span>,
          size: 46,
          z: 10,
        },
        {
          id: 'bed-small',
          x: 73,
          y: 54,
          content: <span>🛏️</span>,
          size: 36,
          z: 10,
        },
        {
          id: 'moon-7',
          x: 85,
          y: 20,
          content: <span>🌙</span>,
          size: 44,
          z: 8,
        },
        {
          id: 'teddy-7',
          x: 15,
          y: 70,
          content: <span>🧸</span>,
          size: 26,
          z: 9,
        },
      ],
      interactions: [
        {
          id: 'int-7a',
          type: 'tap-swap',
          targetId: 'bed-big',
          data: { altContent: <span>🪨🛏️</span> },
        },
        {
          id: 'int-7a2',
          type: 'tap-sound',
          targetId: 'bed-big',
          data: { say: 'Too hard!' },
        },
        {
          id: 'int-7b',
          type: 'tap-swap',
          targetId: 'bed-medium',
          data: { altContent: <span>☁️🛏️</span> },
        },
        {
          id: 'int-7b2',
          type: 'tap-sound',
          targetId: 'bed-medium',
          data: { say: 'Too soft!' },
        },
        {
          id: 'int-7c',
          type: 'tap-sound',
          targetId: 'bed-small',
          data: { say: 'Just right!' },
        },
        {
          id: 'int-7c2',
          type: 'tap-sparkle',
          targetId: 'bed-small',
          data: {},
        },
        {
          id: 'int-7d',
          type: 'tap-grow',
          targetId: 'moon-7',
          data: {},
        },
        {
          id: 'int-7e',
          type: 'tap-reveal',
          targetId: 'teddy-7',
          data: { content: <span>💤</span> },
        },
      ],
    },

    // ── Page 8: Fast asleep ──
    {
      bg: 'from-indigo-300 to-indigo-600',
      scene: <CottageScene />,
      image: '/arthurs-world/images/goldilocks/page-8.png',
      text: 'She fell fast asleep in the little bed. Zzzzz...',
      elements: [
        {
          id: 'sleeping-8',
          x: 45,
          y: 52,
          content: <span>😴</span>,
          size: 56,
          z: 12,
        },
        {
          id: 'zzz-8',
          x: 60,
          y: 35,
          content: <span style={{ fontWeight: 'bold', color: '#c7d2fe' }}>Zzz</span>,
          size: 36,
          z: 11,
        },
        {
          id: 'star-8a',
          x: 25,
          y: 22,
          content: <span>⭐</span>,
          size: 28,
          z: 10,
        },
        {
          id: 'star-8b',
          x: 75,
          y: 18,
          content: <span>⭐</span>,
          size: 24,
          z: 10,
        },
        {
          id: 'blanket-8',
          x: 45,
          y: 66,
          content: <span>🟪</span>,
          size: 22,
          z: 9,
        },
      ],
      interactions: [
        {
          id: 'int-8a',
          type: 'tap-animate',
          targetId: 'zzz-8',
          data: { animation: 'animate-fly', duration: 1200 },
        },
        {
          id: 'int-8b',
          type: 'tap-sparkle',
          targetId: 'star-8a',
          data: {},
        },
        {
          id: 'int-8c',
          type: 'tap-count',
          targetId: 'star-8b',
          data: { max: 5 },
        },
        {
          id: 'int-8d',
          type: 'tap-wiggle',
          targetId: 'sleeping-8',
          data: {},
        },
        {
          id: 'int-8e',
          type: 'tap-reveal',
          targetId: 'blanket-8',
          data: { content: <span>🧶</span> },
        },
      ],
    },

    // ── Page 9: The three bears come home ──
    {
      bg: 'from-amber-200 to-amber-400',
      scene: <CottageScene />,
      image: '/arthurs-world/images/goldilocks/page-9.png',
      text: "The three bears came home! Who's been eating my porridge?",
      elements: [
        {
          id: 'papa-bear',
          x: 22,
          y: 45,
          content: <span>🐻</span>,
          size: 64,
          z: 12,
        },
        {
          id: 'mama-bear',
          x: 48,
          y: 48,
          content: <span>🐻</span>,
          size: 52,
          z: 12,
        },
        {
          id: 'baby-bear',
          x: 70,
          y: 52,
          content: <span>🧸</span>,
          size: 42,
          z: 12,
        },
        {
          id: 'bowls-9',
          x: 50,
          y: 68,
          content: <span>🥣🥣🥣</span>,
          size: 30,
          z: 10,
        },
        {
          id: 'doorway-9',
          x: 88,
          y: 38,
          content: <span>🚪</span>,
          size: 34,
          z: 8,
        },
      ],
      interactions: [
        {
          id: 'int-9a',
          type: 'tap-shake',
          targetId: 'papa-bear',
          data: {},
        },
        {
          id: 'int-9a2',
          type: 'tap-sound',
          targetId: 'papa-bear',
          data: { say: "Who's been eating MY porridge?" },
        },
        {
          id: 'int-9b',
          type: 'tap-shake',
          targetId: 'mama-bear',
          data: {},
        },
        {
          id: 'int-9b2',
          type: 'tap-sound',
          targetId: 'mama-bear',
          data: { say: "Who's been sitting in MY chair?" },
        },
        {
          id: 'int-9c',
          type: 'tap-sound',
          targetId: 'baby-bear',
          data: { say: "Who's sleeping in MY bed?" },
        },
        {
          id: 'int-9c2',
          type: 'tap-wiggle',
          targetId: 'baby-bear',
          data: {},
        },
        {
          id: 'int-9d',
          type: 'tap-grow',
          targetId: 'papa-bear',
          data: {},
        },
        {
          id: 'int-9e',
          type: 'tap-spin',
          targetId: 'doorway-9',
          data: {},
        },
      ],
    },

    // ── Page 10: Goldilocks runs home ──
    {
      bg: 'from-green-300 to-green-600',
      scene: <ForestScene />,
      image: '/arthurs-world/images/goldilocks/page-10.png',
      text: 'Goldilocks woke up and ran all the way home! The end!',
      elements: [
        {
          id: 'girl-10',
          x: 30,
          y: 50,
          content: <span>👧</span>,
          size: 52,
          z: 12,
        },
        {
          id: 'bears-10',
          x: 72,
          y: 48,
          content: <span>🐻👋</span>,
          size: 48,
          z: 11,
        },
        {
          id: 'hearts-10',
          x: 50,
          y: 28,
          content: <span>❤️</span>,
          size: 36,
          z: 10,
        },
        {
          id: 'flowers-10',
          x: 55,
          y: 68,
          content: <span>🌸</span>,
          size: 34,
          z: 9,
        },
        {
          id: 'rainbow-10',
          x: 50,
          y: 18,
          content: <span>🌈</span>,
          size: 42,
          z: 8,
        },
      ],
      interactions: [
        {
          id: 'int-10a',
          type: 'tap-animate',
          targetId: 'girl-10',
          data: { animation: 'animate-dance', duration: 1200 },
        },
        {
          id: 'int-10b',
          type: 'tap-sound',
          targetId: 'bears-10',
          data: { say: 'Bye bye!' },
        },
        {
          id: 'int-10c',
          type: 'tap-sparkle',
          targetId: 'hearts-10',
          data: {},
        },
        {
          id: 'int-10d',
          type: 'tap-sparkle',
          targetId: 'flowers-10',
          data: {},
        },
        {
          id: 'int-10e',
          type: 'tap-sparkle',
          targetId: 'rainbow-10',
          data: {},
        },
        {
          id: 'int-10f',
          type: 'tap-color',
          targetId: 'hearts-10',
          data: { colors: ['#f9a8d4', '#ef4444', '#a78bfa', '#f472b6', '#fb7185'] },
        },
      ],
    },
  ],
};

export default function Goldilocks() {
  return <StoryBook story={storyData} />;
}
