import React from 'react';
import StoryBook from '../components/StoryBook';
import MeadowScene from '../components/scenes/MeadowScene';

const storyData = {
  title: 'The Sing-Song of Old Man Kangaroo',
  audioDir: '/arthurs-world/audio/old-man-kangaroo',
  pages: [
    // ── Page 1: Four Short Legs ──
    {
      bg: 'from-amber-200 to-orange-400',
      image: '/arthurs-world/images/old-man-kangaroo/page-1.png',
      scene: <MeadowScene />,
      text: 'A long time ago, Kangaroo had four short legs, all the same size. He walked slowly like everyone else.',
      elements: [
        {
          id: 'kangaroo-walking',
          x: 50,
          y: 38,
          content: '\uD83E\uDD98',
          size: 76,
          z: 3,
        },
        {
          id: 'sun-outback',
          x: 82,
          y: 14,
          content: '\u2600\uFE0F',
          size: 52,
          z: 1,
        },
        {
          id: 'tree-left',
          x: 12,
          y: 48,
          content: '\uD83C\uDF33',
          size: 52,
          z: 2,
        },
        {
          id: 'turtle-slow',
          x: 75,
          y: 58,
          content: '\uD83D\uDC22',
          size: 36,
          z: 2,
        },
        {
          id: 'hidden-worm',
          x: 30,
          y: 68,
          content: '\uD83E\uDEB1',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'kangaroo-walk-wiggle',
          type: 'tap-wiggle',
          targetId: 'kangaroo-walking',
          data: {},
        },
        {
          id: 'sun-spin',
          type: 'tap-spin',
          targetId: 'sun-outback',
          data: {},
        },
        {
          id: 'tree-shake',
          type: 'tap-shake',
          targetId: 'tree-left',
          data: {},
        },
        {
          id: 'turtle-slow-wiggle',
          type: 'tap-wiggle',
          targetId: 'turtle-slow',
          data: {},
        },
        {
          id: 'worm-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-worm',
          data: { content: 'A worm! \uD83E\uDEB1' },
        },
      ],
    },

    // ── Page 2: Boastful Kangaroo ──
    {
      bg: 'from-yellow-300 to-orange-500',
      image: '/arthurs-world/images/old-man-kangaroo/page-2.png',
      scene: <MeadowScene />,
      text: 'Kangaroo was a bit boastful. He said "I want to be DIFFERENT from all the other animals!"',
      elements: [
        {
          id: 'proud-kangaroo',
          x: 50,
          y: 36,
          content: '\uD83E\uDD98',
          size: 80,
          z: 3,
        },
        {
          id: 'speech-bubble',
          x: 50,
          y: 12,
          content: '\uD83D\uDCAC',
          size: 44,
          z: 2,
        },
        {
          id: 'zebra-watching',
          x: 15,
          y: 48,
          content: '\uD83E\uDD93',
          size: 44,
          z: 2,
        },
        {
          id: 'elephant-watching',
          x: 85,
          y: 44,
          content: '\uD83D\uDC18',
          size: 48,
          z: 2,
        },
        {
          id: 'star-special',
          x: 32,
          y: 18,
          content: '\u2B50',
          size: 32,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'kangaroo-boast-grow',
          type: 'tap-grow',
          targetId: 'proud-kangaroo',
          data: {},
        },
        {
          id: 'kangaroo-boast-sound',
          type: 'tap-sound',
          targetId: 'proud-kangaroo',
          data: { say: 'I want to be different!' },
        },
        {
          id: 'speech-sparkle',
          type: 'tap-sparkle',
          targetId: 'speech-bubble',
          data: {},
        },
        {
          id: 'zebra-wiggle',
          type: 'tap-wiggle',
          targetId: 'zebra-watching',
          data: {},
        },
        {
          id: 'star-color',
          type: 'tap-color',
          targetId: 'star-special',
          data: { colors: ['#FBBF24', '#EC4899', '#8B5CF6', '#22C55E', '#EF4444'] },
        },
      ],
    },

    // ── Page 3: Asks Nqong ──
    {
      bg: 'from-orange-300 to-red-400',
      image: '/arthurs-world/images/old-man-kangaroo/page-3.png',
      scene: <MeadowScene />,
      text: 'He went to the big god Nqong and said "Make me special! Make me famous by five o\'clock today!"',
      elements: [
        {
          id: 'nqong-god',
          x: 30,
          y: 30,
          content: '\uD83E\uDDDE',
          size: 84,
          z: 3,
        },
        {
          id: 'begging-kangaroo',
          x: 70,
          y: 44,
          content: '\uD83E\uDD98',
          size: 64,
          z: 3,
        },
        {
          id: 'magic-sparkles',
          x: 30,
          y: 10,
          content: '\u2728',
          size: 40,
          z: 2,
        },
        {
          id: 'clock-five',
          x: 88,
          y: 14,
          content: '\uD83D\uDD54',
          size: 38,
          z: 2,
        },
        {
          id: 'hidden-spider',
          x: 14,
          y: 66,
          content: '\uD83D\uDD77\uFE0F',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'nqong-sparkle',
          type: 'tap-sparkle',
          targetId: 'nqong-god',
          data: {},
        },
        {
          id: 'nqong-grow',
          type: 'tap-grow',
          targetId: 'nqong-god',
          data: {},
        },
        {
          id: 'kangaroo-beg-sound',
          type: 'tap-sound',
          targetId: 'begging-kangaroo',
          data: { say: 'Make me special!' },
        },
        {
          id: 'clock-spin',
          type: 'tap-spin',
          targetId: 'clock-five',
          data: {},
        },
        {
          id: 'spider-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-spider',
          data: { content: 'A spider! \uD83D\uDD77\uFE0F' },
        },
      ],
    },

    // ── Page 4: Dingo Summoned ──
    {
      bg: 'from-red-300 to-orange-500',
      image: '/arthurs-world/images/old-man-kangaroo/page-4.png',
      scene: <MeadowScene />,
      text: 'Nqong pointed to a big yellow dog called Dingo and said "Dingo! Chase that kangaroo!"',
      elements: [
        {
          id: 'nqong-pointing',
          x: 20,
          y: 28,
          content: '\uD83E\uDDDE',
          size: 72,
          z: 3,
        },
        {
          id: 'dingo-dog',
          x: 50,
          y: 42,
          content: '\uD83D\uDC15',
          size: 68,
          z: 3,
        },
        {
          id: 'scared-kangaroo',
          x: 80,
          y: 40,
          content: '\uD83E\uDD98',
          size: 60,
          z: 3,
        },
        {
          id: 'pointing-finger',
          x: 36,
          y: 32,
          content: '\uD83D\uDC49',
          size: 36,
          z: 2,
        },
        {
          id: 'exclamation',
          x: 80,
          y: 16,
          content: '\u2757',
          size: 36,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'nqong-command-sound',
          type: 'tap-sound',
          targetId: 'nqong-pointing',
          data: { say: 'Dingo! Chase that kangaroo!' },
        },
        {
          id: 'dingo-shake',
          type: 'tap-shake',
          targetId: 'dingo-dog',
          data: {},
        },
        {
          id: 'kangaroo-scared-wiggle',
          type: 'tap-wiggle',
          targetId: 'scared-kangaroo',
          data: {},
        },
        {
          id: 'finger-swap',
          type: 'tap-swap',
          targetId: 'pointing-finger',
          data: { altContent: '\uD83D\uDCA8' },
        },
        {
          id: 'exclamation-sparkle',
          type: 'tap-sparkle',
          targetId: 'exclamation',
          data: {},
        },
      ],
    },

    // ── Page 5: Desert Chase ──
    {
      bg: 'from-yellow-400 to-orange-600',
      image: '/arthurs-world/images/old-man-kangaroo/page-5.png',
      scene: <MeadowScene />,
      text: 'Dingo chased Kangaroo across the sandy desert! Run, run, run!',
      elements: [
        {
          id: 'running-kangaroo',
          x: 70,
          y: 38,
          content: '\uD83E\uDD98',
          size: 72,
          z: 3,
        },
        {
          id: 'chasing-dingo',
          x: 30,
          y: 44,
          content: '\uD83D\uDC15',
          size: 64,
          z: 3,
        },
        {
          id: 'dust-cloud-1',
          x: 50,
          y: 58,
          content: '\uD83D\uDCA8',
          size: 40,
          z: 2,
        },
        {
          id: 'cactus-desert',
          x: 12,
          y: 52,
          content: '\uD83C\uDF35',
          size: 44,
          z: 1,
        },
        {
          id: 'hot-sun',
          x: 85,
          y: 12,
          content: '\u2600\uFE0F',
          size: 50,
          z: 1,
        },
        {
          id: 'footprints',
          x: 50,
          y: 68,
          content: '\uD83D\uDC3E',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'kangaroo-run-animate',
          type: 'tap-animate',
          targetId: 'running-kangaroo',
          data: { animation: 'fly', duration: 1000 },
        },
        {
          id: 'kangaroo-run-sound',
          type: 'tap-sound',
          targetId: 'running-kangaroo',
          data: { say: 'Run run run!' },
        },
        {
          id: 'dingo-chase-animate',
          type: 'tap-animate',
          targetId: 'chasing-dingo',
          data: { animation: 'fly', duration: 1000 },
        },
        {
          id: 'dust-shake',
          type: 'tap-shake',
          targetId: 'dust-cloud-1',
          data: {},
        },
        {
          id: 'cactus-wiggle',
          type: 'tap-wiggle',
          targetId: 'cactus-desert',
          data: {},
        },
        {
          id: 'footprints-count',
          type: 'tap-count',
          targetId: 'footprints',
          data: { max: 5 },
        },
      ],
    },

    // ── Page 6: Grassland Chase ──
    {
      bg: 'from-orange-400 to-yellow-600',
      image: '/arthurs-world/images/old-man-kangaroo/page-6.png',
      scene: <MeadowScene />,
      text: 'Dingo chased him through the tall grasslands! Hop, hop, hop! Kangaroo started jumping to go faster!',
      elements: [
        {
          id: 'hopping-kangaroo',
          x: 65,
          y: 34,
          content: '\uD83E\uDD98',
          size: 76,
          z: 3,
        },
        {
          id: 'dingo-grass',
          x: 25,
          y: 46,
          content: '\uD83D\uDC15',
          size: 60,
          z: 3,
        },
        {
          id: 'grass-tall',
          x: 45,
          y: 60,
          content: '\uD83C\uDF3F',
          size: 44,
          z: 2,
        },
        {
          id: 'dust-puff',
          x: 45,
          y: 52,
          content: '\uD83D\uDCA8',
          size: 36,
          z: 2,
        },
        {
          id: 'hidden-snake',
          x: 88,
          y: 64,
          content: '\uD83D\uDC0D',
          size: 22,
          z: 1,
        },
        {
          id: 'bird-watching',
          x: 14,
          y: 16,
          content: '\uD83E\uDD9C',
          size: 36,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'kangaroo-hop-animate',
          type: 'tap-animate',
          targetId: 'hopping-kangaroo',
          data: { animation: 'fly', duration: 1000 },
        },
        {
          id: 'kangaroo-hop-sound',
          type: 'tap-sound',
          targetId: 'hopping-kangaroo',
          data: { say: 'Hop hop hop!' },
        },
        {
          id: 'dingo-grass-shake',
          type: 'tap-shake',
          targetId: 'dingo-grass',
          data: {},
        },
        {
          id: 'grass-wiggle',
          type: 'tap-wiggle',
          targetId: 'grass-tall',
          data: {},
        },
        {
          id: 'snake-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-snake',
          data: { content: 'A snake! \uD83D\uDC0D' },
        },
        {
          id: 'bird-spin',
          type: 'tap-spin',
          targetId: 'bird-watching',
          data: {},
        },
      ],
    },

    // ── Page 7: Mountain Chase ──
    {
      bg: 'from-red-400 to-orange-600',
      image: '/arthurs-world/images/old-man-kangaroo/page-7.png',
      scene: <MeadowScene />,
      text: 'Dingo chased him over the rocky mountains! JUMP! JUMP! JUMP! His back legs grew bigger and stronger!',
      elements: [
        {
          id: 'jumping-kangaroo',
          x: 60,
          y: 28,
          content: '\uD83E\uDD98',
          size: 80,
          z: 3,
        },
        {
          id: 'dingo-mountain',
          x: 22,
          y: 50,
          content: '\uD83D\uDC15',
          size: 56,
          z: 3,
        },
        {
          id: 'mountain-peak',
          x: 50,
          y: 18,
          content: '\u26F0\uFE0F',
          size: 52,
          z: 1,
        },
        {
          id: 'rocks',
          x: 78,
          y: 60,
          content: '\uD83E\uDEA8',
          size: 36,
          z: 2,
        },
        {
          id: 'muscle-grow',
          x: 80,
          y: 22,
          content: '\uD83D\uDCAA',
          size: 40,
          z: 2,
        },
        {
          id: 'mountain-target',
          x: 50,
          y: 22,
          content: '',
          size: 10,
          z: 0,
        },
      ],
      interactions: [
        {
          id: 'kangaroo-jump-animate',
          type: 'tap-animate',
          targetId: 'jumping-kangaroo',
          data: { animation: 'fly', duration: 1200 },
        },
        {
          id: 'kangaroo-jump-sound',
          type: 'tap-sound',
          targetId: 'jumping-kangaroo',
          data: { say: 'JUMP! JUMP! JUMP!' },
        },
        {
          id: 'dingo-mountain-shake',
          type: 'tap-shake',
          targetId: 'dingo-mountain',
          data: {},
        },
        {
          id: 'muscle-grow-big',
          type: 'tap-grow',
          targetId: 'muscle-grow',
          data: {},
        },
        {
          id: 'rocks-drag-to-mountain',
          type: 'drag-to-target',
          targetId: 'rocks',
          data: { dropZone: { x: 50, y: 22, radius: 45 }, onDrop: 'snap' },
        },
        {
          id: 'mountain-sparkle',
          type: 'tap-sparkle',
          targetId: 'mountain-peak',
          data: {},
        },
      ],
    },

    // ── Page 8: New Legs ──
    {
      bg: 'from-amber-400 to-red-500',
      image: '/arthurs-world/images/old-man-kangaroo/page-8.png',
      scene: <MeadowScene />,
      text: 'By the time Dingo stopped chasing, Kangaroo\'s back legs were HUGE and his front legs were tiny!',
      elements: [
        {
          id: 'changed-kangaroo',
          x: 50,
          y: 36,
          content: '\uD83E\uDD98',
          size: 84,
          z: 3,
        },
        {
          id: 'tired-dingo',
          x: 18,
          y: 52,
          content: '\uD83D\uDC15',
          size: 52,
          z: 2,
        },
        {
          id: 'sweat-drops',
          x: 18,
          y: 34,
          content: '\uD83D\uDCA6',
          size: 32,
          z: 2,
        },
        {
          id: 'big-legs',
          x: 68,
          y: 58,
          content: '\uD83E\uDDB6',
          size: 44,
          z: 2,
        },
        {
          id: 'tiny-arms',
          x: 34,
          y: 30,
          content: '\uD83E\uDDB6',
          size: 20,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'kangaroo-changed-grow',
          type: 'tap-grow',
          targetId: 'changed-kangaroo',
          data: {},
        },
        {
          id: 'kangaroo-changed-sparkle',
          type: 'tap-sparkle',
          targetId: 'changed-kangaroo',
          data: {},
        },
        {
          id: 'dingo-tired-wiggle',
          type: 'tap-wiggle',
          targetId: 'tired-dingo',
          data: {},
        },
        {
          id: 'big-legs-shake',
          type: 'tap-shake',
          targetId: 'big-legs',
          data: {},
        },
        {
          id: 'tiny-arms-hide',
          type: 'tap-hide',
          targetId: 'tiny-arms',
          data: {},
        },
      ],
    },

    // ── Page 9: Bouncy Kangaroo ──
    {
      bg: 'from-yellow-300 to-amber-500',
      image: '/arthurs-world/images/old-man-kangaroo/page-9.png',
      scene: <MeadowScene />,
      text: 'Now Kangaroo could HOP so high and so far! He was the bounciest animal in the whole world!',
      elements: [
        {
          id: 'bouncy-kangaroo',
          x: 50,
          y: 30,
          content: '\uD83E\uDD98',
          size: 84,
          z: 3,
        },
        {
          id: 'cloud-high',
          x: 30,
          y: 10,
          content: '\u2601\uFE0F',
          size: 44,
          z: 1,
        },
        {
          id: 'rainbow-arc',
          x: 75,
          y: 14,
          content: '\uD83C\uDF08',
          size: 48,
          z: 1,
        },
        {
          id: 'bounce-stars',
          x: 50,
          y: 56,
          content: '\u2B50',
          size: 36,
          z: 2,
        },
        {
          id: 'baby-joey',
          x: 50,
          y: 46,
          content: '\uD83E\uDD98',
          size: 28,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'kangaroo-bounce-animate',
          type: 'tap-animate',
          targetId: 'bouncy-kangaroo',
          data: { animation: 'animate-bounce', duration: 1200 },
        },
        {
          id: 'kangaroo-bounce-sound',
          type: 'tap-sound',
          targetId: 'bouncy-kangaroo',
          data: { say: 'Boing! Boing! Boing!' },
        },
        {
          id: 'cloud-spin',
          type: 'tap-spin',
          targetId: 'cloud-high',
          data: {},
        },
        {
          id: 'stars-count',
          type: 'tap-count',
          targetId: 'bounce-stars',
          data: { max: 5 },
        },
        {
          id: 'joey-wiggle',
          type: 'tap-wiggle',
          targetId: 'baby-joey',
          data: {},
        },
      ],
    },

    // ── Page 10: The End ──
    {
      bg: 'from-orange-300 to-red-500',
      image: '/arthurs-world/images/old-man-kangaroo/page-10.png',
      scene: <MeadowScene />,
      text: 'And that is how the kangaroo got his strong jumping legs! The end!',
      elements: [
        {
          id: 'happy-kangaroo',
          x: 50,
          y: 34,
          content: '\uD83E\uDD98',
          size: 84,
          z: 3,
        },
        {
          id: 'hearts-end',
          x: 50,
          y: 12,
          content: '\u2764\uFE0F',
          size: 40,
          z: 2,
        },
        {
          id: 'dingo-friend',
          x: 82,
          y: 50,
          content: '\uD83D\uDC15',
          size: 48,
          z: 2,
        },
        {
          id: 'party-popper',
          x: 18,
          y: 22,
          content: '\uD83C\uDF89',
          size: 40,
          z: 2,
        },
        {
          id: 'hidden-lizard',
          x: 25,
          y: 64,
          content: '\uD83E\uDD8E',
          size: 22,
          z: 1,
        },
        {
          id: 'sunset-end',
          x: 85,
          y: 14,
          content: '\uD83C\uDF05',
          size: 44,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'kangaroo-end-sparkle',
          type: 'tap-sparkle',
          targetId: 'happy-kangaroo',
          data: {},
        },
        {
          id: 'kangaroo-end-sound',
          type: 'tap-sound',
          targetId: 'happy-kangaroo',
          data: { say: 'The end!' },
        },
        {
          id: 'hearts-color',
          type: 'tap-color',
          targetId: 'hearts-end',
          data: { colors: ['#EF4444', '#EC4899', '#F59E0B', '#8B5CF6', '#22C55E'] },
        },
        {
          id: 'party-spin',
          type: 'tap-spin',
          targetId: 'party-popper',
          data: {},
        },
        {
          id: 'lizard-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-lizard',
          data: { content: 'A lizard! \uD83E\uDD8E' },
        },
        {
          id: 'dingo-friend-wiggle',
          type: 'tap-wiggle',
          targetId: 'dingo-friend',
          data: {},
        },
      ],
    },
  ],
};

export default function OldManKangaroo() {
  return <StoryBook story={storyData} />;
}
