import React from 'react';
import StoryBook from '../components/StoryBook';
import MeadowScene from '../components/scenes/MeadowScene';

const storyData = {
  title: 'How the Rhinoceros Got His Skin',
  audioDir: '/arthurs-world/audio/rhino-skin',
  pages: [
    // ── Page 1: The Man and His Cake ──
    {
      bg: 'from-sky-300 to-emerald-400',
      image: '/arthurs-world/images/rhino-skin/page-1.png',
      scene: <MeadowScene />,
      text: 'Once upon a time, a man lived on an island. He made the most yummy cake!',
      elements: [
        {
          id: 'man',
          x: 30,
          y: 40,
          content: '\uD83E\uDDD1\u200D\uD83C\uDF73',
          size: 68,
          z: 3,
        },
        {
          id: 'cake',
          x: 55,
          y: 50,
          content: '\uD83C\uDF82',
          size: 56,
          z: 3,
        },
        {
          id: 'palm-tree',
          x: 85,
          y: 32,
          content: '\uD83C\uDF34',
          size: 60,
          z: 2,
        },
        {
          id: 'island',
          x: 50,
          y: 68,
          content: '\uD83C\uDFDD\uFE0F',
          size: 48,
          z: 1,
        },
        {
          id: 'hidden-crab',
          x: 14,
          y: 66,
          content: '\uD83E\uDD80',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'man-yummy-sound',
          type: 'tap-sound',
          targetId: 'man',
          data: { say: 'My yummy cake!' },
        },
        {
          id: 'cake-sparkle',
          type: 'tap-sparkle',
          targetId: 'cake',
          data: {},
        },
        {
          id: 'cake-grow',
          type: 'tap-grow',
          targetId: 'cake',
          data: {},
        },
        {
          id: 'palm-wiggle',
          type: 'tap-wiggle',
          targetId: 'palm-tree',
          data: {},
        },
        {
          id: 'crab-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-crab',
          data: { content: 'A crab! \uD83E\uDD80' },
        },
      ],
    },

    // ── Page 2: The Smooth Rhinoceros ──
    {
      bg: 'from-amber-200 to-sky-400',
      image: '/arthurs-world/images/rhino-skin/page-2.png',
      scene: <MeadowScene />,
      text: 'A big rhinoceros came along. His skin was smooth and shiny and fitted like a button!',
      elements: [
        {
          id: 'rhino',
          x: 50,
          y: 40,
          content: '\uD83E\uDD8F',
          size: 84,
          z: 3,
        },
        {
          id: 'sparkle-skin',
          x: 50,
          y: 20,
          content: '\u2728',
          size: 40,
          z: 2,
        },
        {
          id: 'beach',
          x: 20,
          y: 65,
          content: '\uD83C\uDFD6\uFE0F',
          size: 44,
          z: 1,
        },
        {
          id: 'sun',
          x: 82,
          y: 14,
          content: '\u2600\uFE0F',
          size: 52,
          z: 1,
        },
        {
          id: 'hidden-seashell',
          x: 88,
          y: 64,
          content: '\uD83D\uDC1A',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'rhino-shiny-sparkle',
          type: 'tap-sparkle',
          targetId: 'rhino',
          data: {},
        },
        {
          id: 'rhino-color',
          type: 'tap-color',
          targetId: 'sparkle-skin',
          data: { colors: ['#facc15', '#38bdf8', '#a78bfa', '#fb923c', '#22c55e'] },
        },
        {
          id: 'sun-spin',
          type: 'tap-spin',
          targetId: 'sun',
          data: {},
        },
        {
          id: 'beach-wiggle',
          type: 'tap-wiggle',
          targetId: 'beach',
          data: {},
        },
        {
          id: 'seashell-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-seashell',
          data: { content: 'A seashell! \uD83D\uDC1A' },
        },
      ],
    },

    // ── Page 3: Rhinoceros Eats the Cake ──
    {
      bg: 'from-red-300 to-orange-400',
      image: '/arthurs-world/images/rhino-skin/page-3.png',
      scene: <MeadowScene />,
      text: 'The cheeky rhinoceros ate ALL the man\'s cake! Every last crumb!',
      elements: [
        {
          id: 'eating-rhino',
          x: 42,
          y: 38,
          content: '\uD83E\uDD8F',
          size: 80,
          z: 3,
        },
        {
          id: 'sad-man',
          x: 78,
          y: 42,
          content: '\uD83D\uDE2D',
          size: 52,
          z: 3,
        },
        {
          id: 'empty-plate',
          x: 42,
          y: 60,
          content: '\uD83C\uDF7D\uFE0F',
          size: 40,
          z: 2,
        },
        {
          id: 'crumb-1',
          x: 60,
          y: 56,
          content: '\uD83C\uDF6A',
          size: 24,
          z: 2,
        },
        {
          id: 'crumb-2',
          x: 28,
          y: 58,
          content: '\uD83C\uDF6A',
          size: 20,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'rhino-eating-shake',
          type: 'tap-shake',
          targetId: 'eating-rhino',
          data: {},
        },
        {
          id: 'rhino-chomp-sound',
          type: 'tap-sound',
          targetId: 'eating-rhino',
          data: { say: 'Chomp chomp chomp!' },
        },
        {
          id: 'crumb-1-hide',
          type: 'tap-hide',
          targetId: 'crumb-1',
          data: {},
        },
        {
          id: 'crumb-2-hide',
          type: 'tap-hide',
          targetId: 'crumb-2',
          data: {},
        },
        {
          id: 'plate-spin',
          type: 'tap-spin',
          targetId: 'empty-plate',
          data: {},
        },
      ],
    },

    // ── Page 4: The Man is Cross ──
    {
      bg: 'from-red-400 to-rose-600',
      image: '/arthurs-world/images/rhino-skin/page-4.png',
      scene: <MeadowScene />,
      text: 'The man was very cross! He wanted his yummy cake back!',
      elements: [
        {
          id: 'angry-man',
          x: 45,
          y: 38,
          content: '\uD83D\uDE21',
          size: 72,
          z: 3,
        },
        {
          id: 'fist',
          x: 70,
          y: 30,
          content: '\u270A',
          size: 48,
          z: 2,
        },
        {
          id: 'crumbs-floor',
          x: 45,
          y: 62,
          content: '\uD83C\uDF6A',
          size: 28,
          z: 1,
        },
        {
          id: 'angry-symbol',
          x: 25,
          y: 18,
          content: '\uD83D\uDCA2',
          size: 36,
          z: 2,
        },
        {
          id: 'hidden-lizard',
          x: 12,
          y: 66,
          content: '\uD83E\uDD8E',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'man-cross-sound',
          type: 'tap-sound',
          targetId: 'angry-man',
          data: { say: 'Give me back my cake!' },
        },
        {
          id: 'angry-man-shake',
          type: 'tap-shake',
          targetId: 'angry-man',
          data: {},
        },
        {
          id: 'fist-animate',
          type: 'tap-animate',
          targetId: 'fist',
          data: { animation: 'animate-bounce', duration: 800 },
        },
        {
          id: 'angry-sparkle',
          type: 'tap-sparkle',
          targetId: 'angry-symbol',
          data: {},
        },
        {
          id: 'lizard-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-lizard',
          data: { content: 'A lizard! \uD83E\uDD8E' },
        },
      ],
    },

    // ── Page 5: The Rhino Takes Off His Skin ──
    {
      bg: 'from-cyan-300 to-blue-500',
      image: '/arthurs-world/images/rhino-skin/page-5.png',
      scene: <MeadowScene />,
      text: 'One very hot day, the rhinoceros took off his smooth skin to go swimming!',
      elements: [
        {
          id: 'rhino-skin',
          x: 30,
          y: 55,
          content: '\uD83E\uDDE5',
          size: 56,
          z: 3,
        },
        {
          id: 'swimming-rhino',
          x: 68,
          y: 38,
          content: '\uD83C\uDFCA',
          size: 64,
          z: 3,
        },
        {
          id: 'hot-sun',
          x: 50,
          y: 12,
          content: '\u2600\uFE0F',
          size: 56,
          z: 1,
        },
        {
          id: 'waves',
          x: 68,
          y: 58,
          content: '\uD83C\uDF0A',
          size: 44,
          z: 2,
        },
        {
          id: 'hidden-fish',
          x: 88,
          y: 52,
          content: '\uD83D\uDC20',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'skin-wiggle',
          type: 'tap-wiggle',
          targetId: 'rhino-skin',
          data: {},
        },
        {
          id: 'swimming-rhino-animate',
          type: 'tap-animate',
          targetId: 'swimming-rhino',
          data: { animation: 'animate-bounce', duration: 900 },
        },
        {
          id: 'splash-sound',
          type: 'tap-sound',
          targetId: 'swimming-rhino',
          data: { say: 'Splish splash!' },
        },
        {
          id: 'sun-grow',
          type: 'tap-grow',
          targetId: 'hot-sun',
          data: {},
        },
        {
          id: 'fish-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-fish',
          data: { content: 'A fishy! \uD83D\uDC20' },
        },
      ],
    },

    // ── Page 6: The Sneaky Idea ──
    {
      bg: 'from-violet-300 to-amber-400',
      image: '/arthurs-world/images/rhino-skin/page-6.png',
      scene: <MeadowScene />,
      text: 'The man found the skin on the beach! He had a sneaky idea...',
      elements: [
        {
          id: 'sneaky-man',
          x: 35,
          y: 38,
          content: '\uD83D\uDE0F',
          size: 68,
          z: 3,
        },
        {
          id: 'rhino-skin-beach',
          x: 65,
          y: 52,
          content: '\uD83E\uDDE5',
          size: 52,
          z: 3,
        },
        {
          id: 'thinking-bubble',
          x: 35,
          y: 16,
          content: '\uD83D\uDCA1',
          size: 44,
          z: 2,
        },
        {
          id: 'beach-bg',
          x: 82,
          y: 66,
          content: '\uD83C\uDFD6\uFE0F',
          size: 40,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'sneaky-man-swap',
          type: 'tap-swap',
          targetId: 'sneaky-man',
          data: { altContent: '\uD83D\uDE08' },
        },
        {
          id: 'idea-sparkle',
          type: 'tap-sparkle',
          targetId: 'thinking-bubble',
          data: {},
        },
        {
          id: 'man-sneaky-sound',
          type: 'tap-sound',
          targetId: 'sneaky-man',
          data: { say: 'I have an idea!' },
        },
        {
          id: 'skin-shake',
          type: 'tap-shake',
          targetId: 'rhino-skin-beach',
          data: {},
        },
        {
          id: 'beach-wiggle',
          type: 'tap-wiggle',
          targetId: 'beach-bg',
          data: {},
        },
      ],
    },

    // ── Page 7: Filling the Skin with Crumbs (Drag-to-target!) ──
    {
      bg: 'from-amber-300 to-yellow-500',
      image: '/arthurs-world/images/rhino-skin/page-7.png',
      scene: <MeadowScene />,
      text: 'He filled the rhino skin with itchy scratchy cake crumbs! So many crumbs!',
      elements: [
        {
          id: 'filling-man',
          x: 25,
          y: 40,
          content: '\uD83D\uDE0F',
          size: 60,
          z: 3,
        },
        {
          id: 'skin-target',
          x: 65,
          y: 45,
          content: '\uD83E\uDDE5',
          size: 60,
          z: 2,
        },
        {
          id: 'drag-crumbs',
          x: 25,
          y: 62,
          content: '\uD83C\uDF6A',
          size: 44,
          z: 4,
        },
        {
          id: 'crumbs-everywhere',
          x: 50,
          y: 68,
          content: '\u2728',
          size: 32,
          z: 1,
        },
        {
          id: 'crumb-count',
          x: 82,
          y: 60,
          content: '\uD83C\uDF70',
          size: 36,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'crumbs-drag-to-skin',
          type: 'drag-to-target',
          targetId: 'drag-crumbs',
          data: { dropZone: { x: 65, y: 45, radius: 40 }, onDrop: 'snap' },
        },
        {
          id: 'man-hehe-sound',
          type: 'tap-sound',
          targetId: 'filling-man',
          data: { say: 'Hee hee hee!' },
        },
        {
          id: 'crumbs-sparkle',
          type: 'tap-sparkle',
          targetId: 'crumbs-everywhere',
          data: {},
        },
        {
          id: 'crumb-count-tap',
          type: 'tap-count',
          targetId: 'crumb-count',
          data: { max: 5 },
        },
        {
          id: 'skin-target-wiggle',
          type: 'tap-wiggle',
          targetId: 'skin-target',
          data: {},
        },
      ],
    },

    // ── Page 8: SO Itchy! ──
    {
      bg: 'from-red-400 to-orange-500',
      image: '/arthurs-world/images/rhino-skin/page-8.png',
      scene: <MeadowScene />,
      text: 'The rhinoceros put his skin back on. OH NO! It was SO itchy!',
      elements: [
        {
          id: 'itchy-rhino',
          x: 45,
          y: 38,
          content: '\uD83E\uDD8F',
          size: 80,
          z: 3,
        },
        {
          id: 'itch-star-1',
          x: 25,
          y: 25,
          content: '\u2B50',
          size: 32,
          z: 2,
        },
        {
          id: 'itch-star-2',
          x: 68,
          y: 22,
          content: '\u2B50',
          size: 28,
          z: 2,
        },
        {
          id: 'scratch-marks',
          x: 45,
          y: 60,
          content: '\uD83D\uDCA5',
          size: 40,
          z: 2,
        },
        {
          id: 'hidden-bug',
          x: 88,
          y: 65,
          content: '\uD83D\uDC1B',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'rhino-itchy-shake',
          type: 'tap-shake',
          targetId: 'itchy-rhino',
          data: {},
        },
        {
          id: 'rhino-itchy-sound',
          type: 'tap-sound',
          targetId: 'itchy-rhino',
          data: { say: 'Oooh so itchy!' },
        },
        {
          id: 'star-1-spin',
          type: 'tap-spin',
          targetId: 'itch-star-1',
          data: {},
        },
        {
          id: 'scratch-color',
          type: 'tap-color',
          targetId: 'scratch-marks',
          data: { colors: ['#EF4444', '#F59E0B', '#EC4899', '#8B5CF6'] },
        },
        {
          id: 'bug-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-bug',
          data: { content: 'A bug! \uD83D\uDC1B' },
        },
      ],
    },

    // ── Page 9: Scratching and Wrinkling ──
    {
      bg: 'from-green-400 to-emerald-600',
      image: '/arthurs-world/images/rhino-skin/page-9.png',
      scene: <MeadowScene />,
      text: 'He scratched and scratched and rubbed against trees! His skin got all wrinkly and baggy!',
      elements: [
        {
          id: 'scratching-rhino',
          x: 42,
          y: 40,
          content: '\uD83E\uDD8F',
          size: 76,
          z: 3,
        },
        {
          id: 'scratch-tree',
          x: 75,
          y: 35,
          content: '\uD83C\uDF33',
          size: 64,
          z: 2,
        },
        {
          id: 'wrinkle-effect',
          x: 42,
          y: 62,
          content: '\uD83C\uDF00',
          size: 36,
          z: 2,
        },
        {
          id: 'dizzy-stars',
          x: 42,
          y: 18,
          content: '\uD83D\uDCAB',
          size: 36,
          z: 2,
        },
        {
          id: 'hidden-bird',
          x: 82,
          y: 14,
          content: '\uD83D\uDC26',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'rhino-scratch-animate',
          type: 'tap-animate',
          targetId: 'scratching-rhino',
          data: { animation: 'animate-shake', duration: 1000 },
        },
        {
          id: 'tree-shake',
          type: 'tap-shake',
          targetId: 'scratch-tree',
          data: {},
        },
        {
          id: 'wrinkle-spin',
          type: 'tap-spin',
          targetId: 'wrinkle-effect',
          data: {},
        },
        {
          id: 'dizzy-wiggle',
          type: 'tap-wiggle',
          targetId: 'dizzy-stars',
          data: {},
        },
        {
          id: 'bird-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-bird',
          data: { content: 'Tweet tweet! \uD83D\uDC26' },
        },
      ],
    },

    // ── Page 10: The End ──
    {
      bg: 'from-green-300 to-sky-400',
      image: '/arthurs-world/images/rhino-skin/page-10.png',
      scene: <MeadowScene />,
      text: 'And that is how the rhinoceros got his wrinkly skin! The end!',
      elements: [
        {
          id: 'wrinkly-rhino',
          x: 45,
          y: 36,
          content: '\uD83E\uDD8F',
          size: 80,
          z: 3,
        },
        {
          id: 'laughing-man',
          x: 78,
          y: 44,
          content: '\uD83D\uDE02',
          size: 52,
          z: 3,
        },
        {
          id: 'bird-1',
          x: 18,
          y: 18,
          content: '\uD83D\uDC26',
          size: 32,
          z: 2,
        },
        {
          id: 'bird-2',
          x: 32,
          y: 14,
          content: '\uD83D\uDC26',
          size: 28,
          z: 2,
        },
        {
          id: 'hearts',
          x: 45,
          y: 16,
          content: '\u2764\uFE0F',
          size: 40,
          z: 2,
        },
        {
          id: 'hidden-butterfly',
          x: 10,
          y: 58,
          content: '\uD83E\uDD8B',
          size: 22,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'rhino-end-sparkle',
          type: 'tap-sparkle',
          targetId: 'wrinkly-rhino',
          data: {},
        },
        {
          id: 'rhino-end-sound',
          type: 'tap-sound',
          targetId: 'wrinkly-rhino',
          data: { say: 'The end!' },
        },
        {
          id: 'man-laugh-animate',
          type: 'tap-animate',
          targetId: 'laughing-man',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'hearts-color',
          type: 'tap-color',
          targetId: 'hearts',
          data: { colors: ['#EF4444', '#EC4899', '#F59E0B', '#8B5CF6', '#10B981'] },
        },
        {
          id: 'butterfly-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-butterfly',
          data: { content: 'A butterfly! \uD83E\uDD8B' },
        },
      ],
    },
  ],
};

export default function RhinoSkin() {
  return <StoryBook story={storyData} />;
}
