import React from 'react';
import StoryBook from '../components/StoryBook';
import UnderwaterScene from '../components/scenes/UnderwaterScene';

const storyData = {
  title: 'How the Whale Got His Throat',
  audioDir: '/arthurs-world/audio/whale-throat',
  pages: [
    // ── Page 1: Introduction ──
    {
      bg: 'from-blue-400 to-blue-700',
      image: '/arthurs-world/images/whale-throat/page-1.png',
      scene: <UnderwaterScene />,
      text: 'Once upon a time, there was a very big whale who lived in the deep blue sea.',
      elements: [
        {
          id: 'whale',
          x: 50,
          y: 40,
          content: '\uD83D\uDC0B',
          size: 80,
          z: 3,
        },
        {
          id: 'wave-left',
          x: 15,
          y: 20,
          content: '\uD83C\uDF0A',
          size: 48,
          z: 1,
        },
        {
          id: 'fish-bg',
          x: 75,
          y: 55,
          content: '\uD83D\uDC1F',
          size: 36,
          z: 1,
        },
        {
          id: 'bubbles',
          x: 35,
          y: 28,
          content: '\uD83E\uDEE7',
          size: 32,
          z: 1,
        },
        {
          id: 'wave-right',
          x: 85,
          y: 22,
          content: '\uD83C\uDF0A',
          size: 44,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'whale-grow',
          type: 'tap-grow',
          targetId: 'whale',
          data: {},
        },
        {
          id: 'whale-sound',
          type: 'tap-sound',
          targetId: 'whale',
          data: { say: "I'm so hungry!" },
        },
        {
          id: 'wave-wiggle',
          type: 'tap-wiggle',
          targetId: 'wave-left',
          data: {},
        },
        {
          id: 'bubbles-sparkle',
          type: 'tap-sparkle',
          targetId: 'bubbles',
          data: {},
        },
        {
          id: 'wave-right-wiggle',
          type: 'tap-wiggle',
          targetId: 'wave-right',
          data: {},
        },
      ],
    },

    // ── Page 2: Gobble Gobble ──
    {
      bg: 'from-blue-500 to-blue-800',
      image: '/arthurs-world/images/whale-throat/page-2.png',
      scene: <UnderwaterScene />,
      text: 'The whale was SO hungry. He ate all the fish he could find! Gobble gobble!',
      elements: [
        {
          id: 'hungry-whale',
          x: 25,
          y: 38,
          content: '\uD83D\uDC0B',
          size: 84,
          z: 3,
        },
        {
          id: 'fish-1',
          x: 55,
          y: 35,
          content: '\uD83D\uDC1F',
          size: 40,
          z: 2,
        },
        {
          id: 'fish-2',
          x: 68,
          y: 50,
          content: '\uD83D\uDC20',
          size: 38,
          z: 2,
        },
        {
          id: 'fish-3',
          x: 80,
          y: 38,
          content: '\uD83D\uDC21',
          size: 36,
          z: 2,
        },
        {
          id: 'fish-4',
          x: 72,
          y: 25,
          content: '\uD83D\uDC1F',
          size: 34,
          z: 2,
        },
        {
          id: 'chomp',
          x: 40,
          y: 55,
          content: '\uD83D\uDE2C',
          size: 36,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'whale-eating-shake',
          type: 'tap-shake',
          targetId: 'hungry-whale',
          data: {},
        },
        {
          id: 'fish-1-hide',
          type: 'tap-hide',
          targetId: 'fish-1',
          data: {},
        },
        {
          id: 'fish-2-hide',
          type: 'tap-hide',
          targetId: 'fish-2',
          data: {},
        },
        {
          id: 'fish-3-hide',
          type: 'tap-hide',
          targetId: 'fish-3',
          data: {},
        },
        {
          id: 'fish-4-hide',
          type: 'tap-hide',
          targetId: 'fish-4',
          data: {},
        },
        {
          id: 'whale-yum-sound',
          type: 'tap-sound',
          targetId: 'hungry-whale',
          data: { say: 'Yum yum!' },
        },
        {
          id: 'chomp-count',
          type: 'tap-count',
          targetId: 'chomp',
          data: { max: 4 },
        },
      ],
    },

    // ── Page 3: One Fish Left ──
    {
      bg: 'from-blue-300 to-blue-600',
      image: '/arthurs-world/images/whale-throat/page-3.png',
      scene: <UnderwaterScene />,
      text: 'Soon there was only one tiny clever fish left in the whole sea.',
      elements: [
        {
          id: 'clever-fish',
          x: 70,
          y: 45,
          content: '\uD83D\uDC1F',
          size: 32,
          z: 3,
        },
        {
          id: 'sad-whale',
          x: 28,
          y: 40,
          content: '\uD83D\uDC0B',
          size: 80,
          z: 2,
        },
        {
          id: 'empty-water',
          x: 50,
          y: 70,
          content: '\uD83C\uDF0A',
          size: 40,
          z: 1,
        },
        {
          id: 'hidden-starfish',
          x: 85,
          y: 68,
          content: '\u2B50',
          size: 24,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'fish-idea-sound',
          type: 'tap-sound',
          targetId: 'clever-fish',
          data: { say: 'I have an idea!' },
        },
        {
          id: 'fish-wiggle',
          type: 'tap-wiggle',
          targetId: 'clever-fish',
          data: {},
        },
        {
          id: 'whale-grow',
          type: 'tap-grow',
          targetId: 'sad-whale',
          data: {},
        },
        {
          id: 'starfish-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-starfish',
          data: { content: 'Hello! \u2B50' },
        },
        {
          id: 'water-sparkle',
          type: 'tap-sparkle',
          targetId: 'empty-water',
          data: {},
        },
      ],
    },

    // ── Page 4: The Clever Plan ──
    {
      bg: 'from-cyan-400 to-blue-600',
      image: '/arthurs-world/images/whale-throat/page-4.png',
      scene: <UnderwaterScene />,
      text: "The clever fish said: 'Why don't you eat the man on the raft?'",
      elements: [
        {
          id: 'plan-fish',
          x: 25,
          y: 50,
          content: '\uD83D\uDC1F',
          size: 36,
          z: 3,
        },
        {
          id: 'man-raft',
          x: 65,
          y: 28,
          content: '\uD83E\uDDD4',
          size: 52,
          z: 2,
        },
        {
          id: 'raft',
          x: 65,
          y: 38,
          content: '\uD83D\uDEF6',
          size: 56,
          z: 1,
        },
        {
          id: 'hidden-crab',
          x: 15,
          y: 72,
          content: '\uD83E\uDD80',
          size: 24,
          z: 1,
        },
        {
          id: 'pointing',
          x: 42,
          y: 38,
          content: '\uD83D\uDC49',
          size: 32,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'fish-try-sound',
          type: 'tap-sound',
          targetId: 'plan-fish',
          data: { say: 'Try that!' },
        },
        {
          id: 'raft-wiggle',
          type: 'tap-wiggle',
          targetId: 'raft',
          data: {},
        },
        {
          id: 'man-spin',
          type: 'tap-spin',
          targetId: 'man-raft',
          data: {},
        },
        {
          id: 'crab-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-crab',
          data: { content: 'Snip snip! \uD83E\uDD80' },
        },
        {
          id: 'pointing-sparkle',
          type: 'tap-sparkle',
          targetId: 'pointing',
          data: {},
        },
      ],
    },

    // ── Page 5: Whale Swims ──
    {
      bg: 'from-blue-400 to-indigo-700',
      image: '/arthurs-world/images/whale-throat/page-5.png',
      scene: <UnderwaterScene />,
      text: 'The whale swam and swam to find the man. SPLASH!',
      elements: [
        {
          id: 'swimming-whale',
          x: 35,
          y: 42,
          content: '\uD83D\uDC0B',
          size: 76,
          z: 3,
        },
        {
          id: 'splash',
          x: 70,
          y: 30,
          content: '\uD83D\uDCA6',
          size: 48,
          z: 2,
        },
        {
          id: 'wave-1',
          x: 15,
          y: 25,
          content: '\uD83C\uDF0A',
          size: 44,
          z: 1,
        },
        {
          id: 'wave-2',
          x: 85,
          y: 20,
          content: '\uD83C\uDF0A',
          size: 40,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'whale-swim-animate',
          type: 'tap-animate',
          targetId: 'swimming-whale',
          data: { animation: 'animate-fly', duration: 1200 },
        },
        {
          id: 'splash-sparkle',
          type: 'tap-sparkle',
          targetId: 'splash',
          data: {},
        },
        {
          id: 'wave-1-shake',
          type: 'tap-shake',
          targetId: 'wave-1',
          data: {},
        },
        {
          id: 'whale-here-sound',
          type: 'tap-sound',
          targetId: 'swimming-whale',
          data: { say: 'Here I come!' },
        },
        {
          id: 'wave-2-wiggle',
          type: 'tap-wiggle',
          targetId: 'wave-2',
          data: {},
        },
      ],
    },

    // ── Page 6: Swallowed Whole ──
    {
      bg: 'from-blue-600 to-blue-900',
      image: '/arthurs-world/images/whale-throat/page-6.png',
      scene: <UnderwaterScene />,
      text: 'The big whale opened his ENORMOUS mouth and swallowed the man whole!',
      elements: [
        {
          id: 'big-whale-mouth',
          x: 40,
          y: 38,
          content: '\uD83D\uDC0B',
          size: 96,
          z: 3,
        },
        {
          id: 'swallowed-man',
          x: 62,
          y: 42,
          content: '\uD83E\uDDD4',
          size: 44,
          z: 2,
        },
        {
          id: 'gulp-effect',
          x: 50,
          y: 60,
          content: '\uD83D\uDCAB',
          size: 36,
          z: 1,
        },
        {
          id: 'surprised-fish',
          x: 82,
          y: 55,
          content: '\uD83D\uDC1F',
          size: 28,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'mouth-grow',
          type: 'tap-grow',
          targetId: 'big-whale-mouth',
          data: {},
        },
        {
          id: 'whale-gulp-shake',
          type: 'tap-shake',
          targetId: 'big-whale-mouth',
          data: {},
        },
        {
          id: 'man-hide',
          type: 'tap-hide',
          targetId: 'swallowed-man',
          data: {},
        },
        {
          id: 'gulp-sound',
          type: 'tap-sound',
          targetId: 'gulp-effect',
          data: { say: 'GULP!' },
        },
        {
          id: 'fish-wiggle',
          type: 'tap-wiggle',
          targetId: 'surprised-fish',
          data: {},
        },
      ],
    },

    // ── Page 7: Building the Grating ──
    {
      bg: 'from-amber-800 to-rose-900',
      image: '/arthurs-world/images/whale-throat/page-7.png',
      scene: <UnderwaterScene />,
      text: 'But the clever man had a plan! He built a grating inside the whale!',
      elements: [
        {
          id: 'inside-man',
          x: 35,
          y: 45,
          content: '\uD83E\uDDD4',
          size: 52,
          z: 3,
        },
        {
          id: 'grating',
          x: 72,
          y: 30,
          content: '\uD83E\uDEB5',
          size: 52,
          z: 2,
        },
        {
          id: 'hammer',
          x: 55,
          y: 60,
          content: '\uD83D\uDD28',
          size: 44,
          z: 2,
        },
        {
          id: 'grating-target',
          x: 50,
          y: 35,
          content: '',
          size: 10,
          z: 0,
        },
      ],
      interactions: [
        {
          id: 'grating-drag',
          type: 'drag-to-target',
          targetId: 'grating',
          data: { dropZone: { x: 50, y: 35, radius: 40 }, onDrop: 'snap' },
        },
        {
          id: 'hammer-count',
          type: 'tap-count',
          targetId: 'hammer',
          data: { max: 5 },
        },
        {
          id: 'hammer-sound',
          type: 'tap-sound',
          targetId: 'hammer',
          data: { say: 'Tap tap tap!' },
        },
        {
          id: 'man-wiggle',
          type: 'tap-wiggle',
          targetId: 'inside-man',
          data: {},
        },
      ],
    },

    // ── Page 8: Stuck in His Throat ──
    {
      bg: 'from-blue-500 to-purple-700',
      image: '/arthurs-world/images/whale-throat/page-8.png',
      scene: <UnderwaterScene />,
      text: 'The whale coughed and spluttered! The grating was stuck in his throat!',
      elements: [
        {
          id: 'coughing-whale',
          x: 45,
          y: 40,
          content: '\uD83D\uDC0B',
          size: 84,
          z: 3,
        },
        {
          id: 'stuck-grating',
          x: 45,
          y: 55,
          content: '\uD83E\uDEB5',
          size: 40,
          z: 2,
        },
        {
          id: 'star-1',
          x: 20,
          y: 25,
          content: '\u2B50',
          size: 36,
          z: 1,
        },
        {
          id: 'star-2',
          x: 72,
          y: 22,
          content: '\u2B50',
          size: 32,
          z: 1,
        },
        {
          id: 'dizzy',
          x: 60,
          y: 30,
          content: '\uD83D\uDCAB',
          size: 34,
          z: 2,
        },
      ],
      interactions: [
        {
          id: 'whale-cough-shake',
          type: 'tap-shake',
          targetId: 'coughing-whale',
          data: {},
        },
        {
          id: 'star-1-spin',
          type: 'tap-spin',
          targetId: 'star-1',
          data: {},
        },
        {
          id: 'star-2-spin',
          type: 'tap-spin',
          targetId: 'star-2',
          data: {},
        },
        {
          id: 'whale-achoo-sound',
          type: 'tap-sound',
          targetId: 'coughing-whale',
          data: { say: 'Achoo!' },
        },
        {
          id: 'dizzy-sparkle',
          type: 'tap-sparkle',
          targetId: 'dizzy',
          data: {},
        },
      ],
    },

    // ── Page 9: Man Escapes ──
    {
      bg: 'from-cyan-300 to-blue-500',
      image: '/arthurs-world/images/whale-throat/page-9.png',
      scene: <UnderwaterScene />,
      text: 'The man jumped out and sailed away on his raft. Hooray!',
      elements: [
        {
          id: 'escaping-man',
          x: 70,
          y: 30,
          content: '\uD83E\uDDD4',
          size: 52,
          z: 3,
        },
        {
          id: 'escape-raft',
          x: 70,
          y: 40,
          content: '\uD83D\uDEF6',
          size: 52,
          z: 2,
        },
        {
          id: 'sad-whale-end',
          x: 25,
          y: 48,
          content: '\uD83D\uDC0B',
          size: 72,
          z: 2,
        },
        {
          id: 'escape-waves',
          x: 50,
          y: 65,
          content: '\uD83C\uDF0A',
          size: 44,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'man-escape-animate',
          type: 'tap-animate',
          targetId: 'escaping-man',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'man-goodbye-sound',
          type: 'tap-sound',
          targetId: 'escaping-man',
          data: { say: 'Goodbye whale!' },
        },
        {
          id: 'waves-wiggle',
          type: 'tap-wiggle',
          targetId: 'escape-waves',
          data: {},
        },
        {
          id: 'whale-swap-sad',
          type: 'tap-swap',
          targetId: 'sad-whale-end',
          data: { altContent: '\uD83D\uDE22' },
        },
        {
          id: 'raft-shake',
          type: 'tap-shake',
          targetId: 'escape-raft',
          data: {},
        },
      ],
    },

    // ── Page 10: The End ──
    {
      bg: 'from-blue-300 to-cyan-500',
      image: '/arthurs-world/images/whale-throat/page-10.png',
      scene: <UnderwaterScene />,
      text: 'And from that day, the whale could only eat tiny tiny fish. The end!',
      elements: [
        {
          id: 'gentle-whale',
          x: 40,
          y: 35,
          content: '\uD83D\uDC0B',
          size: 76,
          z: 2,
        },
        {
          id: 'tiny-fish',
          x: 65,
          y: 42,
          content: '\uD83D\uDC1F',
          size: 22,
          z: 3,
        },
        {
          id: 'happy-crab',
          x: 18,
          y: 65,
          content: '\uD83E\uDD80',
          size: 40,
          z: 2,
        },
        {
          id: 'happy-octopus',
          x: 78,
          y: 60,
          content: '\uD83D\uDC19',
          size: 42,
          z: 2,
        },
        {
          id: 'happy-fish',
          x: 55,
          y: 58,
          content: '\uD83D\uDC20',
          size: 36,
          z: 2,
        },
        {
          id: 'hidden-pearl',
          x: 88,
          y: 72,
          content: '\uD83E\uDE77',
          size: 24,
          z: 1,
        },
      ],
      interactions: [
        {
          id: 'whale-sparkle',
          type: 'tap-sparkle',
          targetId: 'gentle-whale',
          data: {},
        },
        {
          id: 'fish-dance-animate',
          type: 'tap-animate',
          targetId: 'tiny-fish',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'whale-tiny-sound',
          type: 'tap-sound',
          targetId: 'gentle-whale',
          data: { say: 'Only little fish now!' },
        },
        {
          id: 'creatures-color',
          type: 'tap-color',
          targetId: 'happy-crab',
          data: { colors: ['#EF4444', '#F59E0B', '#8B5CF6', '#EC4899', '#10B981'] },
        },
        {
          id: 'pearl-reveal',
          type: 'tap-reveal',
          targetId: 'hidden-pearl',
          data: { content: 'A shiny pearl! \u2728' },
        },
        {
          id: 'octopus-animate',
          type: 'tap-animate',
          targetId: 'happy-octopus',
          data: { animation: 'animate-dance', duration: 1000 },
        },
        {
          id: 'happy-fish-wiggle',
          type: 'tap-wiggle',
          targetId: 'happy-fish',
          data: {},
        },
      ],
    },
  ],
};

export default function WhaleThroat() {
  return <StoryBook story={storyData} />;
}
