#!/usr/bin/env node
/**
 * Manage the Arthur's World video registry from the command line.
 *
 * Usage:
 *   node scripts/manage-videos.mjs list              — Show all videos with status
 *   node scripts/manage-videos.mjs approve <id>      — Approve a video
 *   node scripts/manage-videos.mjs reject <id>       — Reject a video (hides from Arthur)
 *   node scripts/manage-videos.mjs hide <id>         — Hide without rejecting
 *   node scripts/manage-videos.mjs remove <id>       — Remove from registry + delete files
 *   node scripts/manage-videos.mjs rescreen <id>     — Re-run Claude screening on a video
 *   node scripts/manage-videos.mjs sync              — Regenerate videoData.js + games.js entries from registry
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REGISTRY_PATH = path.join(__dirname, '..', 'data', 'video-registry.json');
const VIDEOS_DIR = path.join(__dirname, '..', 'public', 'videos');

function loadRegistry() {
  return JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf-8'));
}

function saveRegistry(registry) {
  fs.writeFileSync(REGISTRY_PATH, JSON.stringify(registry, null, 2) + '\n');
}

function list() {
  const registry = loadRegistry();
  console.log(`\nVideo Registry (${registry.videos.length} videos)\n`);
  console.log('Status     | ID                      | Title');
  console.log('-'.repeat(70));

  for (const v of registry.videos) {
    const status = v.status.toUpperCase().padEnd(10);
    const id = v.id.padEnd(23);
    const screening = v.screening?.reason ? ` — ${v.screening.reason}` : '';
    console.log(`${status} | ${id} | ${v.title}${screening}`);
  }

  const approved = registry.videos.filter(v => v.status === 'approved').length;
  const rejected = registry.videos.filter(v => v.status === 'rejected').length;
  const hidden = registry.videos.filter(v => v.status === 'hidden').length;
  const pending = registry.videos.filter(v => v.status === 'pending').length;
  console.log(`\nApproved: ${approved} | Rejected: ${rejected} | Hidden: ${hidden} | Pending: ${pending}`);
}

function setStatus(id, status) {
  const registry = loadRegistry();
  const video = registry.videos.find(v => v.id === id);
  if (!video) {
    console.error(`Video "${id}" not found in registry.`);
    console.log('Available IDs:', registry.videos.map(v => v.id).join(', '));
    process.exit(1);
  }

  video.status = status;
  saveRegistry(registry);
  console.log(`"${video.title}" (${id}) is now: ${status}`);
}

function remove(id) {
  const registry = loadRegistry();
  const idx = registry.videos.findIndex(v => v.id === id);
  if (idx === -1) {
    console.error(`Video "${id}" not found in registry.`);
    process.exit(1);
  }

  const video = registry.videos[idx];
  registry.videos.splice(idx, 1);
  saveRegistry(registry);

  // Delete files
  const mp4 = path.join(VIDEOS_DIR, `${id}.mp4`);
  const webp = path.join(VIDEOS_DIR, `${id}.webp`);
  if (fs.existsSync(mp4)) { fs.unlinkSync(mp4); console.log(`  Deleted ${id}.mp4`); }
  if (fs.existsSync(webp)) { fs.unlinkSync(webp); console.log(`  Deleted ${id}.webp`); }

  console.log(`Removed "${video.title}" from registry.`);
}

function sync() {
  const registry = loadRegistry();
  const approved = registry.videos.filter(v => v.status === 'approved');

  // Generate videoData.js
  const videoDataPath = path.join(__dirname, '..', 'src', 'data', 'videoData.js');
  const videoEntries = approved.map(v => `  {
    id: '${v.id}',
    title: ${JSON.stringify(v.title)},
    src: '/arthurs-world/videos/${v.id}.mp4',
    thumb: '/arthurs-world/videos/${v.id}.webp',
    bg: '${v.bg}',
    color: '${v.color}',
  }`).join(',\n');

  const videoDataContent = `/**
 * Video metadata for the offline video player.
 * AUTO-GENERATED by scripts/manage-videos.mjs sync — do not edit manually.
 * Source: data/video-registry.json
 */
const videos = [
${videoEntries}
];

export default videos;
`;

  fs.writeFileSync(videoDataPath, videoDataContent);
  console.log(`Updated videoData.js with ${approved.length} approved videos.`);

  // Generate video entries for games.js
  console.log('\nApproved video entries for games.js (copy if needed):');
  console.log('─'.repeat(60));
  for (const v of approved) {
    console.log(`  { id: '${v.id}', emoji: '', title: ${JSON.stringify(v.title)}, path: 'video/${v.id}', category: 'videos', bg: '${v.bg}', cover: '/arthurs-world/videos/${v.id}.webp' },`);
  }
}

// ── Main ──
const [cmd, ...cmdArgs] = process.argv.slice(2);

switch (cmd) {
  case 'list':
  case 'ls':
    list();
    break;
  case 'approve':
    if (!cmdArgs[0]) { console.error('Usage: manage-videos.mjs approve <id>'); process.exit(1); }
    setStatus(cmdArgs[0], 'approved');
    break;
  case 'reject':
    if (!cmdArgs[0]) { console.error('Usage: manage-videos.mjs reject <id>'); process.exit(1); }
    setStatus(cmdArgs[0], 'rejected');
    break;
  case 'hide':
    if (!cmdArgs[0]) { console.error('Usage: manage-videos.mjs hide <id>'); process.exit(1); }
    setStatus(cmdArgs[0], 'hidden');
    break;
  case 'remove':
  case 'rm':
    if (!cmdArgs[0]) { console.error('Usage: manage-videos.mjs remove <id>'); process.exit(1); }
    remove(cmdArgs[0]);
    break;
  case 'sync':
    sync();
    break;
  default:
    console.log(`
Arthur's World — Video Manager

Usage:
  node scripts/manage-videos.mjs <command> [args]

Commands:
  list                Show all videos with screening status
  approve <id>        Approve a video (makes it visible to Arthur)
  reject <id>         Reject a video (hides from Arthur)
  hide <id>           Hide a video temporarily
  remove <id>         Remove from registry and delete video files
  sync                Regenerate videoData.js from registry

Examples:
  node scripts/manage-videos.mjs list
  node scripts/manage-videos.mjs approve baby-shark
  node scripts/manage-videos.mjs reject scary-video
  node scripts/manage-videos.mjs sync
`);
}
